### ISSUE TITLE
Need Iphlpapi.dll's api, thanks.

### ISSUE THREAD

**Issue by GreatFireWall** [dahall/Vanara#1]

**Comment by dahall** [comment]
This is a massive library. Are there a few critical functions that would help for a first revision? I will commit the project framework shortly. If you want to help, please do a PR and submit.

**Comment by dahall** [comment]
Stub project [here](https://github.com/dahall/Vanara/tree/master/PInvoke/IpHlpApi).

**Comment by dahall** [comment]
Many updates today. Please review and let me know if there are specific functions missing that you require.

**Comment by GreatFireWall** [comment]
Great, thank you very much !
