### ISSUE TITLE
[Question] - Shell32 PIDL[] EqualityComparer

### ISSUE THREAD

**Issue by Sherulez** [dahall/Vanara#100]
When I want to get a set of difference between 2 `PIDL[]` arrays, I'm doing :

```csharp
var diff = pidlArr1.Except(pidlArr2, new PidlComparer());
```

And this is my `Equals` from the `PidlComparer` : 

```csharp
public bool Equals(PIDL pidl1, PIDL pidl2)
{ 
    return Shell32.ILIsEqual(pidl1.DangerousGetHandle(), pidl2.DangerousGetHandle());
}
```
**Is it safer to do it this way (by using `Shell32.ILIsEqual`) ?** 
By "_safer_" I mean : the comparison accuracy

Or should I use the default EqualityComparer ? : 
(Both work)
```csharp
var diff = pidlArr1.Except(pidlArr2);
```

_I hope this silly question does not bother you too much ;)_

**Comment by dahall** [comment]
The `PIDL` class overrides the `Equals` method to use `ILIsEqual`, so they are effectively the same. I would use the default `EqualityComparer` as the `Equals<PIDL>` method directly addresses the memory rather than having to call `DangerousGetHandle()`.

**Comment by Sherulez** [comment]
Understood, Thank you for answering this question even if it is not directly related to Vanara :)
