### ISSUE TITLE
MenuStrip MRU Manager - Item Icon

### ISSUE THREAD

**Issue by DarkByte7** [dahall/Vanara#102]
**Is your feature request related to a problem? Please describe.**
There is no preview for an ```Icon``` assigned in the ```ToolStripMenuItem``` for the specified file path.

**Describe the additions or enhancements you'd like**
- When a file path is added to ```MenuStripMRUManager```. Extract the ```Icon``` from the file if it exists. Then assign it as an ```Image``` to the specified  ```ToolStripMenuItem```.
- A ```Boolean``` to toggle the ```Icon``` visibility for all the items.

**Example**
![Image](https://i.imgur.com/WGUZqwO.jpg)

**Comment by dahall** [comment]
Added `GetMenuImageForFile` event that is called with the filename for each file so that an icon can be provided. I thought this method more flexible while providing a way to accomplish your request.

**Comment by DarkByte7** [comment]
Thank you for quickly implementing all the requested enhancements to allow further customization flexibility. 👍

Can't wait to start pimping up the the properties next update. Its a better use of the space than just having a white space and it blends in better with the rest of the user interface ```ToolStripMenuItems```. ✨

And awesome work on this project repository you have been doing! I have been utilizing it for >2 year's now its been very educational. ⭐️

#LongLiveVanara ☯️

**Comment by dahall** [comment]
Thank you. It is really nice to know that someone both uses and appreciates the work. Keep the enhancement requests and bug reports coming!

**Comment by DarkByte7** [comment]
@dahall Will do. And do you also have any alternative communication channels for your repository/s like a Discord or an email? In case I run into questions and might need assistance.

**Comment by dahall** [comment]
I monitor this forum regularly, so please post here.
