### ISSUE TITLE
MenuStrip MRU Manager - ClearAllListMenuItem Icon

### ISSUE THREAD

**Issue by DarkByte7** [dahall/Vanara#103]
**Is your feature request related to a problem? Please describe.**
There is no assignable preview ```Icon``` option for the ```ClearAllListMenuItem```.

**Describe the additions or enhancements you'd like**
Allow assigning an ```Icon``` image for the ```ClearAllListMenuItem```.

**Example**
![Image](https://i.imgur.com/VghWouW.jpg)

**Comment by dahall** [comment]
Added `ClearListMenuItemImage` property.
