### ISSUE TITLE
MenuStrip MRU Manager - ClearAllListMenuItem Alignment

### ISSUE THREAD

**Issue by DarkByte7** [dahall/Vanara#104]
**Is your feature request related to a problem? Please describe.**
There is no item ```Alignment``` option for the ```ClearAllListMenuItem```.

**Describe the additions or enhancements you'd like**
A ```Enum``` to toggle the ```Alignment``` of the ```ClearAllListMenuItem``` to (```Bottom``` or ```Top```).

**Example**
##### Bottom:
![Image-Bottom](https://i.imgur.com/jLC5V7Y.jpg)
##### Top:
![Image-Top](https://i.imgur.com/fYjgP72.jpg)

**Comment by dahall** [comment]
Added `ClearListMenuItemPlacement` property that will place at top or bottom.
