### ISSUE TITLE
Exception Unhandled 'System.Runtime.InteropServices.COMException' in GetPath(Shell32.ControlPanelItem)

### ISSUE THREAD

**Issue by DarkByte7** [dahall/Vanara#105]
**Describe the bug**
The `System.Runtime.InteropServices.COMException` is thrown when failing trying to get the path using `Vanara.Windows.Shell.GetPath(Shell32.ControlPanelItem)`.

***Message:***
```Error HRESULT E_FAIL has been returned from a call to a COM component.```

***Stack Trace:***
```CSharp
at Vanara.PInvoke.Shell32.IOpenControlPanel.GetPath(String pszName, StringBuilder pszPath, UInt32 cchPath)
at Vanara.Windows.Shell.ControlPanel.SafeCP.GetPath(String pszName)
at Vanara.Windows.Shell.ControlPanel.GetPath(ControlPanelItem item)
```

**What code is involved**
***Example:***
```CSharp
string path = Vanara.Windows.Shell.ControlPanel.GetPath(Shell32.ControlPanelItem.WindowsDefender);
```

**Expected behavior**
An empty `System.String` without the `System.Runtime.InteropServices.COMException` thrown.

**Comment by dahall** [comment]
Fixed in pushed code. Will deploy in next release.
