### ISSUE TITLE
DMPAPER.DMPAPER_USER is missing

### ISSUE THREAD

**Issue by VapidLinus** [dahall/Vanara#106]
The enum `DMPAPER` has no entry for `DMPAPER_USER` which would have a value of 256.

The Microsoft documentation mentions it here (search for "DMPAPER_USER"):
https://docs.microsoft.com/en-us/windows/win32/api/wingdi/ns-wingdi-devmodea

Therefore I am unable to set `devmode.dmPaperSize` to `DMPAPER_USER`.

This doesn't work because the enum doesn't contain this value:

```
DEVMODE devmode = default;
devmode.dmFields |= DMFIELDS.DM_PAPERSIZE | DMFIELDS.DM_PAPERLENGTH | DMFIELDS.DM_PAPERWIDTH;
devmode.dmPaperSize = (DMPAPER) 256;
devmode.dmPaperLength = 1000;
devmode.dmPaperWidth = 1000;
```

**Comment by dahall** [comment]
I've added it. Thanks.
