### ISSUE TITLE
Vanara.PInvoke.Printing is 2MB

### ISSUE THREAD

**Issue by VapidLinus** [dahall/Vanara#108]
I have been using `Vanara.PInvoke.Printing` in a project and am very happy to use it. However, the fact that just adding `Vanara.PInvoke.Printing` as a dependency adds an entire 2MB to the build size is unfortunately not acceptable for this project. So I have to either find a way to reduce this size or to abandon using this as a dependency. It seems like it gets big because it depends on so many other parts of the project.

**Size:**
https://i.imgur.com/l8kwo9p.png

Is there any way to reduce the file size? I wouldn't expect the printing library to depend on 2MB of other code.

Thanks in advance.

**Comment by dahall** [comment]
Yes, this library, like the system dlls, has lots of dependencies. If you're using .NET Core, there is a command that let's you combine all dependencies into one file. The advantage is that it will also remove unused code. See https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#assembly-linking.

**Comment by VapidLinus** [comment]
Thank you for your reply and help.

Unfortunately this project is on .NET Framework 4.7.1 and it will not be converted to .NET Core.

Is there anything similar that can be done *(removing unused code)* that would work on my project's version? It think finding a way to remove all unused code would reduce the size a lot as my project only uses a small subset of your library.

**Comment by dahall** [comment]
ILMerge is the only similar tool I'm aware of for .NET Framework.

**Comment by dahall** [comment]
I hope ILMerge helped. I don't think this is an issue I can resolve given the multitude of interdependencies across the Win32 libraries. May I close this issue?

**Comment by VapidLinus** [comment]
As far as I could see, ILMerge doesn't do anything to strip out unused code.

Our solution was to create our own internal copy of the library only copy the specific methods and classes that we use. It's unfortunate because we'll lose a lot of ease of development, flexibility, and easy updates.

I don't think there's anything you can do on the library itself though regarding this so it's alright to close the issue. Our project is only around 15MB and adding an extra 2MB is unfortunately a major barrier, but I don't expect this to be the case for the majority of users of this project.
