### ISSUE TITLE
Memory leak with SafePSECURITY_DESCRIPTOR

### ISSUE THREAD

**Issue by cocowalla** [dahall/Vanara#109]
I've ran across a memory leak when calling `GetNamedSecurityInfo`, which I've tracked down to the `SafePSECURITY_DESCRIPTOR` that it outputs.

I'm calling this on several files, like this:

```c#
var sections = SECURITY_INFORMATION.DACL_SECURITY_INFORMATION | 
    SECURITY_INFORMATION.OWNER_SECURITY_INFORMATION | 
    SECURITY_INFORMATION.GROUP_SECURITY_INFORMATION;

AdvApi32.SafePSECURITY_DESCRIPTOR ppSecurityDescriptor = null;
try
{
    var win32Error = GetNamedSecurityInfo(myPath,
        SE_OBJECT_TYPE.SE_FILE_OBJECT, sections, out PSID ppsidOwner, out PSID ppsidGroup,
        out PACL ppDacl, out PACL ppSacl, out ppSecurityDescriptor);
}
finally
{
    ppSecurityDescriptor?.Dispose();
}
```

As you can see, I dispose the `SafePSECURITY_DESCRIPTOR`. However, unmanaged memory used by the process hrows indefinitely as this method is called.

If I use `LocalFree` before disposing the `SafePSECURITY_DESCRIPTOR`, the memory leak is gone:

```c#
    Kernel32.LocalFree((IntPtr)ppSecurityDescriptor)
```

I think this could be resolved by having `SafePSECURITY_DESCRIPTOR` override `Dispose`, and having it call `ReleaseHandle` on the base `SafeMemoryHandle`.

**Comment by dahall** [comment]
Thanks for finding this. The problem was that I had set the default constructor for `SafePSECURITY_DESCRIPTOR` to not own the pointer and dispose of it properly. That is now corrected with the recent push. You should not need to call `LocalFree` now (or at least once 3.2.3 is released).

**Comment by cocowalla** [comment]
That was quick, thanks! 👍
