### ISSUE TITLE
There is no list of privilege constants

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#11]
https://docs.microsoft.com/en-us/windows/desktop/SecAuthZ/privilege-constants

**Comment by dahall** [comment]
Not sure why you sent me this link. These string constants are captured in the project within the `Vanara.Security.SystemPrivilegeTypeConverter` class that will convert `Vanara.Security.SystemPrivilege` values to their string equivalents.

**Comment by NN---** [comment]
Sorry, I was not aware of this class.
Tried to search "SE_DEBUG" in the code.

**Comment by NN---** [comment]
The issue was due to lack of Vanara.Security package.
Thanks.
