### ISSUE TITLE
[Performance] GetExtendedTcpTable<T>/GetExtendedTcpTable<T> Performance

### ISSUE THREAD

**Issue by GF-Huang** [dahall/Vanara#110]
I found that `GetExtendedTcpTable<T>/GetExtendedTcpTable<T>` call `Activator.CreateInstance` for creating table instances.

https://github.com/dahall/Vanara/blob/c68aca71ac1f9de82e70845c9df5bc048b158edc/PInvoke/IpHlpApi/IpHlpApi.cs#L3162-L3172

But when I read this [blog](https://vagifabilov.wordpress.com/2010/04/02/dont-use-activator-createinstance-or-constructorinfo-invoke-use-compiled-lambda-expressions/), I found that the performance of `Activator.CreateInstance` is very poor. Don't know if you have tested the performance of `Activator.CreateInstance`?

![image](https://user-images.githubusercontent.com/4510984/78044721-a3057d00-73a7-11ea-9056-93a96610e73f.png)

**Comment by dahall** [comment]
I haven't tested this, but are you calling this method enough that a few milliseconds matter?

**Comment by NN---** [comment]
I don’t see any harm to have a such optimization .
It can be global caching object and could save calling CreateInstance in other methods.
So in total it makes program a little bit faster.

**Comment by dahall** [comment]
If either of you (@GF-Huang or @NN--- ) are willing to submit a PR, I'll accept. Given the minor improvement at large, I'll put my energies into other parts of the library.

**Comment by dahall** [comment]
I'm going to close this issue and decline the suggestion. To do what is suggested in the blog, you have to use lambda function compilation, which isn't supported on all the platforms supported by this library.
