### ISSUE TITLE
Missing WinEvent constants (Winuser.h)

### ISSUE THREAD

**Issue by NickAcPT** [dahall/Vanara#111]
**Is your feature request related to a problem? Please describe.**
I found out that these constants are missing
https://docs.microsoft.com/en-us/windows/win32/winauto/event-constants

**Describe the additions or enhancements you'd like**
I would like to have some kind of class that had those constants that can be used along with methods on the User32 class (eg. SetWinEventHook)

**Comment by dahall** [comment]
Nice catch. I've added these to the EventConstants static class in User32.

**Comment by NickAcPT** [comment]
Thank you so much 👍
