### ISSUE TITLE
Add a bleeding-edge NuGet feed

### ISSUE THREAD

**Issue by NickAcPT** [dahall/Vanara#112]
**Is your feature request related to a problem? Please describe.**
Sometimes issues get fixed and the project version gets incremented but the new code isn't on NuGet yet.

**Describe the additions or enhancements you'd like**
My suggestion is to add a MyGet feed where we can get bleeding edge builds (for all commits or version bumps) for when you don't release the update on NuGet immediately.

**Previous work**
I've tried building and packing the project on a local nuget repo but I'm not able to pack the project with `dotnet pack`. (`The reference assemblies for .NETFramework,Version=v2.0 were not found.`)

**Comment by dahall** [comment]
Thanks for pushing me on this. I'd started it on AppVeyor, but kept having build issues. Those are now resolved and I have update the project ReadMe with information on the "bleeding-edge" NuGet feed and a status icon for the AppVeyor build. I'll also need to be much more rigorous about changing the version after each release so the new builds have new versions.

**Comment by dahall** [comment]
Thanks for submitting this again. I've started using this feed for a project where I'm duplicating the Windows Samples using my libs. It helps me to find holes and usability issues. Having this new "beta" repository allows me to test against updates without interrupting my work.
