### ISSUE TITLE
Missing object id constants (Winuser.h)

### ISSUE THREAD

**Issue by NickAcPT** [dahall/Vanara#113]
**Is your feature request related to a problem? Please describe.**
I found out that these constants are missing
https://docs.microsoft.com/en-us/windows/win32/winauto/object-identifiers

These are the constants for the Object Ids.

**Describe the additions or enhancements you'd like**
I would like to have some kind of class that had those constants that can be used along with methods on the User32 class (eg. SetWinEventHook)

One of the uses is on Hooks where we get a `int idObject` parameter with the id of the object.

Not sure if it can become an enum. If so, how would that affect `User32.WinEventProc`? What about other uses?

**Comment by dahall** [comment]
Taking a look, it appears this list can be extended, so I'd likely stay away from making it an enum. I can add it as a static class similar to the one I did for event constants. Does that work?

**Comment by dahall** [comment]
I've added as described above. Please reopen if this doesn't work.
