### ISSUE TITLE
TypeLoadException CRYPTUI_WIZ_DIGITAL_SIGN_INFO_UNION ('Vanara.PInvoke.Cryptography')

### ISSUE THREAD

**Issue by chasewallis** [dahall/Vanara#115]
**Describe the bug**
`System.TypeLoadException : Could not load type 'CRYPTUI_WIZ_DIGITAL_SIGN_INFO_UNION' from assembly 'Vanara.PInvoke.Cryptography, Version=3.2.3.0, Culture=neutral, PublicKeyToken=c37e4080322237fa' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.
`

Runtime exception when loading. I believe in WinCrypt.cs, there is a struct `CRYPTUI_WIZ_DIGITAL_SIGN_INFO` that contains a union `CRYPTUI_WIZ_DIGITAL_SIGN_INFO_UNION`. That `_UNION` is a struct with 2 fields, both at [FieldOffset(0)]. That appears to be how the win32 code is, but .net is not happy about it.

https://docs.microsoft.com/en-us/windows/win32/api/cryptuiapi/ns-cryptuiapi-cryptui_wiz_digital_sign_info

That struct linked to has 2 unions. In the Vanara code, the second union is just an IntPtr to the correct instance. Can that same approach be used for the first union?

**What code is involved**
`Vanara.PInvoke.Cryptography`
Creating the struct `CRYPTUI_WIZ_DIGITAL_SIGN_INFO` caused the error.

`var si = new CryptUI.CRYPTUI_WIZ_DIGITAL_SIGN_INFO();`

To be clear, I can't even debug into my code that calls that method, it fails when loading the library. 

**Expected behavior**
No TypeLoadException when creating a `CRYPTUI_WIZ_DIGITAL_SIGN_INFO`.

**Screenshots**
I think the stacktrace and description paints a pretty clear picture.

**Comment by dahall** [comment]
Pushing out in 3.2.5 release now
