### ISSUE TITLE
Include PROCESS_QUERY_LIMITED_INFORMATION and other process-related constants for use in OpenProcess

### ISSUE THREAD

**Issue by Enigmatrix** [dahall/Vanara#116]
`OpenProcess` uses `ACCESS_MASK` for the first parameter, which does not include `PROCESS_QUERY_LIMITED_INFORMATION` and `PROCESS_VM_READ`. In fact, these constants are not defined in the Vanara codebase.

It would be good if these process-related constants are defined in a separate enum for the use of `OpenProcess`, perhaps `PROCESS_ACCESS_MASK`?
 
Information for these constants are given [here](https://docs.microsoft.com/en-us/windows/win32/procthread/process-security-and-access-rights).

**Comment by dahall** [comment]
See [`Vanara.PInvoke.Win32.ProcessAccess`](https://github.com/dahall/Vanara/blob/c6b9c3e5b6ccf6bcc5b8898afcddfd7e8f0e6b30/PInvoke/Kernel32/ProcessThreadsApi.cs#L673-L807) enum. Cast to a `uint` to use in `OpenProcess`.

**Comment by Enigmatrix** [comment]
Thanks!
