### ISSUE TITLE
TypeLoadException for DSREG_JOIN_INFO

### ISSUE THREAD

**Issue by jformacek** [dahall/Vanara#117]
**Describe the bug**
Hello, I'm getting TypeLoadException when trying to use NetApi32 - see code below.
Compiling for .NET Framework 4.7.2 in VS2019; target platform is x64

Exception:
```
Could not load type 'DSREG_JOIN_INFO' from assembly 
'Vanara.PInvoke.NetApi32, Version=3.2.5.0, Culture=neutral, PublicKeyToken=c37e4080322237fa' 
because the format is invalid.
```

**What code is involved**
The code is pretty simple:
```csharp
        HRESULT hr = 0;
        NetApi32.DSREG_JOIN_INFO info;
        hr = Vanara.PInvoke.NetApi32.NetGetAadJoinInformation(null, out info);
```
BTW when I try to use completely different NetAPI32 API function from PowerShell4, after loading all required libs manually, I'm getting exactly the same error:
```powershell
[Vanara.PInvoke.NetApi32]::NetServerDiskEnum($null)
#throws "Could not load type 'DSREG_JOIN_INFO' 
#              from assembly 'Vanara.PInvoke.NetApi32, Version=3.2.5.0, Culture=neutral, PublicKeyToken=c37e4080322237fa' 
#              because the format is invalid."
```

**Expected behavior**
No TypeLoadException

**Comment by dahall** [comment]
Thanks for finding this. It's a symptom of being too lazy to finish the unit tests for this assembly. It is fixed now and will get released in 3.2.6.

**Comment by jformacek** [comment]
Thanks for quick fix!
Any estimate for vNext release?

Jiri

**Comment by dahall** [comment]
Sometime this coming week for sure.

**Comment by dahall** [comment]
Check the homepage readme for the project for information on how to download pre-release nuget packages from appveyor.
