### ISSUE TITLE
implicit convertion to IntPtr from SafeHandle

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#12]
I don't think this is a good idea to have such implicit conversion.
It may lead to hard finding bugs.
The better option is to use SafeHandle instead of IntPtr.

https://github.com/dahall/Vanara/blob/b9f2b152b894da5a17238dd90f30f2bdeb0a9f4c/Core/InteropServices/GenericSafeHandle.cs#L41

**Comment by dahall** [comment]
I hadn't considered that approach, but I like it. Let me look at what would break if I refactored everything that way.

**Comment by dahall** [comment]
Turned out it wasn't so hard. Thanks for the suggestion. Code has been updated to make that operator explicit and I've updated affected functions.

**Comment by NN---** [comment]
Why not removing cast as .NET framework does.
The name DangerousGetHandle is what people are used to and for a good reason this is named so.

**Comment by dahall** [comment]
Well, basically because I'm lazy and it would entail too many changes. Sorry.

**Comment by NN---** [comment]
If you remove implicit cast it is already a breaking change.
So better to remove the explicit too.
Perhaps you need to bump major version of the package.
