### ISSUE TITLE
DnsGetCacheDataTable API

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#121]
**Is your feature request related to a problem? Please describe.**
Add undocumented DnsGetCacheDataTable.

This API exists in all Windows versions but doesn't have good documentation.
Fortunately, there are many definitions in [GitHub](https://github.com/search?q=DnsGetCacheDataTable&type=Code)

Definition in [StreamReroute.cs](https://github.com/confirmedcode/Confirmed-Windows/blob/149c0d42763bd3b2799e9e8dd13e159089afef96/TrustWindowsWPF/TrustWindowsWPF/StreamReroute.cs)

More information:
https://docs.microsoft.com/en-us/windows/win32/apiindex/windows-8-api-sets

**Comment by dahall** [comment]
Code complete. This will go out in next version, but I'm adding a new library so it may take over a week.
