### ISSUE TITLE
Vanara.PInvoke.Shell32.FolderItem - MarshalDirectiveException

### ISSUE THREAD

**Issue by gave92** [dahall/Vanara#125]
**Describe the bug**
Hello I'm getting a System.Runtime.InteropServices.MarshalDirectiveException when trying to enumerate the contents on the recycle bin using the code below.
* OS: Windows 10

 **Stack trace**
> Exception: 'System.Runtime.InteropServices.MarshalDirectiveException' in FilesFullTrust.exe
   in System.StubHelpers.StubHelpers.ThrowInteropParamException(Int32 resID, Int32 paramIdx)
   in FilesFullTrust.Program.Main(String[] args) in C:\Users\Marco\source\repos\files-uwp\Files.Launcher\Program.cs:riga 51

**What code is involved**
```cs
[STAThread]
private static void Main(string[] args)
{ 
	// Create shell COM object and get recycle bin folder
	var shell = new Shell32.Shell();
	Type shellAppType = Type.GetTypeFromProgID("Shell.Application");
	var Recycler = (Shell32.Folder)shellAppType.InvokeMember("NameSpace",
	System.Reflection.BindingFlags.InvokeMethod, null, shell, new object[] { Shell32.ShellSpecialFolderConstants.ssfBITBUCKET });

	// Enumerate recyclebin contents and send response to UWP
	Shell32.FolderItems items = Recycler.Items();
	for (int i = 0; i < items.Count; i++)
	{
		Shell32.FolderItem FI = items.Item(i); -----> exception
	}
}
```

**Comment by dahall** [comment]
I'm not sure why you're approaching it this way and am guessing that calling `InvokeMember` may be part of the problem. Here's how I'd approach it if you want to use the COM interfaces:
```cs
// Get IShellFolder for Desktop
SHGetDesktopFolder(out var iDesktop).ThrowIfFailed();
using var pDesktop = ComReleaserFactory.Create(iDesktop);

// Get IShellFolder for Recycle Bin
SHGetKnownFolderIDList(KNOWNFOLDERID.FOLDERID_RecycleBinFolder.Guid(), KNOWN_FOLDER_FLAG.KF_FLAG_DEFAULT, default, out var pIDL).ThrowIfFailed();
using var pBin = ComReleaserFactory.Create(pDesktop.Item.BindToObject<IShellFolder>(pIDL));

// Enum all items in bin
foreach (var childPidl in pBin.Item.EnumObjects())
{
    using var pItem = ComReleaserFactory.Create(SHCreateItemFromIDList<IShellItem>(childPidl));
    // use pItem.Item to access methods of IShellItem
}
```
If you want a much easier approach, consider using the Vanara.Windows.Shell classes:
```cs
using var bin = new ShellFolder(KNOWNFOLDERID.FOLDERID_RecycleBinFolder);
foreach (ShellItem item in bin)
{
    // Use item to access IShellItem properties
}
```

**Comment by gave92** [comment]
Thanks a lot second solution works perfectly.
To answer your question: the code in the first post is what I was using when referencing the "Microsoft Shell Controls And Automation" COM instead of this library
