### ISSUE TITLE
SHQUERYRBINFO - Incorrect struct definition

### ISSUE THREAD

**Issue by gave92** [dahall/Vanara#127]
**Describe the bug**
The function `Vanara.PInvoke.Shell32.SHQueryRecycleBin` returns garbage data.

**Research**
The definition of the SHQUERYRBINFO is missing the correct alignment attribute.
With the following definition the call to `SHQueryRecycleBin` return correct results:
```cs
[StructLayout(LayoutKind.Sequential, Pack = 4)]  -----> added Pack attribute
struct SHQUERYRBINFO
{
    public uint cbSize;
    public long i64Size;
    public long i64NumItems;
}
```

PS: when are you planning to release a new version on nuget?

**Comment by dahall** [comment]
I have updated the structure per your research. Thank you. An interim build of the NuGet package will be available in about 10 minutes from AppVeyor. See the home page for info on that NuGet source. I'm likely about a week or more from publishing the next release to NuGet.org as I'm in the middle of a significant library addition and some major fixes to `Vanara.Windows.Shell`.
