### ISSUE TITLE
Can't find where Vanara.PInvoke.User32.EnumWindows is declared

### ISSUE THREAD

**Issue by VapidLinus** [dahall/Vanara#128]
The correlation report for user32.dll has an entry for Vanara.PInvoke.User32.EnumWindows:
https://github.com/dahall/Vanara/blob/master/PInvoke/User32/CorrelationReport.md

But the link for it takes me to an empty search page:
https://github.com/dahall/Vanara/search?l=C%23&q=EnumWindows

I am trying to find where User32.EnumWindows is defined in Vanara.

Any help or input is appreciated, cheers!

**Comment by dahall** [comment]
Not sure why the search engine isn't finding it. It is in [WinUser.Window.cs](https://github.com/dahall/Vanara/blob/master/PInvoke/User32/WinUser.Window.cs). Use the `Vanara.PInvoke.User32` NuGet package. In the future, just look for the `Vanara.PInvoke.[DllName]` package where _DllName_ is the name of the DLL containing the function you need.
