### ISSUE TITLE
Vanara.Windows.Shell - COMException, Enumerating Computer folder

### ISSUE THREAD

**Issue by gave92** [dahall/Vanara#130]
**Describe the bug**
1) I'm getting COMException enumerating the contents of the "Computer" shell folder.
2) I'm getting different results depending whether I'm using the `[STAThread]` attribute or not (if [STAThread] is missing some items (e.g a connected android phone) are missing. But the exception (1) is always there.

**What code is involved**
```cs
[STAThread] -----> (2) is this necessary?
static void Main(string[] args)
{
    using (var computer = new ShellFolder(Vanara.PInvoke.Shell32.KNOWNFOLDERID.FOLDERID_ComputerFolder))
    {
        foreach (var si in computer) { ----------> (1) exception
            Console.WriteLine(si.ParsingName);
            si.Dispose();
        }
    }
}
```

**Stacktrace**
>    in Vanara.PInvoke.Shell32.IShellItem2.GetString(PROPERTYKEY& key)
   in Vanara.Windows.Shell.ShellItem.Open(IShellItem iItem)
Class not registered.
Failed to find proxy registration for IID: {ADD8BA80-002B-11D0-8F0F-00C04FD7D062}.

**Comment by dahall** [comment]
Thanks for all these issues. You're giving `Vanara.Windows.Shell` a much better workout than I've been able to. I'm making some other related updates today so I'll look at this.

**Comment by gave92** [comment]
Thanks a lot for addressing them so quickly xD

**Comment by dahall** [comment]
Hm. I copied your failure code right into a test and cannot reproduce the error. I'm guessing it has something to do with something on your desktop that my code isn't handling. Any chance you can look at your desktop and see if there's anything there that isn't a well-known folder or a drive?

**Comment by dahall** [comment]
And I get the exact same results regardless of threading attribute. Sorry.

**Comment by gave92** [comment]
I feared as much, I could swear that the problem was not there yesterday.
- Could you try to connect an android phone as MTP device? That is where I'm noticing the difference 
with or without the threading attribute (phone not listed without [STAThread])
- I'm getting exception when the loop gets to enumerating my hard drives. The exception *does not* crash the app I'm just seeing it in the debug window
![tempsnip](https://user-images.githubusercontent.com/9673091/83955834-a14caf80-a857-11ea-837a-e571c925b125.png)

Thanks for looking into this.

**Comment by dahall** [comment]
The exception is a handled exception when calling IShellItem2.GetString(PK_ItemType) in `ShellItem.Open` which drives obviously don't support. You can safely ignore it.

I plugged in my Android phone and connected as an MTP device and see the exact same thing. It's not my code. Under MTA mode, IEnumShellItems never even pulls it up. I'm not sure why.

I even tried using `IShellFolder.EnumObjects` and it doesn't show it either under MTA. Interestingly enough, this method doesn't show the user folders (e.g. "Documents") either.
