### ISSUE TITLE
Shell32.Shell not implemented?

### ISSUE THREAD

**Issue by gave92** [dahall/Vanara#131]
**Describe the bug**
The [Shell NameSpace](https://docs.microsoft.com/en-us/windows/win32/shell/shell) method appears to be missing.
I expected the following code to work, but there is no `NameSpace` method in `Vanara.PInvoke.Shell32.Shell` class. Am I missing something?

**What code is involved**
```cs
var shell = new Vanara.PInvoke.Shell32.Shell();
Vanara.PInvoke.Shell32.Folder objFolder = shell.NameSpace(some_folder_path);
```

**Comment by dahall** [comment]
That is a coclass that then must be cast to the interface you want. The interface you're looking for is `IShellDispatch`. Code should be:
```cs
var shell = new Vanara.PInvoke.Shell32.IShellDispatch();
var objFolder = shell.NameSpace(ShellFolderViewOptions.XX);
```

**Comment by dahall** [comment]
However, in looking at this now, it appears the parameter for the NameSpace method is incorrect. I'll get that corrected.
