### ISSUE TITLE
If you use ShellFileOperations.Move to operate the recycle bin, it might get stuck until the program is closed

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#132]
**Describe the bug**
I want to use ShellFileOperations.Move to restore the files in the recycle bin, but a strange phenomenon often occurs: the operation of moving the file will be stuck until the program is closed. Once the program is closed, the original restore operation will continue

**What code is involved**
```csharp
        public static bool Move(string SourcePath, string DestinationPath)
        {
            try
            {
                using (ShellItem SourceItem = new ShellItem(SourcePath))
                using (ShellFolder DestItem = new ShellFolder(DestinationPath))
                {
                    ShellFileOperations.Move(SourceItem, DestItem, null, ShellFileOperations.OperationFlags.AllowUndo | ShellFileOperations.OperationFlags.NoConfirmMkDir | ShellFileOperations.OperationFlags.Silent);
                }

                return true;
            }
            catch
            {
                return false;
            }
        }
```

In addition to the method of moving files, is there any other method that can be used to restore files in the recycle bin?

**Screenshots**

**Comment by zhuxb711** [comment]
SHEmptyRecycleBin() will also cause stuck and unable to empty the recycle bin, it seems that some resources have not been properly released. Right-click the empty button of the recycle bin, it cannot be cleared, and the progress is stuck at 0%. Only the termination of the current program can be emptied normally

**Comment by dahall** [comment]
What parameters are you passing when calling `SHEmptyRecycleBin`?

**Comment by dahall** [comment]
Also, before I dive into this, have you tried adding the `NoConfirmation` option flag. Usually this is needed with `Silent` for `Move` operations.

**Comment by zhuxb711** [comment]
@dahall 
```csharp
public static bool EmptyRecycleBin()
        {
            return SHEmptyRecycleBin(IntPtr.Zero, null, SHERB.SHERB_NOSOUND | SHERB.SHERB_NOPROGRESSUI | SHERB.SHERB_NOCONFIRMATION) == HRESULT.S_OK;
        }
```

**Comment by dahall** [comment]
Just a note, but checking for S_OK on SHEmptyRecycleBin is only correct if there are items in the Recycle Bin. If it is empty, you will get E_UNEXPECTED. I'm still debugging trying to recreate your errors.

**Comment by zhuxb711** [comment]
@dahall 
It's strange, I won't get stuck here again, sometimes not.
Thanks for the tip!

**Comment by dahall** [comment]
I've run the following test and cannot reproduce what you're seeing:
```cs
// Delete item to Recycle Bin
using var tmp = new TempFile();
Assert.That(() => ShellFileOperations.Delete(new ShellItem(tmp.FullName)), Throws.Nothing);

// Find deleted item
using var bin = new ShellFolder(KNOWNFOLDERID.FOLDERID_RecycleBinFolder);
var item = bin.FirstOrDefault(si => si.Name == tmp.FullName);
Assert.NotNull(item);

// Restore item
Assert.That(() => ShellFileOperations.Move(item, new ShellFolder(Path.GetDirectoryName(tmp.FullName)), null, ShellFileOperations.OperationFlags.NoConfirmation), Throws.Nothing);
Assert.IsTrue(File.Exists(tmp.FullName));
```
If you see why this test would be different, please let me know.

**Comment by zhuxb711** [comment]
@dahall 
This problem seems to have disappeared, if I can find the exact way to reproduce the problem, I will notify you. I will close this issue first, thank you very much.

**Comment by zhuxb711** [comment]
@dahall 
The problem seems to be related to different files, please delete the following files to the recycle bin and try to restore it.

Here is code :
```csharp
        public static bool Move(string SourcePath, string DestinationPath, string NewName = null)
        {
            try
            {
                using (ShellItem SourceItem = new ShellItem(SourcePath))
                using (ShellFolder DestItem = new ShellFolder(DestinationPath))
                {
                    ShellFileOperations.Move(SourceItem, DestItem, NewName, ShellFileOperations.OperationFlags.AllowUndo | ShellFileOperations.OperationFlags.NoConfirmMkDir | ShellFileOperations.OperationFlags.Silent);
                }

                return true;
            }
            catch
            {
                return false;
            }
        }
```

Here is test file:
https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.10.1/Clash.for.Windows.Setup.0.10.1.exe

#### Now you will find it stuck at "ShellFileOperations.Move()".

**Comment by dahall** [comment]
I have run your exact code with the file you provided under a .NET Core 3.1 and .NET Framework 4.7.2 build without any problems. Sorry. Could it be your anti-virus software that locks the file?

**Comment by zhuxb711** [comment]
@dahall 
My environment is Win10 2004 version, .Net Framework 4.7.2, console program.

I can move this file to the recycle bin, but I have no way to move it back from the recycle bin to its original location. It just stuck.

I have tested it on different computers and the same situation will occur.

It stands to reason that anti-virus software will not lock files in the recycle bin, right? The antivirus software I use is Microsoft Defender.

If the above situation occurs, execute SHEmptyRecycleBin function will also get stuck...

So Weird.

**Comment by dahall** [comment]
When you call the `Move` method, what parameters are you using?

**Comment by zhuxb711** [comment]
ShellFileOperations.OperationFlags.AllowUndo | ShellFileOperations.OperationFlags.NoConfirmMkDir | ShellFileOperations.OperationFlags.Silent

**Comment by dahall** [comment]
Right. You have that in the code. I'm wondering about the file paths.

**Comment by zhuxb711** [comment]
SourcePath is the FileSystemPath of the file I want to restore. DestinationPath is the parent folder of the original path of that file. 

For example:
Clash.exe is now in C:\$Recycle.Bin\XXXXXXXX
And it's origin path is C:\Users\XXX\Downloads\Clash.exe

So 
SourcePath=C:\$Recycle.Bin\XXXXXXXX
DestinationPath=C:\Users\XXX\Downloads

**Comment by dahall** [comment]
Here's the exact code I'm running.
```cs
class Program
{
   [STAThread]
   static void Main(string[] args)
   {
      const string bitBucket = @"C:\$Recycle.Bin";
      var fi = new FileInfo(@"C:\Users\XXX\Downloads\Clash.for.Windows.Setup.0.10.1.exe");
      Move(fi.FullName, bitBucket);
      Thread.Sleep(500);
      Move(Path.Combine(bitBucket, fi.Name), fi.DirectoryName);
   }

   public static bool Move(string SourcePath, string DestinationPath, string NewName = null)
   {
      try
      {
         using (ShellItem SourceItem = new ShellItem(SourcePath))
         using (ShellFolder DestItem = new ShellFolder(DestinationPath))
         {
            ShellFileOperations.Move(SourceItem, DestItem, NewName, ShellFileOperations.OperationFlags.AllowUndo | ShellFileOperations.OperationFlags.NoConfirmMkDir | ShellFileOperations.OperationFlags.Silent);
         }

         return true;
      }
      catch
      {
         return false;
      }
   }
}
```
If I run this in user mode, I am prompted for UAC permissions on both `Move` calls. If I run as Admin, it just runs without error or prompts. Could the prompts or UAC be causing your problem?

**Comment by zhuxb711** [comment]
My code is a little different from yours.

My code has no `[STAThread]` tag

And not so simple
```csharp
const string bitBucket = @"C:\\$Recycle.Bin";
```
### Step1:
```csharp
using (ShellFolder RecycleBin = new ShellFolder(Shell32.KNOWNFOLDERID.FOLDERID_RecycleBinFolder))
            {
                foreach (ShellItem Item in RecycleBin)
                {
                  //Get SourcePath from "Item.FileSystemPath"
                  //Example: C:\\$Recycle.Bin\\S-1-5-21-1386655269-1975286617-285474710-1001\\$RNHVUP2.txt
                  //Get DestinationPath from "Item.Name" which is OriginPath
                  //Example: C:\\Users\\XXXX\\Downloads\\test.txt
                }
            }
```
### Step2:
```csharp
// Example: 
// SourcePath="C:\\$Recycle.Bin\\S-1-5-21-1386655269-1975286617-285474710-1001\\$RNHVUP2.txt"
// DestinationPath="C:\\Users\\XXXX\\Downloads\\test.txt"
// Path.GetDirectoryName(DestinationPath): "C:\\Users\\XXXX\\Downloads"
Move(SourcePath,Path.GetDirectoryName(DestinationPath));
```

#### In the above code, no administrator rights are required and UAC will not be triggered
#### The strange thing about this problem is that only certain files cannot be restored from the recycle bin, and folders or other files can be operated normally. And if there is a file that causes the "Restore (Which is 'Move')" operation to be stuck, it will also cause the call to SHEmptyRecycleBin function to be stuck

**Comment by zhuxb711** [comment]
@dahall 
Can you reproduce this problem? Do you have any idea about this ?

**Comment by dahall** [comment]
I have not been able to reproduce the problem. Using similar code, I have deleted a very large folder with subfolders and very diverse files and been able to restore it without any hanging. I'm creating a `RecycleBin` static class in `Vanara.Windows.Shell` and will post the code shortly.

**Comment by zhuxb711** [comment]
Looking forward to your "RecycleBin" class😊

**Comment by dahall** [comment]
I just pushed it. The NuGet packages should be available shortly on AppVeyor. I've tried with a 1.5GB directory with hundreds of files of different types and sizes. I've done it with the UI visible and hidden without hangs. Please give it a try and let me know if still experience your hangs. Thanks.

**Comment by zhuxb711** [comment]
I don't see a newer version in Nuget, how can I test it?

**Comment by dahall** [comment]
See the home page readme for a link to the NuGet repo via AppVeyor.

**Comment by zhuxb711** [comment]
Sorry , but I don't know how to get the beta version through "AppVeyor".

**Comment by dahall** [comment]
To use this package, add our private feed to your NuGet sources in Visual Studio. Go to `Tools > NuGet Package Manager > Package Manager Settings` and add the source https://ci.appveyor.com/nuget/vanara-prerelease. When you select that source in NuGet Package Manager, you should see the latest version of the Vanara packages.

**Comment by zhuxb711** [comment]
I got this when restore item in recycle bin:
"Unable to restore a ShellItem that is not in the Recycle Bin"

![image](https://user-images.githubusercontent.com/42038175/85361647-181fc300-b54f-11ea-9339-038822d12c50.png)

This file does exist, whether it is viewed from the Explorer or from the recycle bin, it exists.


In addition, when I try to empty the recycle bin with a new method, it will still get stuck. The files in the recycle bin are as follows:
![image](https://user-images.githubusercontent.com/42038175/85361777-68972080-b54f-11ea-8e6c-b1b98daf72e2.png)

**Comment by zhuxb711** [comment]
I found a new situation, the root cause of the stuck problem should be to delete the file using ShellFileOperations.Delete. Because after I use ShellFileOperations.Delete, even if I don’t do anything to the recycle bin, I will get stuck when emptying the recycle bin in the system explorer. I guess it should be because ShellFileOperations.Delete deletes the file to the recycle bin, which in turn causes other operations to be stuck.

But I checked your source code and found no problems.

This problem is very strange, and it seems that this problem only occurs for specific files. According to your previous description, these problems have not been found on your Windows 10.

**Comment by zhuxb711** [comment]
Here is my project , maybe you could found something in "Recycle Bin" function.

https://github.com/zhuxb711/RX-Explorer

**Comment by zhuxb711** [comment]
When calling the Restore function, an exception is thrown here
```csharp
if (item.Parent != ShellFolderInstance) throw new InvalidOperationException("Unable to restore a ShellItem that is not in the Recycle Bin.");
```

Here is how I use it (throw exception "Unable to restore a ShellItem that is not in the Recycle Bin."):
```csharp
        public static bool Restore(string Path)
        {
            try
            {
                using (ShellItem Item = new ShellItem(Path))
                {
                    RecycleBin.Restore(Item);
                }
                return true;
            }
            catch
            {
                return false;
            }
        }

```

Based on your logic, I wrote the following code:
```csharp
            using(var bin = new ShellFolder(Vanara.PInvoke.Shell32.KNOWNFOLDERID.FOLDERID_RecycleBinFolder))
            {
                foreach(var item in bin)
                {
                    if(item.Parent==bin)
                    {
                          //It run to here
                    }
                    else
                    {

                    }
                }
            }
```
According to the above code, it is indeed found that item.Parent==bin.
It seems that it is false in your code. Weird.

**Comment by zhuxb711** [comment]
@dahall 
I found another similar project, it also uses SHEmptyRecycleBin function, but it won't get stuck, and mine will get stuck.

Here is what I found, it use SHEmptyRecycleBin in Files.Launcher project: https://github.com/files-community/files-uwp/blob/master/Files.Launcher/Program.cs

Here is my project, I use it in FullTrustProcess project: https://github.com/zhuxb711/RX-Explorer/blob/master/FullTrustProcess/Program.cs

I will appreciate if you can help me investigate why my project calls SHEmptyRecycleBin function will be stuck, but the Files.Launcher project will not.

**Comment by dahall** [comment]
First thing I notice is that Files.Launcher is using my declaration of the SHxxRecycleBin methods while you are declaring your own in `RecycleBinController.cs`. Please make sure they're consistent. The other thing I'd check is making sure you've released all COM objects or disposed any COM object wrappers (like ShellItem) so that the reference isn't trying to hang around when you want to delete it.

**Comment by zhuxb711** [comment]
Sorry, I forgot to delete the SHEmptyRecycleBin I implemented in the previous submission. But this does not affect the conclusion, because I did use your implementation in the test. Simply replace it.

**Comment by zhuxb711** [comment]
@dahall 
`First thing I notice is that Files.Launcher is using my declaration of the SHxxRecycleBin methods while you are declaring your own in RecycleBinController.cs.`

In fact, although I declared my own SHEmptyRecycleBin before, but the actual implementation is yours.

![image](https://user-images.githubusercontent.com/42038175/85813711-899d8280-b796-11ea-823b-7b6a019cbca6.png)

**Comment by zhuxb711** [comment]
#### I checked your source code and found that the ShellItem obtained by traversing the folder requires manual destruction of resources. After adding Dispose, all problems were solved.
```csharp
        public static string GenerateRecycleItemsByJson()
        {
            try
            {
                List<Dictionary<string, string>> RecycleItemList = new List<Dictionary<string, string>>();

                using (ShellFolder RecycleBin = new ShellFolder(Shell32.KNOWNFOLDERID.FOLDERID_RecycleBinFolder))
                {
                    foreach (ShellItem Item in RecycleBin)
                    {
                        try
                        {
                            if (!Path.GetExtension(Item.FileSystemPath).Equals(".lnk", StringComparison.OrdinalIgnoreCase))
                            {
                                Dictionary<string, string> PropertyDic = new Dictionary<string, string>
                                {
                                    { "OriginPath", Item.Name },
                                    { "ActualPath", Item.FileSystemPath },
                                    { "CreateTime", Convert.ToString(((System.Runtime.InteropServices.ComTypes.FILETIME)Item.Properties[Ole32.PROPERTYKEY.System.DateCreated]).ToDateTime().ToBinary())}
                                };

                                RecycleItemList.Add(PropertyDic);
                            }
                        }
                        finally
                        {
                            Item.Dispose();
                        }
                    }
                }

                return JsonConvert.SerializeObject(RecycleItemList);
            }
            catch
            {
                return string.Empty;
            }
        }

```

**Comment by dahall** [comment]
I'm so glad you found your problem! Just a couple of thoughts: You could use a `using` statement on `Item` rather than `try/finally`. Also, rather than checking for the `.lnk` extension, does the `IsLink` property give the right value or checking to see if `ShellItem` is actually `ShellLink`?

**Comment by zhuxb711** [comment]
@dahall 
Thanks for tip. Now I use IsLink to check ".lnk".
Thanks for the help.
