### ISSUE TITLE
IEnumExplorerCommand.Next array marshaling SizeParameterIndex incorrect?

### ISSUE THREAD

**Issue by wangfu91** [dahall/Vanara#143]
https://github.com/dahall/Vanara/blob/c88bf0acfd4e0b209b5ed6d2d688fd22a1aad37a/PInvoke/Shell32/ShObjIdl.IExplorerCommand.cs#L115

Here, should the ```celt``` be used as the size parameter, instead of ```pceltFetched```?
That is should the ```SizeParamIndex``` be set to 0, instead of 2?

The documentation says :
>```celt```
Specifies the number of elements to fetch.
```pceltFetched```
When this method returns, contains a pointer to the number of elements actually retrieved. 

When this method gets called,  the out parameter ```pceltFetched``` will always be the default value zero,
so, seems ```pUICommand``` should be initialized as an array of size ```celt```, instead of ```pceltFetched```?
otherwise, the initial value of ```pUICommand``` will always be an empty array and can't be populated later.

Also see: https://github.com/wjk/MSIExtractApp/blob/ba59307319a97c8a1d0a49bdaaa5be54fbf479af/src/MSIExtract.ShellExtension/Interop/IEnumExplorerCommand.cs#L18

**Comment by dahall** [comment]
`SizeParamIndex` is ignored on input. The length of the array is used. On output, it uses `SizeParamIndex` as a hint to determine the array length. For this method and most other IEnumXX interfaces, their documentation says to pass `celt` as the number being requested and then a pre-initialized array as the second parameter. I have found, like in this, that the implementation does not always set `pceltFetched`, especially when they only accept 1 as the value of `celt`.

**Comment by wangfu91** [comment]
Thanks, I understand that on output CLR uses the third parameter to tell the native side the size of the managed array,
but on input, if ```SizeParamIndex``` is ignored, what's the value of ```pUICommand``` then? how CLR able to know what size of the managed array to pre-initialize for?

**Comment by dahall** [comment]
Maybe an example will help:
```cs
var cmds = new IExplorerCommand[5];
if (iEnum.Next((uint)cmds.Length, cmds, out var cnt).Succeeded)
{
   for (uint i = 0; i < cnt; i++)
   {
      // Process from cmds[i]
   }
}
```

**Comment by wangfu91** [comment]
Ah, "pre-initialized", I see what you mean now 😅 , thanks for the example.
I'm using ```IEnumExplorerCommand``` to implement a cascading context menu, so the ```Next``` method is actually called by the explorer, so I'm not able to pre-initialize the array beforehand, in my case I found that setting ```SizeParamIndex``` to 0 works.
```c#
        public int Next(uint celt,
            [MarshalAs(UnmanagedType.LPArray, ArraySubType = UnmanagedType.Interface, SizeParamIndex = 0), Out]
            IExplorerCommand[] pUICommand,
            out uint pceltFetched)
        {
            pceltFetched = 0;

            if (_currentIndex < _commands.Length)
            {
                uint localIndex = 0;
                while (localIndex < celt && _currentIndex < _commands.Length)
                {
                    pUICommand[localIndex] = _commands[_currentIndex];
                    localIndex++;
                    _currentIndex++;
                }

                pceltFetched = localIndex;

                if (localIndex == celt)
                {
                    return HResults.S_OK;
                }
            }

            return HResults.S_FALSE;
        }
```

**Comment by dahall** [comment]
So you're implementing the interface? I'm curious then what the impact is of leaving `SizeParamIndex = 2`?

**Comment by dahall** [comment]
Also, from how these seem to be generally implemented, the `celt` value is the contract of how many elements have had memory allocated and passed in `pUICommand`. The `pceltFetched` is the implementer's mechanism to communicate back to the client how many elements were set.

**Comment by wangfu91** [comment]
>So you're implementing the interface? 

Yes.
>I'm curious then what the impact is of leaving SizeParamIndex = 2?

If leaving ```SizeParamIndex = 2```, 
on input, when ```IEnumExplorerCommand.Next()``` get called, the ```pUICommand``` will be initialized to an array of length ```pceltFetched``` (which is an out parameter, so always zero), 
then on output, explorer.exe crashes with **Access violation** even when I set ```pceltFetched``` to zero:
```c#
        public int Next(uint celt, IExplorerCommand[] pUICommand, out uint pceltFetched)
        {
            pceltFetched = 0;
            return HResults.S_OK;
        }
```
```
(5e94.31b0): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
SHELL32!CFolderMenu::_AllocFolderMenuItemData+0x5a:
00007ffd`55e4bb82 488b0f          mov     rcx,qword ptr [rdi] ds:00000000`00000000=????????????????
0:070> k
 # Child-SP          RetAddr               Call Site
00 00000000`055cca40 00007ffd`55e4c73d     SHELL32!CFolderMenu::_AllocFolderMenuItemData+0x5a
01 00000000`055ccad0 00007ffd`55e4c2cc     SHELL32!CFolderMenu::_InsertCommandToMenu+0x95
02 00000000`055ccc00 00007ffd`55e4b62d     SHELL32!CFolderMenu::_ComposeMenuFromEnumCommand+0x1f8
03 00000000`055ccd10 00007ffd`55d812a2     SHELL32!CFolderMenu::QueryContextMenu+0xfd
04 00000000`055ccdc0 00007ffd`55d81b90     SHELL32!CRegistryVerbsContextMenu::_EnsureSubMenuHandler+0x19a
05 00000000`055cce40 00007ffd`55d80aef     SHELL32!CRegistryVerbsContextMenu::_InitMenuPopup+0x5c
06 00000000`055cce70 00007ffd`55cb43ea     SHELL32!CRegistryVerbsContextMenu::HandleMenuMsg2+0x1f
07 00000000`055ccea0 00007ffd`5638cac8     SHELL32!CDefFolderMenu::HandleMenuMsg2+0x13a
```

**Comment by dahall** [comment]
Thank you. That helps my understanding immensely. I think I need to expand my testing to including implementations and then adjust all the `SizeParamIndex` values accordingly.

**Comment by dahall** [comment]
I have updated all interfaces with similar patterns to using the input size parameter for SizeParamIndex.
