### ISSUE TITLE
Possible incorrect definition of struct CMINVOKECOMMANDINFOEX

### ISSUE THREAD

**Issue by gave92** [dahall/Vanara#144]
**Describe the bug**
Definition of field `lpVerb` in CMINVOKECOMMANDINFOEX  might be incorrect.
Docs state that the field can accept either a string (Verb) or an int (ID of menu item) as the result of the `MAKEINTRESOURCE` macro.
How can I assign the result of MAKEINTRESOURCE to lpVerb (doing MAKEINTRESOURCE(some_int).ToString() won't work)? 

**Example code**
```cs
var pici = new CMINVOKECOMMANDINFOEX();
pici.lpVerb = Macros.MAKEINTRESOURCE(some_int); --> I can't do this as lpVerb must be a string
```

Thanks for the help

**Comment by dahall** [comment]
I think you're right. I believe the right field type should be `ResourceId` and then to use it, per your code, would be:
```cs
var pici = new CMINVOKECOMMANDINFOEX();
pici.lpVerb = new ResourceId(some_int);
// OR
pici.lpVerb = new SafeResourceId("some_string", CharSet.Ansi);
```
I'll make the change and do some testing.
