### ISSUE TITLE
Add Cancellation to ShellFileOperations

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#149]
Is it possible to add a function to cancel the operation in ShellFileOperations?

if OperationFlags.Silent is set, there is no way for user to cancel.

**Comment by dahall** [comment]
Throwing a COMException within an event should cancel the operation.

**Comment by dahall** [comment]
Please let me know if this solution works. If so, please close the issue. In

**Comment by zhuxb711** [comment]
It works, thanks a lot
