### ISSUE TITLE
StringBuilder is not required in CreateProcess*

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#15]
.NET always copies strings when passed via P/Invoke: https://docs.microsoft.com/en-us/dotnet/framework/interop/marshaling-strings

Therefore all input string arguments can be safely passed as string and not as StringBuffer.

**Comment by dahall** [comment]
It will really help if you provide more context so I don't have to assume your intent. Here, I assume you're talking about the lpCommandLine parameter. If so, then it does need to be a StringBuilder per its documented use:
"The Unicode version of this function, <c>CreateProcessW</c>, can modify the contents of this string. Therefore, this parameter cannot be a pointer to read-only memory (such as a <c>const</c> variable or a literal string). If this parameter is a constant string, the function may cause an access violation."

**Comment by NN---** [comment]
Sorry, forgot to put the link.
Yes I am talking about CreateProcess.
It is okay to pass string, since .NET marshaller always copies the string, so it is can be freely modified without touching the original one.

**Comment by dahall** [comment]
Correct, but then that copied string is not available to the developer. Using StringBuilder allows the developer to see the changes made by the function.

**Comment by NN---** [comment]
CreateProcess doesn't make any visible effect to caller.
It just changes string internally and then restores it to original.

**Comment by NN---** [comment]
https://blogs.msdn.microsoft.com/oldnewthing/20090601-00/?p=18083
```The CreateProcess temporarily modifies the string you pass as the lpCommandLine in its attempt to figure out where the program name ends and the command line arguments begin.```
