### ISSUE TITLE
ShellFileOperations.PreMoveItem and ShellFileOperations.PreDeleteItem behave differently from ShellFileOperations.PreCopyItem

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#150]
**Describe the bug**
After ShellFileOperations.PreCopyItem completes the operation, ShellFileOpEventArgs.Result is S_OK

After ShellFileOperations.PreMoveItem completes the operation, ShellFileOpEventArgs.Result is COPYENGINE_S_DONT_PROCESS_CHILDREN

After ShellFileOperations.PreDeleteItem completes the operation, ShellFileOpEventArgs.Result is COPYENGINE_S_DONT_PROCESS_CHILDREN

**Expected behavior**
After ShellFileOperations.PreMoveItem completes the operation, ShellFileOpEventArgs.Result should be S_OK

**Comment by dahall** [comment]
These values come directly from the OS. The library just passes them on.

**Comment by zhuxb711** [comment]
Different return values are very confusing, but this is not a problem with your library.
