### ISSUE TITLE
ConvertSecurityDescriptorToStringSecurityDescriptor returns an empty string

### ISSUE THREAD

**Issue by ryannewington** [dahall/Vanara#152]
**Describe the bug**

When calling `ConvertSecurityDescriptorToStringSecurityDescriptor` with a valid security descriptor, the function returns an empty string

```c#
string sddlVanara = AdvApi32.ConvertSecurityDescriptorToStringSecurityDescriptor(securityDescriptor, requestInformation);
```
When calling my own dllimport of this function (using an `out string` parameter rather than `SafeLocalHandle`), against the same security descriptor, I get the correct value returned.

**What code is involved**
`SafeLocalHandle`
`AdvApi32.ConvertSecurityDescriptorToStringSecurityDescriptor`

**Expected behavior**
A string should be resolved to SDDL form

**Screenshots**
Here is a debugger breakpoint showing the values of `sddlNative` and `sddlVanara` taken from the same pSecurityDescriptor object

![image](https://user-images.githubusercontent.com/17229877/87887226-9431fb80-ca66-11ea-93d4-1e5831ba9b73.png)

**Comment by dahall** [comment]
I'm looking into this. The problem with using `out string` is that it can create a memory leak. .NET marshaling releases memory with CoTaskMemFree and, in this case, the function allocates the memory with LocalAlloc and should be paired with LocalFree. I'm debugging the wrapper method now to determine why the wrong value is returned.

**Comment by dahall** [comment]
Thanks. This uncovered a bug that has a much larger scope. I have it fixed now and it will go out in the next release sometime this week.
