### ISSUE TITLE
Possible issue: Systemtime vs. Filetime

### ISSUE THREAD

**Issue by LordMike** [dahall/Vanara#154]
I was referring to your library to verify our own implementation of the `GetExtendedTcpTable` function, and noticed a potential bug here. Microsoft says the `liCreateTimestamp` member is a `SYSTEMTIME`. And as I read it, `SYSTEMTIME` is time since system boot, while `FILETIME` is absolute time (irrespective of boot etc.). 

I think this member should be a `SYSTEMTIME`, as to not lead any users to think it's a `FILETIME`. 

https://github.com/dahall/Vanara/blob/c68aca71ac1f9de82e70845c9df5bc048b158edc/PInvoke/IpHlpApi/TcpMib.cs#L1145

See: https://docs.microsoft.com/en-us/windows/win32/api/tcpmib/ns-tcpmib-mib_tcprow_owner_module

**Comment by LordMike** [comment]
Same goes for the UDP variant: https://github.com/dahall/Vanara/blob/c68aca71ac1f9de82e70845c9df5bc048b158edc/PInvoke/IpHlpApi/UdbMib.cs#L154

Also. Shouldn't that file be named `UdpMib` ?

**Comment by dahall** [comment]
Appreciate all those finds. I have updated them all and I found two others of that same error in those files.

**Comment by dahall** [comment]
This is now officially published to NuGet

**Comment by LordMike** [comment]
@dahall I'm verifying this again .. and actually running the code I have, I don't think this is a SYSTEMTIME.. but actually a FILETIME (like it started as).. Locally, I'm getting nonsense with the SYSTEMTIME struct (16 bytes) - and it seems to skew the offsets to the other structs in the table.

But with a FILETIME (8 bytes), the offsets match (ie. the addresses and ports of subsequent structs make sense again), and the timestamps make sense too (they're today f.ex.).

Is there something I'm missing in Microsofts docs?...

**Comment by dahall** [comment]
@LordMike I'm just curious, are you building as x86, x64 or AnyCPU? It will help me know which size to look at in the native C code.

**Comment by dahall** [comment]
I have verified that the native structure field is a 64-bit `LARGE_INTEGER` which corresponds to the `SYSTEMTIME` structure. I'm now verifying that the native structure layout and size match those of this library. More to come!

**Comment by LordMike** [comment]
Ooh.. I read WORD's as two-bytes.. Right, so it's 8 bytes still. They're one byte, right? Then your struct is incorrect, right?

* MS Docs on SYSTEMTIME: https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-systemtime
* Current Vanara impl, with ushorts: https://github.com/dahall/Vanara/blob/master/PInvoke/Shared/WinBase/SYSTEMTIME.cs#L16-L130

Now for why `DateTime.FromFileTime()` works with this data.. ?

**Comment by dahall** [comment]
No. You're right. `SYSTEMTIME` is a 16-byte/128-bit structure. Something's off. I have confirmed that the native structure uses a 64-bit value. I'm doing testing now.

**Comment by dahall** [comment]
Well, the changes you asked me to make (from FILETIME to SYSTEMTIME) did, in fact, break the structure layout. I'm testing now to determine how MS reads that value to get to a time. More to come shortly.

**Comment by dahall** [comment]
So, in other C/C++ examples, the `liCreateTimeStamp` field is processed using `FILETIME` rather than `SYSTEMTIME`. I'm going to change them back and curse your name forever for leading me astray (just kidding). I actually appreciate that you're using the library to find these kinds of things. Was it broken before your original issue or did you just notice the discrepancies between my structure and the docs?

**Comment by dahall** [comment]
The updates are pushed and available via AppVeyor's NuGet feed (see homepage). Please give them a try and let me know if you are seeing the right info.

**Comment by LordMike** [comment]
I worked purely from the docs. I don't recall actually trying the code out - I didn't even try our own code out.. I left that for another guy - but as he didn't touch the issue internally (due to other projects).. I circled back and then actually tried the code to fix our issue, noticing that the first bit actually worked :P

The funny part is that I actually only looked at this code, as we were getting `0001-01-01`'s in our system. Turned out our guy forgot to assign the value from `liCreateTimeStamp` to our own DTO's ... :D

You might wanna put in a remark saying "Don't.. we know .." :D

**Comment by LordMike** [comment]
I've run this, with `3.2.20` (published last night), and it provides proper dates.

```csharp
var n1 = IpHlpApi.GetExtendedTcpTable<IpHlpApi.MIB_TCPTABLE_OWNER_MODULE>(IpHlpApi.TCP_TABLE_CLASS.TCP_TABLE_OWNER_MODULE_ALL);

foreach (var row in n1)
{
    Console.WriteLine(row.liCreateTimestamp.ToDateTime());
}
```

So it probably works.. :D

Do put in the remark so I don't see it again :D

**Comment by dahall** [comment]
I have updated the comments for those fields and have submitted a PR to Microsoft to change their documentation as well.
