### ISSUE TITLE
Add overload to GetMonitorInfo to accept MONITORINFOEX handle

### ISSUE THREAD

**Issue by weitzhandler** [dahall/Vanara#155]
**Is your feature request related to a problem? Please describe.**
Hi,

According the the `GetMonitorInfo` [docs](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmonitorinfoa), you can a pointer to either `MONITORINFO` or `MONITORINFOEX`, however, seems that in C# this can only be achieved if using another overload of this mehtod.

**Describe the additions or enhancements you'd like**
Please add another overload of `GetMonitorInfo` with its 2nd parameter as a `MONITORINFOEX`.

**Comment by dahall** [comment]
Good call. Update is checked in and will release next cycle.

**Comment by weitzhandler** [comment]
Wow that was quick!
Thank you!

**Comment by dahall** [comment]
This is now officially published to NuGet
