### ISSUE TITLE
ShellFileOperations throws an exception during the process of moving lnk files

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#156]
**Describe the bug**
If you listen to the PostMoveItem event, a FileNotFound exception will be thrown. 
If remove "Operation.PostMoveItem += Operation_PostMoveItem;" it will work well.

**What code is involved**
### Example code:
```csharp
    class Program
    {
        static void Main(string[] args)
        {
            using (ShellFileOperations Operation = new ShellFileOperations
            {
                Options = ShellFileOperations.OperationFlags.AddUndoRecord | ShellFileOperations.OperationFlags.NoConfirmMkDir | ShellFileOperations.OperationFlags.Silent
            })
            {
                Operation.PostMoveItem += Operation_PostMoveItem;

                using (ShellItem SourceItem = new ShellItem("Enter lnk file path"))
                using (ShellFolder DestItem = new ShellFolder("Enter directory name"))
                {
                    Operation.QueueMoveOperation(SourceItem, DestItem);
                }

                Operation.PerformOperations();

                Operation.PostMoveItem -= Operation_PostMoveItem;
            }
        }

        private static void Operation_PostMoveItem(object sender, ShellFileOperations.ShellFileOpEventArgs e)
        {
            
        }
    }
```

**Expected behavior**

**Screenshots**

**Comment by zhuxb711** [comment]
"QueueDeleteOperation" has same problem.

**Comment by zhuxb711** [comment]
I found this:
![image](https://user-images.githubusercontent.com/42038175/90305105-79319a80-def1-11ea-8078-2144afe33530.png)
![image](https://user-images.githubusercontent.com/42038175/90305254-3ec8fd00-def3-11ea-923e-6baf47c65d36.png)

#### This problem seems to be caused by the constructor of ShellFileOpEventArgs called by the PostMoveItem event.

#### The PostMoveItem event will be raised multiple times during the moving process. The last time it was raised, because the corresponding file has been moved, it raised an exception when it tried to call ShellItem.Open

**Comment by zhuxb711** [comment]
@dahall 

The root cause of this problem is that when ShellFileOperations moves the file, it is assumed that the original file still exists.

According to observations, when moving other types of files, the original file will disappear after the PostMoveItem event, so there is no problem with this design, but for the lnk file, it is no longer in the original position before the PostMoveItem event.

![image](https://user-images.githubusercontent.com/42038175/90312572-2202e880-df38-11ea-833a-dacb5567d797.png)
According to the MSDN documentation, "psiItem is a pointer to an IShellItem that specifies the source item", but it does not guarantee that the IShellItem still exists in the original location, so in this case calling ShellItem.Open again will most likely cause a FileNotFoundException. In summary, it should not be assumed that SoursItem still exists

**Comment by dahall** [comment]
Thanks. I've added code to catch the exception and just return a ShellItem instance instead of the ShellLink instance.

**Comment by zhuxb711** [comment]
I hope to release a new version soon to solve this problem. Thanks.

**Comment by dahall** [comment]
I had a build error in my last push. I've corrected it and you should be able to test with the NuGet packages from my AppVeyor feed in the next 5 minutes. I'm finishing some work on the addition of the DbgHelp library and then I'll release new official packages sometime this week.

**Comment by zhuxb711** [comment]
@dahall 
I have tested the 3.2.14 version and it is currently working well, thank you.

**Comment by dahall** [comment]
This is now officially published to NuGet
