### ISSUE TITLE
INameSpaceTreeControl.GetRootItems - parameter is incorrect

### ISSUE THREAD

**Issue by tonyhallett** [dahall/Vanara#157]
I was interested in what the initial root items are so forked your code and added this line in OnCreateControl before you remove the root items. https://github.com/dahall/Vanara/blob/7a46a780110e5a3c4fe6ce66285ca55dd816499d/WIndows.Forms/Controls/ShellNamespaceTreeControl.cs#L884

`var getRootItemsResult = pCtrl.GetRootItems(out var rootItems);`

The error is parameter is incorrect
![image](https://user-images.githubusercontent.com/11292998/91189753-bc0e2200-e6ea-11ea-8f26-300768449b79.png)

Interop is not my forte.  Perhaps you can advise.

Thanks Tony

**Comment by dahall** [comment]
Yep. That method returns E_INVALIDARG if there are no items displayed in the view or if the control has not been initialized yet. The docs say `RemoveAllRoots` must be called before use.
