### ISSUE TITLE
ExplorerBrowserTestForm throws AccessViolationException

### ISSUE THREAD

**Issue by tonyhallett** [dahall/Vanara#158]
https://github.com/dahall/Vanara/blob/7a46a780110e5a3c4fe6ce66285ca55dd816499d/UnitTests/ExplorerBrowser/ExplorerBrowserTestForm.cs#L39			
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory 

This form is commented out, perhaps it should not be used ?
https://github.com/dahall/Vanara/blob/7a46a780110e5a3c4fe6ce66285ca55dd816499d/UnitTests/ExplorerBrowser/Program.cs#L19

**Comment by dahall** [comment]
Yes. I reused the framework to test both and just comment out one or the other to test.

**Comment by tonyhallett** [comment]
Do you get the exception with the ExplorerBrowserTestForm ?

**Comment by dahall** [comment]
Yes. I broke something here while trying fix something else. I found root cause and should release a fix soon.

**Comment by tajbender** [comment]
I still have Issues running the demo. The App crashes hard, and just closes.

Running a build using the following version of Vanara:

Revision: 4fea35cd9e04e96479f5770ff49cb0b830c3ff64
Author: dahall <dahall@byu.net>
Date: 12/09/2020 20:10:44
Message:
Added SIZEOF_SOCKET_ADDRESS_LIST macro.
Added conversions from SOCKADDR_IN to SOCKADDR_IN6.
Added SOCKET_ADDRESS_LIST.Pack to convert structure to a packad memory

**Comment by dahall** [comment]
I just wanted to let you know I've been looking into the root cause for that last couple of days and am stumped. I'll keep working on this, but it is going to take more time.

**Comment by tajbender** [comment]
Okay, David, as soon as I am able to find a hint where this comes from, I'll let you know.

However, thanks for your support, keep up the great work, a stay healthy.

**Comment by tajbender** [comment]
After working on `ShellBrowser` I came to a very similar problem, and I think it has to do with the lifetime of COM-Object-Instances.

In my case, I created an IShellFolder, passed it to a method as an argument, and voilà, the same problem. Can't tell more at the moment, I'm still investigating further.

But I think, let's assume you have the following scenario (and excuse my rugged English language, it's not my mother language):

- Caller A
- Component B which implements an COM-Interface

Caller A creates an argument of type `ShellFolder` which gets passed as argument to COM-Component B. For example, let's say you have:

`CallerA.SomeMethod() => return ComponentB.Navigate(new ShellFolder(@"C:\"));`

ComponentB stores a reference to `ShellFolder(@"C:\")` for later processing. _It stores the reference to the object itself, and does not make a copy of it._

In my case, which was in fact as simple as that, the argument for Method `ComponentB.Navigate()` was already invalidated a few moments later although ComponentB still had a valid reference to it. In my understanding, as long as anyone has a reference to an object on the heap, the Garbage Collector is not allowed to Dispose() it - cause that would make no sense, that's how garbage collection has to work.

However, I think in that particular case the object may get collected as soon as `CallerA.SomeMethod()` finished. So it is valid to use that object in `ComponentB.Navigate()`, but it is not valid to store a reference to it for further processing.

Instead
- the value has be passed as reference (maybe and if possible?), or
- ComponentB has to increase it's reference count (if there's one), or
- ComponentB has to make a clean copy for further processing

@dahall: I hope I was able to point out what I think the problem could be.

Regards, tajbender

**Comment by tajbender** [comment]
I found some time to play around with `Explorer Browser Demo`.  Albeit being currently rather slow cause all that debug-stuff it seems to work again. The following patch-file is based on commit dbec5d0507c9847c1c635798939740ed923b9b2e , I hope you can reproduce the working state I'm currently testing on.

[Vanara.ExplorerBrowser - WorkingAgainPatch 21.04.21.diff.zip](https://github.com/dahall/Vanara/files/6343295/Vanara.ExplorerBrowser.-.WorkingAgainPatch.21.04.21.diff.zip)

The question is, where is the hard worker that will isolate the root cause for the Exceptions? 😁 I have to admit that some days ago I changed some debug-settings, so I hope someone can confirm that it works _at least better_ now?

**Comment by tajbender** [comment]
@dahall : Okay, further testing showed that these comments seems to fix the issue so far:

`

			/// <summary>
			/// Internal method that actually releases the handle. This is called by <see cref="M:Vanara.PInvoke.SafeHANDLE.ReleaseHandle"/>
			/// for valid handles and afterwards zeros the handle.
			/// </summary>
			/// <returns><c>true</c> to indicate successful release of the handle; <c>false</c> otherwise.</returns>
			protected override bool InternalReleaseHandle()
			{
				//ILFree(handle);  <-- commented out for testing by tajbender
				return true;
			}
`
`

			/// <summary>Updates the handle after freeing the existing handle.</summary>
			/// <param name="newHandle">The new handle.</param>
			protected virtual void UpdateHandle(IntPtr newHandle)
			{
				//ILFree(handle);   <-- commented out for testing by tajbender
				SetHandle(newHandle);
			}
`

I'll dig further into it...

Regards,
tajbender

**Comment by tajbender** [comment]
Heureka, I've got it. Thanks for reading.

I'll prepare a pull request the next days! Small issue, great impact, as always with really nasty bugs.

**Comment by tajbender** [comment]
See Pull Request https://github.com/dahall/Vanara/pull/224

**Comment by dahall** [comment]
> Heureka, I've got it. Thanks for reading.
> 
> I'll prepare a pull request the next days! Small issue, great impact, as always with really nasty bugs.

THANK YOU!! This one had evaded me for months.

**Comment by tajbender** [comment]
Thank you for all the great work. That was a nasty one... Without having a very similar issue in ShellBrowser a few weeks ago I wouldn't have found it...

Those bugs could really drive you crazy, cause you have no chance finding the root cause by debugging, it just depends on luck 🍀
