### ISSUE TITLE
Expose INameSpaceTreeControl from IExplorerBrowser

### ISSUE THREAD

**Issue by tonyhallett** [dahall/Vanara#159]
I found this python code which suggests that it is possible
http://plaxis.us/updater/Plaxis%202D/2017.00/files/python/Lib/site-packages/win32comext/shell/demos/explorer_browser.py

This would allow working with the tree control on the left.

**Comment by dahall** [comment]
Added DangerousGetInterface() method to expose the underlying IExplorerBrowser interface. Use with caution. It for sure can be used to query for that interface, but do not use it directly as it will cause the control to be out of sync.
