### ISSUE TITLE
NtQuerySystemInformation is missing

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#16]
https://docs.microsoft.com/en-us/windows/desktop/api/winternl/nf-winternl-ntquerysysteminformation

There are many options to call this function.
There should be a generic and a specialized:  https://www.pinvoke.net/default.aspx/ntdll.ntquerysysteminformation

As well SYTEM_INFORMATION_CLASS: http://www.pinvoke.net/default.aspx/ntdll/SYSTEM_INFORMATION_CLASS.html

**Comment by dahall** [comment]
Added. See https://github.com/dahall/Vanara/blob/master/PInvoke/NTDll/NTDll.cs for implementation and offer any comments.
