### ISSUE TITLE
How to get Recycle Date from ShellItem ?

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#162]
**Describe the bug**
How can I get the deletion date from the file in the recycle bin?
I searched Ole32.PROPERTYKEY.System but did not find any related properties

**Comment by dahall** [comment]
I have no idea. Sounds like time to ask Google.

**Comment by zhuxb711** [comment]
I found this:
https://stackoverflow.com/questions/12871456/get-the-date-when-the-file-was-sent-to-recycle-bin

**Comment by dahall** [comment]
I've added some new property keys so you can call:
`shellItem.Properties[Ole32.PROPERTYKEY.System.Recycle.DateDeleted]` to get a `FILETIME` struct with the date the item was deleted. There is a helper method in `Vanara.Extensions` for `FILETIME` that will convert to a `DateTime` called `ToDateTime`.

I'll likely release this code in the next few days. If you want to use that PROPERTYKEY before then, the Guid is `{9b174b33-40ff-11d2-a27e-00c04fc30871}` and the ID is `3`.

**Comment by zhuxb711** [comment]
Thanks a lot.
