### ISSUE TITLE
The directory folder (WIndows.Forms) name is misspelled

### ISSUE THREAD

**Issue by DarkByte7** [dahall/Vanara#165]
**Describe the bug**
The directory folder (`WIndows.Forms`) has a minor spelling mistake. Its using the wrong character casing in the folder name. The first (`I` or `i`) character should be lowercase instead of an uppercase. I did a quick search on the repository for the exact associated path to check for any affected paths that may have been linked and it appears they are all otherwise in the right order.

The casing maybe not always recognized properly as the exact name and may cause future issues linking references. 

> ### Example: 

#### Currently:
`WIndows.Forms`

#### Fixed:
`Windows.Forms`

**What code is involved**
It appears just the folder name is affected by the misspelling. ( [`Vanara/WIndows.Forms`](https://github.com/dahall/Vanara/tree/master/WIndows.Forms)). I was unable to find any further files that may have been affected when referencing the library.

**Comment by dahall** [comment]
This has bugged me for a while, but I had no reason to fix it since it wasn't messing anything up. But, it appears there are other OCD people in the world like me! :) I hope this relieves some anxiety when using this project.
