### ISSUE TITLE
How can ı write custom audit log in windows log/security

### ISSUE THREAD

**Issue by nto4** [dahall/Vanara#167]
Im trying to insert logs in security log and my code is looks like that what is wrong my code ? 
bert variable always false and how can generate correctly this function parameters ım not sure can you explain or can you share any example for custom write audit logs  ?
thans for help.

using System;
using System.Text;
using Vanara.PInvoke;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security;
using Vanara.Extensions;
using Vanara.InteropServices;
using static Vanara.PInvoke.AdvApi32;
using static Vanara.PInvoke.Kernel32;
using static Vanara.PInvoke.Authz;
using Newtonsoft.Json;

namespace vanara
{
    public static class F
    {
        public static string Dump(object obj)
        {
            return JsonConvert.SerializeObject(obj);
        }
    }
    class Program
    {
        public static uint dwFlags = 123;
        public static AUTHZ_SECURITY_EVENT_PROVIDER_HANDLE hEventProvider;
        public static uint dwAuditId = 123;
        public static PSID pUserSid;//= SafePSID.CreateFromPtr((IntPtr)(void*)psid);// = Convert.toPSID ("S-1-5-18");
        public static AUDIT_PARAMS dwCount;
    static void Main(string[] args)
        {
          //  var dw = GetLastError();
            var bret = Vanara.PInvoke.Authz.AuthzReportSecurityEventFromParams(dwFlags, hEventProvider,dwAuditId,pUserSid,dwCount);
         //   var lookHere = F.Dump(bret);
          //  Console.WriteLine("Hello World!");
        }

    }
}

**Comment by dahall** [comment]
Does the .NET Framework `System.Diagnostics.EventLog` class not meet your needs?

**Comment by nto4** [comment]
This cant be write in windows / secuirty  forexample like audit log im using now AuthzReportSecurityEvent function c++ implamentation for writing this log but ı have some formatting problem.
I want to be write security log in windows server  like audit log(login, logout etc.) if vanara can be support this feature( u write supported "AuthzReportSecurityEvent")  can you share me any example or can you explain how can use this in .net ? with vanara how ıcan write log using this function or another sysyem call for writing secuirty log in windows logs/security.
Thx for answer.

**Comment by dahall** [comment]
See examples [here](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.eventlogentrytype?view=dotnet-plat-ext-3.1#examples) on using `System.Diagnostics.EventLog.WriteEntry` with the `SuccessAudit` flag. I would not use the `AuthzReportSecurityEvent` API call in this case. Too much for someone unfamiliar.
