### ISSUE TITLE
CREDUI_FLAGS_KEEP_USERNAME for CredentialsDialog

### ISSUE THREAD

**Issue by TechInterMezzo** [dahall/Vanara#168]
Could the flag CREDUI_FLAGS_KEEP_USERNAME be implemented in the Vanara.Windows.Forms.CredentialsDialog class?
I would really like to force the user to use a specific predefined username.

Or maybe could there be a virtual property or method to set additional flags in a derived class? At the moment i would have to implement the RunDialog myself to use other flags.

**Comment by dahall** [comment]
Added protected virtual CredentialsDialog.GetDialogFlags and CredentialsDialog.GetPreVistaDialogFlags methods that return the flags used by SDK functions so you can add that flag in a derived class. This will get pushed in the next few days.
