### ISSUE TITLE
System.AccessViolationException when calling LsaOpenPolicy with a remote machine name

### ISSUE THREAD

**Issue by ryannewington** [dahall/Vanara#169]
**Describe the bug**
When calling the overload of  AdvApi32.LsaOpenPolicy take takes a computer name parameter, and access violation is thrown. Passing null as the computer name, or using the overload without the computer name parameter does not throw an exception.

**What code is involved**
```c#
AdvApi32.LSA_OBJECT_ATTRIBUTES lsaObjectAttributes = new AdvApi32.LSA_OBJECT_ATTRIBUTES();
var result = AdvApi32.LsaOpenPolicy(server, lsaObjectAttributes, AdvApi32.LsaPolicyRights.POLICY_VIEW_LOCAL_INFORMATION, out AdvApi32.SafeLSA_HANDLE pPolicyHandle);
result.ThrowIfFailed("LsaOpenPolicy failed");
```

**Expected behavior**
The API call should succeed.

**Screenshots**
![image](https://user-images.githubusercontent.com/17229877/93043833-4f0cfd00-f696-11ea-96d0-33179779e379.png)

**Comment by dahall** [comment]
This is expected behavior of the native API if you do not have the rights on the specified remote system to view the specified policy. There are many online articles that detail how to configure remote machines in order to access policy information. There are also many examples in C/C++. If you find you are able to call this function in C/C++ but not in this library, please let me know.

**Comment by dahall** [comment]
Also, make sure you are calling this method using an account with access on the remote system. You many need to impersonate an account to do this.

**Comment by ryannewington** [comment]
If I don't have access, it should return error code 5, not a memory corruption?

If I pass in 'null' to the function (meaning the local machine), it works, so it's not an access issue. If I pass in the local machine name, it get the access violation.

**Comment by ryannewington** [comment]
Ah, x86 seems to be fine. The access violation only happens in a x64 app.

**Comment by dahall** [comment]
Thanks for the further testing. Working on that case now.

**Comment by ryannewington** [comment]
Let me know if there is anything I can do to help. I've had a look at the underlying code, but can't see anything immediately obvious. I can spend some time on this later today if needed.

**Comment by dahall** [comment]
I think I found the problem. Under X64, the LSA_UNICODE_STRING struct aligns in memory differently. In my custom marshaler, I assume the X86 layout. I've corrected and am testing now.

**Comment by dahall** [comment]
In about 10 minutes, the NuGet source at https://ci.appveyor.com/nuget/vanara-prerelease will have an updated build with the fix. I'd appreciate your confirmation that it is working.

**Comment by ryannewington** [comment]
Perfect Dave. Tested on x86 and x64 and working fine.

I just want to say thanks heaps for these libraries. I've done a ton of interop code in the past, and sometimes the smallest things can take so long to do. This library set saves so much time. I really appreciate the work you've put into this. 

Ryan

**Comment by dahall** [comment]
Thank you. It's for comments like yours that I keep doing it.
