### ISSUE TITLE
IPropertySetStorage does not persist properties

### ISSUE THREAD

**Issue by gave92** [dahall/Vanara#170]
**Describe the bug**
Hello I'm having trouble writing custom properties to file when using the [ipropertysetstorage-ntfs implementation](https://docs.microsoft.com/en-us/windows/win32/stg/ipropertysetstorage-ntfs-file-system-implementation).
Looks like the properties are not getting saved. When I try to write and then read a property, I get "S_FALSE".

**What code is involved**
```cs
// creates a new storage object using NTFS implementation
var hr = Ole32.StgCreateStorageEx(@"test.txt",
    STGM.STGM_CREATE | STGM.STGM_DIRECT | STGM.STGM_READWRITE | STGM.STGM_SHARE_EXCLUSIVE,
    STGFMT.STGFMT_FILE, 0, IntPtr.Zero, IntPtr.Zero, typeof(IPropertySetStorage).GUID, out var iptr);
var istg = (IPropertySetStorage)iptr;
// creates propertystorage
hr = istg.Create(PROPERTYKEY.System.Keywords.Key, IntPtr.Zero, 0, STGM.STGM_CREATE | STGM.STGM_DIRECT | STGM.STGM_READWRITE | STGM.STGM_SHARE_EXCLUSIVE, out IPropertyStorage ipse);
// write property
var prc = new PROPSPEC() { ulKind = PRSPEC.PRSPEC_PROPID, union = new PROPSPEC.PROPSPECunion() { propid = PROPERTYKEY.System.Keywords.Id } };
var prv = new PROPVARIANT("VALUE", VarEnum.VT_LPSTR);
ipse.WriteMultiple(1, new PROPSPEC[] { prc }, new PROPVARIANT[] { prv }, 2);
hr = ipse.Commit((uint)STGC.STGC_DEFAULT);
// read property
var prvRead = new PROPVARIANT();
hr = ipse.ReadMultiple(1, new PROPSPEC[] { prc }, new PROPVARIANT[] { prvRead });
Debug.WriteLine(hr); --------------------> prints "S_FALSE", the property is not present
Marshal.ReleaseComObject(ipse);
Marshal.ReleaseComObject(istg);
```

**Expected behavior**
The code should save the value "VALUE" to the "Keywords" property and read it again.

I admit I'm not particularly sure of the correctness of the above code, if the mistake is mine I apologize :)

**Comment by dahall** [comment]
Check to verify that you can set custom properties on "txt" files. I don't think you can.

All those functions and structures do work as I'm using them in the `Vanara.Windows.Shell` project. There, you can use the `ShellItem` class to set properties. Check the unit test for exact syntax, but you should be able to do something like:
```cs
using var item = new ShellItem(fullFilePath);
item.Properties[PROPERTYKEY.System.Keywords.Id] = "VALUE";
```

**Comment by gave92** [comment]
Thanks @dahall. The code you provided works fine on video files (which have a tag/keyword property) but not for txt file.
But from my understanding NTFS should allow to define custom properties for any kind of file by storing them as alternate data streams.
This is the code example I followed -> [here](https://docs.microsoft.com/en-us/windows/win32/stg/writeread-sample).
Here they use a "compound file" to store the properties but the process should be the same.

**Comment by dahall** [comment]
Testing this now. I think I have a problem with the PROPSPEC structure. The WriteMultiple method actually fails.

**Comment by dahall** [comment]
I'm testing the fix. Once verified, I'll commit the code and post your code, modified with my changes.

**Comment by dahall** [comment]
That required some rework. There were many bugs. Sorry. The code is all committed now. Here's how I'd write your function:
```cs
var propKey = PROPERTYKEY.System.Title;

// creates a new storage object using NTFS implementation
StgOpenStorageEx(TestCaseSources.LogFile, STGM.STGM_DIRECT | STGM.STGM_READWRITE | STGM.STGM_SHARE_EXCLUSIVE,
   STGFMT.STGFMT_ANY, default, default, default, typeof(IPropertySetStorage).GUID, out var iptr).ThrowIfFailed();
using var istg = ComReleaserFactory.Create((IPropertySetStorage)iptr);

var prc = new PROPSPEC(propKey.Id);

// creates propertystorage
istg.Item.Create(propKey.Key, default, PROPSETFLAG.PROPSETFLAG_DEFAULT, STGM.STGM_CREATE | STGM.STGM_READWRITE | STGM.STGM_SHARE_EXCLUSIVE, out var ipse).ThrowIfFailed();
using (var pipse = ComReleaserFactory.Create(ipse))
{
   // write property
   using var prv = new PROPVARIANT("VALUE", VarEnum.VT_LPWSTR);
   ipse.WriteMultiple(new[] { prc }, new[] { prv }, PID_FIRST_USABLE).ThrowIfFailed();
}

// read property
istg.Item.Open(propKey.Key, STGM.STGM_READ | STGM.STGM_SHARE_EXCLUSIVE, out ipse).ThrowIfFailed();
using (var pipse = ComReleaserFactory.Create(ipse))
{
   ipse.ReadMultiple(new[] { prc }, out var prvRead).ThrowIfFailed();
   Console.WriteLine($"Read value = {prvRead}");
}
```
