### ISSUE TITLE
Vanara lacks `A` (ANSI/UTF-8) variants of console APIs

### ISSUE THREAD

**Issue by alexrp** [dahall/Vanara#171]
There have been a lot of improvements to the console host, pseudoconsoles, etc in Windows 10 as of late. One of those improvements is that the `A` variants of console APIs now support reading/writing UTF-8 data if:

* The global system setting for UTF-8 is enabled; or
* One calls `SetConsoleCP(65001)` before calling `ReadConsoleA()`; or
* One calls `SetConsoleOutputCP(65001)` before calling `WriteConsoleA()`.

Vanara's `ReadConsole`/`WriteConsole` declarations don't explicitly specify `A` or `W`, but they do specify `CharSet.Auto`, which maps to `wchar_t` according to [this page](https://docs.microsoft.com/en-us/dotnet/standard/native-interop/charset), so they end up calling the `W` variants in practice.

So, I think Vanara will have to specifically expose `A` variants in order to enable the UTF-8 scenario. I don't feel very strongly about how they would be named, but it seems to me that it would make sense to only expose `ReadConsoleW` and `ReadConsoleA` to remove any ambiguity for users, especially now that there are valid modern scenarios for both variants.

**Comment by dahall** [comment]
I am having difficulty finding documentation on this. Which functions specifically need to have the 'A' variant exposed? Just Read/WriteConsole?

**Comment by dahall** [comment]
Those two functions now have 'A' variants in the AppVeyor repository (see home page for detail). I decided to just add the 'A' variants rather than break any existing implementations against the 'Auto' tagged functions. Once I hear back from you with any others, I'll add them and then push a new update to NuGet.org.

**Comment by alexrp** [comment]
The documentation is over on this PR: https://github.com/MicrosoftDocs/Console-Docs/pull/162#discussion_r504044121

But as you can see from the discussion there, it turns out there's currently a bug preventing them from working as expected. 😞

**Comment by dahall** [comment]
Released additions of Read/WriteConsole**A**. Please reopen if others are needed once they're fixed in the runtime.
