### ISSUE TITLE
GetPrivateProfileSection results are truncated

### ISSUE THREAD

**Issue by ryannewington** [dahall/Vanara#172]
**Describe the bug**
`GetPrivateProfileSection` is used to return a section from an INI file.

Consider the following example
```ini
[Unicode]
Unicode=yes
[Version]
signature="$CHICAGO$"
Revision=1
```

I can call the `GetPrivateProfileSection` function to return the contents of say the `Version` section. The API returns the results in the following format

`signature="$CHICAGO$"\0Revision=1\0\0`

When the StringBuilder used in the PInvoke declaration encounters the first null character, it stops building the string, and the rest of the result is discarded.

**What code is involved**
```c#
string inf = "C:\temp\my.ini"
StringBuilder sectionData = new StringBuilder(32000);

var bytesFilled = Kernel32.GetPrivateProfileSection("Version", sectionData, 32000, inf);

// sectionData will now hold only the first element
```

**Expected behavior**
All items should be available. Perhaps an array of strings is more appopriate.

**Comment by ryannewington** [comment]
I gave that a go, but I still only get the first result. There are 4 entries in this section.

![image](https://user-images.githubusercontent.com/17229877/96308583-65b8c200-104f-11eb-9633-51bebf882d31.png)

**Comment by dahall** [comment]
I just added overloads to those methods that take an `IntPtr` instead of `StringBuilder`. This should allow you to allocate memory and pass it to the methods. You can then do the following:
```cs
string inf = @"C:\temp\my.ini";
var chars = 32,767;
using var mem = new SafeCoTaskMemHandle(chars * StringHelper.GetCharSize());
var bytesFilled = Kernel32.GetPrivateProfileSection("Version", mem, chars, inf);
return mem.ToStringEnum();
```
If you'd like to try this before the next release, you can check the project home page for info on the AppVeyor prerelease NuGet feed.

**Comment by ryannewington** [comment]
Brilliant. That is working great, thanks David.

Was I doing something wrong with the StringBuilder?

**Comment by dahall** [comment]
No. It appears that different versions of .NET handle StringBuilder internals differently. I'm actually working on some better wrappers so you can simply call : `return Kernel32.GetPrivateProfileSection("Version", inf)` and get a `string[]` with the values. I'll let you know when those are done.

**Comment by dahall** [comment]
Would a wrapper class be a valuable addition to do something like the following?
```cs
var ini = new InitializationFile(@"C:\temp\my.ini");
var versionSettings = ini.Sections["Version"];
foreach (var keyValuePair in versionSettings)
   Console.WriteLine($"{keyValuePair.Key}={keyValuePair.Value}");
versionSettings["MyNewKey"] = "some value";
```

**Comment by dahall** [comment]
I just added one to the AppVeyor build. Look for `Vanara.Configuration.InitializationFile`. I also just pushed a bunch of changes to make the native API functions behave. I removed many of the `StringBuilder` based functions. Please give me your thoughts.

**Comment by ryannewington** [comment]
Yeah thats an awesome idea. I turned to the API because most other parsers are regex or similarly based and I didn't feel comfortable with that. I'll convert my code over to use this and let you know how it goes

**Comment by ryannewington** [comment]
Is it in the Vanara.PInvoke.Kernel32 package? I'm not seeing an updated version on AppVeyor.

**Comment by dahall** [comment]
Yes. I got confirmation of the build a few minutes ago.

**Comment by dahall** [comment]
Sometimes VS has a hard time updating packages whose version didn't change. You may need to flush your NuGet caches.

**Comment by dahall** [comment]
Released!

**Comment by ryannewington** [comment]
Sorry - late on the feedback, but I have used it and it is working well. Great idea. Thanks again David.

**Comment by dahall** [comment]
Glad it is useful. I laid in bed stewing on the idea and it came together quickly the next morning.
