### ISSUE TITLE
TLE while iterating types in AD

### ISSUE THREAD

**Issue by sos-dll** [dahall/Vanara#173]
**Describe the bug**
An exception is thrown while iterating all exported/public types in the current AppDomain.
```
System.TypeLoadException: Could not load type 'PARTITION_INFORMATION_EX' from assembly 'Vanara.PInvoke.Kernel32, Version=3.2.19.0, Culture=neutral, PublicKeyToken=c37e4080322237fa' because it contains an object field at offset 32 that is incorrectly aligned or overlapped by a non-object field.
```

**What code is involved**
See [DotNetFiddle](https://dotnetfiddle.net/icCEE2)
<details><summary>(see here if DotNetFiddle is invalid)</summary>
<p>

```cs
using System;
using System.Runtime.InteropServices;
using static Vanara.PInvoke.Kernel32;

static class Program
{
	static void Main()
	{
		Vanara.BOOL b = true;
		if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
		{
			var temp = GetCurrentProcessId();
		}
		try
		{
			foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies()) {
				foreach (var type in assembly.GetExportedTypes()) {
					_ = type.FullName;
				}
			}
		}
		catch (TypeLoadException ex)
		{
			Console.WriteLine(ex);
		}
	}
}
```

</p>
</details>

**Expected behavior**
No exception.

**Bonus details**
[`PARTITION_INFORMATION_EX` uses a wrong layout, click here](https://github.com/dahall/Vanara/blob/ffc54378a7a40dbd4558165331c17686cd405203/PInvoke/Kernel32/WinIOCtl.Structs.cs#L2226).
[The correct layout would be this, click here](https://github.com/terrafx/terrafx.interop.windows/blob/main/sources/Interop/Windows/um/winioctl/PARTITION_INFORMATION_EX.cs).

**Comment by dahall** [comment]
Thanks. I ended up doing something different, but the link helped me find the problem quickly. This should now work. You can pull the pre-release NuGet package 3.2.20 from AppVeyor (see homepage) for testing.
