### ISSUE TITLE
Bad Value in Parameters' default values.

### ISSUE THREAD

**Issue by DineshSolanki** [dahall/Vanara#174]
**Describe the bug**
I'm getting bad value as the default parameter of Pinvoke methods

**What code is involved**
All Methods starting with 'SH'

**Expected behavior**
while I understand that these parameters are marked optional but not given a default value, that works but IntelliSense confuses it by saying that "the passed value has the same as default value" no matter what I pass.

**Screenshots**
![image](https://user-images.githubusercontent.com/15937452/97871548-b06a5780-1d3a-11eb-9979-6f456a292d49.png)

**Comment by dahall** [comment]
I have confirmed that this is not a problem on my system. Those values are specified as `Optional` with `IntPtr` types, which is a pattern used throughout the library and .NET in general. Your _Intellisense_ may be corrupted.

**Comment by DineshSolanki** [comment]
> 
> 
> I have confirmed that this is not a problem on my system. Those values are specified as `Optional` with `IntPtr` types, which is a pattern used throughout the library and .NET in general. Your _Intellisense_ may be corrupted.

It's JetBrains RIDER , do you think, I should open a issue there?

**Comment by dahall** [comment]
Yes
