### ISSUE TITLE
Always throw InvalidOperationException in class RecycleBin

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#179]
See this:
https://github.com/dahall/Vanara/blob/a3bfd8c7cdc88b0cef12be696451414a522fb9be/Windows.Shell/RecycleBin.cs#L84

ShellFolder must implement IEquatable to compare. In this case, it compares whether the two are the same instance, not whether they are the same folder. Therefore, ShellFolder must implement IEquatable or compare the paths of folders here to see if they are the same.

**Why can it pass the test?**
https://github.com/dahall/Vanara/blob/3085b7d41228b0c2a821b0afa3b314f1fe9ec461/UnitTests/Windows.Shell/RecycleBinTests.cs#L43

You got ShellItems from RecycleBin.GetItemFromOriginalPath(). Which is created by ShellFolderInstance. So its parent is the same instance

**How to reproduce**
```csharp
//Path is the deleted item's filesystempath
using (ShellItem SourceItem = new ShellItem(Path))
{
         RecycleBin.Restore(SourceItem, true);
}
```

**Comment by dahall** [comment]
`ShellFolder` derives from `ShellItem` which implements `IEquatable` based on the PIDL. To confirm, I just ran:
```cs
new ShellFolder(KNOWNFOLDERID.FOLDERID_Documents) == new ShellFolder(KNOWNFOLDERID.FOLDERID_LocalDocuments)
```
and got `true`.

I'm not sure what the request is here other than putting IEquatable on ShellFolder. Let me know if there is more to the request.

**Comment by zhuxb711** [comment]
```csharp
string Path = RecycleBin.GetItems().FirstOrDefault().FileSystemPath;
ShellItem Item = new ShellItem(Path);
RecycleBin.Restore(Item);
```

It will throw InvalidOperationException

**Comment by dahall** [comment]
This was fascinating. For some reason when using SHCreateItemFromParsingName on a physical file in the Recycle Bin the IShellFolder returned is not the same as getting the IShellFile item from enumerating items in the Recycle Bin. I worked this out in C to avoid any C# problems. The PIDLs are different even though the names are the same. To avoid this, use the ShellItem value retrieved from `GetItems` or from calling `GetItemFromOriginalPath` when calling `Restore`. I don't know why Windows Shell is doing this, but it is consistent.
