### ISSUE TITLE
SafeHandle overloads

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#18]
Functions receiving IntPtr should receive SafeHandle instead.

E.g. instead of
```cs
public static extern bool CreateProcessAsUser(IntPtr hToken, ...)
```

It is better to have
```cs
public static extern bool CreateProcessAsUser(SafeTokenHandle hToken, ...)
```

Nowadays everyone is using safe handles, so converting back and forth is not only unnecessary but may introduce bugs.

**Comment by dahall** [comment]
I've tried to do that where required. Looks like I missed this one. Thanks. My logic has been to use IntPtr in situations where it is a handle that does not have to be closed or where the closure is handled automatically. If you find situations, like the one above, where I've missed this, please let me know.

**Comment by NN---** [comment]
Can you show such function ?
Whenever you open a handle you want to close it, and you use SafeHandle wrapper.

In such rare cases you can pass false in ownsHandle parameter:
https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.safehandle.-ctor?view=netframework-4.7.2

**Comment by dahall** [comment]
Menu handles, Window handles, Resource handles. All of which are closed by the OS during other operations. Often these handles are returned by functions so there is no means to set the ownership to false. If there are areas where you'd like changes, please start submitting PRs.

**Comment by NN---** [comment]
I see, you can introduce a SafeHandle wrapper which doesn't close.
```cs
class SafeMenuHandle : SafeHandle { void ReleaseHandle() {/*nothing*/} }
```

It is better than just IntPtr since it doesn't allow you to pass incorrect handle type to the function.

**Comment by dahall** [comment]
I didn't use SafeTokenHandle in the CreateProcessAsUser method (and I'm sure some others) because it would require a project dependency on Vanara.PInvoke.Security which would introduce a circular reference. In general, I agree with your assertion that SafeHandles should be used whenever possible.

**Comment by NN---** [comment]
It doesn't sound like a good decision.
If you need to break circular refererence you can do it.
Technically you can make manually circular reference but it is not good idea :)

**Comment by NN---** [comment]
Seems like little bit overcomplicated, especially Func in the constructor.
I guess you don't really need SafeHandle where you don't need it.

If you want C# HICON to be synonym for HANDLE but more type safe you can use simple struct.

```cs
[StructLayout(LayoutKind.Explicit, Pack = 0)]
struct HICON 
{
  [FieldOffset(0)]
  private IntPtr handle;
}
```

This way marshaller will marshal the structure as simple IntPtr but gives you type safety, e.g. you cannot pass HINSTANCE into DestroyIcon.

WDYT ?

**Comment by dahall** [comment]
I thought about that, but then I can't derive the SafeXX version from it and have it marshaled correctly.

The Func in the constructor just makes it easier to build 30+ derived classes by just supplying a method rather than overloading ReleaseHandle every time.

**Comment by NN---** [comment]
Your use case is duality of HMENU etc. 
Like GetMenu doesn't need to be destroyed but CreateMenu does. Correct?

So for first you want SafeHandle that doesn't destroy and for second you do want.
E.g.:
```cs
public static extern HMENU GetMenu();

public static extern SafeMenuHandle CreateMenu();

public static extern void DestroyMenu(HMENU menu);
```

Next is have two types of overloads.

If you want life simpler than you can do what you proposed just give better names.
HMENU name implies that it is not safehandle and you don't need to dispose it.

As for Func parameter it involves additional member instead of overloading function.
In the end it is the same amount of code but without Func you have smaller objects which better for GC.
If you have too much copy paste code just use T4, it is not so bad as you might think.

**Comment by dahall** [comment]
I just checked in a ton of changes implemented the idea above. It will seriously screw anyone who has used the library in the past, but I think it is a major improvement. Thanks for pushing the idea. Give the posts a look and see what you think. I think I will have to change the version to 2.0 and popup a web page explaining the changes.

**Comment by NN---** [comment]
I'll take a look ASAP.
IMO SafeIconHandle is better name than SafeHICON.
You have several examples for this convention even in .NET itself.
https://github.com/dotnet/corefx/tree/master/src/System.Diagnostics.Process/src/Microsoft/Win32/SafeHandles

**Comment by dahall** [comment]
I thought about that naming for the exact reason you suggest, but think that parity with the Windows API, especially reading their documentation, makes keeping with the API names a better option. I do that with functions, enums and structures, so I can't justify deviating for handles.
