### ISSUE TITLE
NtDll

### ISSUE THREAD

**Issue by arsium** [dahall/Vanara#182]
Hello Sir just interested if you could complete NtDll implementation ?

Also a dll : win32u.dll

**Comment by dahall** [comment]
Ntdll is huge and is mostly low level driver functions. I believe most of the functions would never get used by the public. If there are specific functions you would like me to include, please list them here and I will include them.

**Comment by dahall** [comment]
I will look into win32u

**Comment by arsium** [comment]
Yes yes they seems to be similar with user32.dll 

also do you implement SetDeskWallpaper for user32 ? I've searched it in your src but didn't find it.

**Comment by dahall** [comment]
I have not implemented either `SetDeskWallpaper` (see your issue #183) and likely won't do `NtUserShowSystemCursor` since both are undocumented and not supported API by Microsoft.

**Comment by arsium** [comment]
Okay okay no problem :)
