### ISSUE TITLE
Missing User32 function

### ISSUE THREAD

**Issue by arsium** [dahall/Vanara#183]
Hello Sir ,

I saw User32 missed : BOOL extern SetDeskWallPaper(LPSTR lpstrBitmap);

    <DllImport("user32.dll")>
        Public Shared Function SetDeskWallpaper(ByVal FileName As String) As Long

        End Function

**Comment by dahall** [comment]
That is an undocumented function. The recommended approach is to use `IDesktopWallpaper` and its functions. I have wrapped this COM interface in [WallpaperManager.cs](https://github.com/dahall/Vanara/blob/master/Windows.Shell/WallpaperManager.cs).
