### ISSUE TITLE
Fix misspelling in PInvoke-Folder tree

### ISSUE THREAD

**Issue by tajbender** [dahall/Vanara#186]
**Describe the bug**
I've found another misspelled folder/item

**What code is involved**
`Vanara\PInvoke\N ~t~ Dll\Winternl.cs`

**Expected behavior**
`Vanara\PInvoke\N ~T~ Dll\Winternl.cs`

**Screenshots**

**Comment by tajbender** [comment]
AFIK, that's the last actual issue of this kind 😁

**Comment by dahall** [comment]
This is strange. They are in the same directory on my system. Thanks for finding this oddity.
