### ISSUE TITLE
PInvoke.IpHlpApi.GetExtendedUdpTable

### ISSUE THREAD

**Issue by bweberde** [dahall/Vanara#189]
Using GetExtendedUdpTable to get all upd4 ports returns a lot of 0.0.0.0:0 Ports.
I believe the reason is an alignment/padding problem in the MIB_UDPROW_OWNER_MODULE struct.

The return value is an array of rows where each row is a structrured like this:
public struct MIB_UDPROW_OWNER_MODULE {
  public IN_ADDR dwLocalAddr;
  public uint dwLocalPort;
  public uint dwOwningPid;
  public FILETIME liCreateTimestamp;
  public int SpecificPortBind; 
  public ulong[16] OwningModuleInfo;
}

The actual returned structures by windows have an additional 32 bit DWORD between the dwOwningPid and the following liCreateTimestamp. I believe the DWORD is added by the compiler as a padding so that 64 bitliCreateTimestamp can be aligned on a 64 bit border. 
This not only affects the following fields of the structure but also messes up the structure length so that the next structure in the array will start within the last 4 bytes of the previous OwningModuleInfo. And since these are mostly 0 the next entries will have a dwLocalAddr and dwLocalPort of zero.

A simple loop over the results should expose the problem:
```
    using (var table = IpHlpApi.GetExtendedUdpTable<IpHlpApi.MIB_UDPTABLE_OWNER_MODULE> IpHlpApi.UDP_TABLE_CLASS.UDP_TABLE_OWNER_MODULE, Ws2_32.ADDRESS_FAMILY.AF_INET, false)) {
        foreach (var row in table) {
            Debug.Print($"Addr {row.dwLocalAddr}, Port {row.dwLocalPort}");
        }
     }
```
I experimentally added a dummy DWORD and it seemed to fix the Problem. Maybe this can also be fixed by the Structlayout annotation but I am not a frequent pinvoker...
Regards
Bernd Weber

**Comment by dahall** [comment]
Yes. There appears to be the need then to use `Pack = 8` in `StructLayout`. I've done that and ask you to test the NuGet packages on AppVeyor that will be built in a about 15 minutes (see homepage readme for more detail).

**Comment by bweberde** [comment]
Sorry to disappoint. When I tried to fix this I tried the same thing but it changed nothing. (At least not here). I am building for net5.0 and x64. I guess the layout does not treat liCreateTimestamp as a 64 bit structure but as two 32 bit values. I could try to experiment with explicit layout over the weekend. 

BTW thanks for making this library public.
Bernd

**Comment by dahall** [comment]
I've just confirmed that the structure size and layout does not change in native C code between x86 an x64 builds. Here's the size and offset of each field. I'll work on the C# structure now to ensure it always has these offsets.

MIB_UDPROW_OWNER_MODULE : 160
MIB_UDPROW_OWNER_MODULE.dwLocalAddr : 0
MIB_UDPROW_OWNER_MODULE.dwLocalPort : 4
MIB_UDPROW_OWNER_MODULE.dwOwningPid : 8
MIB_UDPROW_OWNER_MODULE.liCreateTimestamp : 16
MIB_UDPROW_OWNER_MODULE.OwningModuleInfo : 32

**Comment by dahall** [comment]
I took your suggestion and added the dummy padding field. Tested GetExtendedUdpTable on both x86 and x64 and it seems to work, providing many expected IP address values.

**Comment by bweberde** [comment]
Thanks for the quick solution. If you want to get rid off the dummy: This will make the compiler recognize the FileTime as a 64 Bit structure and at the same time add a usable long that can be used in DateTime.FromFileTimeUtc(fileTime).
No garanties for unexpected side effects :-)
[StructLayout(LayoutKind.Explicit)]
public struct FILETIME
{
  [FieldOffset(0)] public ulong dwDateTime;
  [FieldOffset(0)] public int   dwLowDateTime;
  [FieldOffset(4)] public int   dwHighDateTime;
}

**Comment by dahall** [comment]
I think `FILETIME` will always be 8 bytes, maybe you're saying 64-contiguous bits. I'll think about your option. FYI, there is already an extension method for `FILETIME` that converts to `DataTime`: [ToDateTime](https://github.com/dahall/Vanara/blob/1fb8a2dc8a116995831730a7d433a07f940cc5ef/Core/Extensions/FileTimeExtensions.cs).

**Comment by bweberde** [comment]
Hi David, thanks for the first Fix - I believe MIB_UDP6ROW_OWNER_MODULE needs the same padding.
Regards  Bernd

**Comment by dahall** [comment]
Thank you. After checking, you are correct. I have committed the fix and it will go out in the next release.
