### ISSUE TITLE
Using ref structs

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#19]
From readme.md:
```Where structures are always passed by reference and where that structure needs to clean up memory allocations, I have changed the structure to a class implementing IDisposable.```

C# 7.2 introduces reference value types which doesn't require you to use class anymore.
https://docs.microsoft.com/en-us/dotnet/csharp/reference-semantics-with-value-types

It means you don't have overhead of reference type such as GC and you keep passing arguments by reference without specifying explicitly as reference types do.
And your struct can implement IDisposable still.

Btw, 'in' keyword even allows you to pass a reference to struct which is used in 'using' unlike 'ref' keyword.

Full sample:

```cs
using System;
using System.Runtime.InteropServices;

namespace ConsoleApp2
{
    [StructLayout(LayoutKind.Sequential)]
    public struct RECT : IDisposable
    {
        public int x, y, w, h;

        public void Dispose()
        {
            Console.WriteLine("Disposing RECT");
        }
    }

    static class User
    {
        [DllImport("user32")]
        public static extern void GetWindowRect(IntPtr a, in RECT r);

        [DllImport("user32")]
        public static extern IntPtr GetDesktopWindow();
    }

    public class Program
    {
        static void Main(string[] args)
        {
            using (var rect = new RECT())
            {
                User.GetWindowRect(User.GetDesktopWindow(), rect);
                Console.WriteLine($"{rect.w}x{rect.h}");
            }
        }
    }
}
```

**Comment by dahall** [comment]
Have you tested your `GetWindowRect` declaration above and confirmed it marshals correctly? If so, then I will definitely move to this model instead of [MarshalAs(UnstructuredType.LPStruct)].

**Comment by NN---** [comment]
Yes, it works for me.
I suggest you to double check of course.

**Comment by dahall** [comment]
The 2.0 release uses `in` where applicable and wherever I could find. If you find omissions, please let me know.
