### ISSUE TITLE
Example for Registering for Events

### ISSUE THREAD

**Issue by tkennedy13** [dahall/Vanara#190]
I have a windows service (C#) that needs to monitor for power change events. Is there a clear, full example of how to use RegisterPowerSettingNotification in the [PInvoke.User32](https://github.com/dahall/Vanara/blob/1fb8a2dc8a116995831730a7d433a07f940cc5ef/PInvoke/User32/WinUser.Power.cs) library? I didn't see any examples in the [UnitTests](https://github.com/dahall/Vanara/tree/master/UnitTests) or the [WInClassicSamples](https://github.com/dahall/WinClassicSamplesCS).

**Comment by dahall** [comment]
Sorry. I don't have one. However, your comment has caused me to revisit `Vanara.Diagnostics.PowerManager` where I had intended to put power events. Give me a few days, and I may have something you can use.

**Comment by dahall** [comment]
I'm not quite done with my component to really make this easy, but here's some working code using the library functions that may help to get you started.
```cs
using System;
using System.ComponentModel;
using System.Windows.Forms;
using Vanara.Extensions;
using Vanara.PInvoke;
using static Vanara.PInvoke.PowrProf;
using static Vanara.PInvoke.User32;

public partial class Form1 : Form
{
   private SafeHPOWERSETTINGNOTIFY hNot;
   private static readonly Guid notGuid = GUID_POWERSCHEME_PERSONALITY;

   public Form1()
   {
      InitializeComponent();
   }

   protected override void OnClosing(CancelEventArgs e)
   {
      hNot?.Dispose();
      base.OnClosing(e);
   }

   protected override void OnLoad(EventArgs e)
   {
      hNot = RegisterPowerSettingNotification(Handle, notGuid, Vanara.PInvoke.User32.DEVICE_NOTIFY.DEVICE_NOTIFY_WINDOW_HANDLE);
      Win32Error.ThrowLastErrorIfInvalid(hNot);
      base.OnLoad(e);
   }

   protected override void WndProc(ref Message m)
   {
      if (m.Msg == (int)WindowMessage.WM_POWERBROADCAST)
      {
         if (m.WParam.ToInt32() == (int)PowerBroadcastType.PBT_POWERSETTINGCHANGE)
         {
            var ps = m.LParam.ToStructure<POWERBROADCAST_SETTING>();
            if (ps.PowerSetting == notGuid && ps.DataLength == 16)
            {
               var newSchemaGuid = new Guid(ps.Data);
            }
         }
      }
      base.WndProc(ref m);
   }
}
```

**Comment by dahall** [comment]
I completed work on `Vanara.Diagnostics.PowerManager` to add all power events. You can check out the code [there](https://github.com/dahall/Vanara/blob/master/System/PowerManager.cs) for a full example to your question.
