### ISSUE TITLE
SendMessage - ArgumentException: 'Object contains non-primitive or non-blittable data. Arg_ParamName_Name'

### ISSUE THREAD

**Issue by netcorefan1** [dahall/Vanara#191]
Hello,
I get the exception mentioned in the title when calling SendMessage (StringBuilder variant version).
```
var length = (int) SendMessage(hWnd, (uint) WindowMessage.WM_GETTEXTLENGTH);
if (length is 0) return null;
var sb = new StringBuilder(length + 1);
SendMessage(hWnd, WindowMessage.WM_GETTEXT, sb.Capacity, sb); // ArgumentException
```
The default pinvoke signature works as expected:
```
[DllImport("user32.dll", EntryPoint = "SendMessage", CharSet = CharSet.Auto)]
public static extern IntPtr SendMessageOriginal(IntPtr hWnd, int Msg, int wParam, StringBuilder lParam);

var length = (int) SendMessage(hWnd, (int) WindowMessage.WM_GETTEXTLENGTH);
if (length is 0) return null;
var sb = new StringBuilder(length + 1);
SendMessageOriginal(hWnd, WindowMessage.WM_GETTEXT, sb.Capacity, sb);
```
The exception is raised here:
 ```
public static IntPtr SendMessage<TEnum, TWP, TLP>(HWND hWnd, TEnum msg, TWP wParam, TLP lParam)
where TEnum : struct, IConvertible where TWP : struct, IConvertible where TLP : class
{
	using var lp = new PinnedObject(lParam); // ArgumentException
	return SendMessage(hWnd, Convert.ToUInt32(msg), new IntPtr(Convert.ToInt64(wParam)), lp);
});
```
Is there any particular reason for not using the default pinvoke signature? Did you used this also in other APIs other than User32?

Also, I noticed that even if I pass hWnd as IntPtr, it is automatically wrapped into HWND struct. A good amount of times we just deal with plain IntPtr and I am wondering in what measure could affect resources usage wrapping in classes and structs on every call. I am new to this library and I have yet to explore it, but seems to be that most of the functions are implemented in this way.
In order to save on memory allocations and avoid issues like in this thread, I would like to ask if would be possible to keep and expose the raw signatures. I could manually add overloads, but this would go against the whole purpose of Vanara.
Thanks

**Comment by dahall** [comment]
I'll look into the exception you're getting and push a fix today. I think the wrong generic method is getting selected.

I'm not sure what you mean by "expose raw signatures", but the rawest of signatures is usually exposed using the strong types (see below) of this library. In this case, the simplest signature for `SendMessage` is:
```cs
[DllImport("user32.dll", CharSet = CharSet.Auto)]
public static extern IntPtr SendMessage(HWND hWnd, uint Msg, IntPtr wParam, IntPtr lParam);
```

On you other point about `IntPtr` conversions. Early on I did some performance testing on this because I had the same concern. I wanted to strongly type handles so they couldn't be mis-used. Using `struct` based handles creates two CLI instructions and pushes the value to the stack for P-Invoke. So, there is a very small performance hit, but in testing hundreds of those allocations, the time was negligible and I felt it was worth the value of strong types.

**Comment by dahall** [comment]
I was correct. There are so many `SendMessage` overloads that the wrong one gets selected in your case. I also found an omission in overloads which I've added to simplify your use case. The function is:
```cs
[DllImport(Lib.User32, SetLastError = false, CharSet = CharSet.Auto)]
public static extern IntPtr SendMessage(HWND hWnd, uint msg, [In] IntPtr wParam, [In, Out] StringBuilder lParam);
```
The proper use of this new overload for your use case is:
```cs
SendMessage(hWnd, (uint)WindowMessage.WM_GETTEXT, (IntPtr)sb.Capacity, sb);
```
Notice the casts of `WindowMessage` to `uint` and `sb.Capacity` to `IntPtr`. These are critical to ensure the correct overload is chosen by the compiler.

The fix has been pushed and is available as a pre-release package from AppVeyor (see home page for details on using that NuGet repo). I'll push this release to NuGet.org within the next few days after completing some other work.

**Comment by netcorefan1** [comment]
Many thanks for your fast support. The latest I could find in pre-release is version 3.3.1, but I am sure that I just need to wait for the servers to update and I am sure that your fix will work.

Although this is strictly related, I am not sure if I should open a new thread. Feel free to do the required changes if needed.
For raw signatures I means exposing the closest C# equivalent of the native versions without wrapping arguments and returned data into classes or structs. In the specific case of SendMessage would mean keeping IntPtr instead of HWND which for each call create several members basically for nothing because the function only expects the IntPtr handle we got from another API call. In this case there's no risk to mis-use because there's no memory management to take care of from the managed side. You're signature still accept IntPtr, but under the hood creates an HWND.
I am not sure on the exact usage of "new PinnedObject(lParam);", but to me this seems to be another object allocation which does not happens when I call "SendMessageOriginal(IntPtr hWnd, int Msg, int wParam, StringBuilder lParam);"
It's good to know that your tests showed a very small performance it, but my main concern is the memory usage more than speed. What did found on this matter?
Right now I am working on a custom function which search for a specific window and add a custom control to it. I don't need to store anything in memory. I call your api with something like this:
```
public class TargetWindow
{
        public string ClassName
        {
            get
            {
                var sb = new StringBuilder(256);
                GetClassName(hWnd, sb, sb.Capacity);
                return sb.ToString();
            }
        }
        public string Title
        {
            get
            {
                var length = (int) SendMessage(hWnd, (uint) WindowMessage.WM_GETTEXTLENGTH);
                if (length is 0) return null;
                var sb = new StringBuilder(length + 1);
                SendMessage(hWnd, WindowMessage.WM_GETTEXT, sb.Capacity, sb);
                return sb.ToString();
            }
        }
        public IntPtr hWnd
        {
            get
            {
               return MyFunctionThatOriginatesTheHandle();
            }
        }
}
```
With the standard pinvoke signatures an instance like this will have very little impact on memory usage because it is an empty class which don't store any data (except the StringBuilder and other unavoidable temporary variables). But with you API, both GetClassName() and SendMessage() creates and store several members for nothing, just to pass an IntPtr.

I am talking about HWND because User32 is the first one Win32 API I started to deal with, but I am wondering if I will encounter the same in all the rest of Vanara API.
I think that the main approach for who decide to use Vanara (or at least for me) is the convenience of having all the pinvoke signatures available from a Nuget package. The custom handlers and wrappers are a bonus (and a great bonus) which should be left to the developer if to use or not. In this way it will be possible to avoid exceptions like the one I reported and have full control on resources.
Do you think would be possible to expose the closest native signatures and make the object wrappers optional?
I initially thought to create my own overloads thinking that it would have been required only for rare cases, but seems to be that Vanara is all implemented in this way and I am afraid I'll end up to rewrite everything just to have the original signature I would expect.
