### ISSUE TITLE
Suggestion: make the object wrappers optional and expose original pinvoke signatures to avoid allocations

### ISSUE THREAD

**Issue by netcorefan1** [dahall/Vanara#192]
Since the issue has been solved and closed, the closest option I could find is to open a new issue and reference the old one. Feel free to make the necessary changes if needed.

For raw signatures I means exposing the closest C# equivalent of the native versions without wrapping arguments and returned data into classes or structs. In the specific case of SendMessage would mean keeping IntPtr instead of HWND which for each call create several members basically for nothing because the function only expects the IntPtr handle we got from another API call. In this case there's no risk to mis-use because there's no memory management to take care of from the managed side. You're signature still accept IntPtr, but under the hood creates an HWND.
I am not sure on the exact usage of "new PinnedObject(lParam);", but to me this seems to be another object allocation which does not happens when I call "SendMessageOriginal(IntPtr hWnd, int Msg, int wParam, StringBuilder lParam);"
It's good to know that your tests showed a very small performance it, but my main concern is the memory usage more than speed. What did found on this matter?
Right now I am working on a custom function which search for a specific window and add a custom control to it. I don't need to store anything in memory. I call your api with something like this:
```
public class TargetWindow
{
        public string ClassName
        {
            get
            {
                var sb = new StringBuilder(256);
                GetClassName(hWnd, sb, sb.Capacity);
                return sb.ToString();
            }
        }
        public string Title
        {
            get
            {
                var length = (int) SendMessage(hWnd, (uint) WindowMessage.WM_GETTEXTLENGTH);
                if (length is 0) return null;
                var sb = new StringBuilder(length + 1);
                SendMessage(hWnd, WindowMessage.WM_GETTEXT, sb.Capacity, sb);
                return sb.ToString();
            }
        }
        public IntPtr hWnd
        {
            get
            {
               return MyFunctionThatOriginatesTheHandle();
            }
        }
}
```
With the standard pinvoke signatures an instance like this will have very little impact on memory usage because it is an empty class which don't store any data (except the StringBuilder and other unavoidable temporary variables). But with you API, both GetClassName() and SendMessage() creates and store several members for nothing, just to pass an IntPtr.

I am talking about HWND because User32 is the first one Win32 API I started to deal with, but I am wondering if I will encounter the same in all the rest of Vanara API.
I think that the main approach for who decide to use Vanara (or at least for me) is the convenience of having all the pinvoke signatures available from a Nuget package. The custom handlers and wrappers are a bonus (and a great bonus) which should be left to the developer if to use or not. In this way it will be possible to avoid exceptions like the one I reported and have full control on resources.
Do you think would be possible to expose the closest native signatures and make the object wrappers optional?
I initially thought to create my own overloads thinking that it would have been required only for rare cases, but seems to be that Vanara is all implemented in this way and I am afraid I'll end up to rewrite everything just to have the original signature I would expect.

_Originally posted by @netcorefan1 in https://github.com/dahall/Vanara/issues/191#issuecomment-753019074_

**Comment by dahall** [comment]
> For raw signatures I means exposing the closest C# equivalent of the native versions without wrapping arguments and returned data into classes or structs.

One of the key design principles in the library is type enforcement. In any case where PVOID or void* actually should represent a type, especially with handles, this library enforces the type. Casting from `IntPtr` to any of the handle wrappers (HWND, HGLOBAL, HPEN, etc.) does not create a new instance. Once optimized by the compiler, these two value types are the same size and have implicit operators that effectively inline that stack operation. Since I have almost a million lines of code following that principle, I'm disinclined to change it. Especially since it has almost no impact to speed or memory.

> In the specific case of SendMessage would mean keeping IntPtr instead of HWND which for each call create several members basically for nothing because the function only expects the IntPtr handle we got from another API call.

`IntPtr` automatically casts to `HWND` using the process above, so there is no penalty.

> my main concern is the memory usage

These are all value variables that get pushed on the stack during the marshal process. In optimized code, there is no memory hit.

> I am not sure on the exact usage of "new PinnedObject(lParam);", but to me this seems to be another object allocation which does not happens when I call "SendMessageOriginal(IntPtr hWnd, int Msg, int wParam, StringBuilder lParam);"

`PinnedObject` is a wrapper around `GC` methods to pin memory used by blittable structures to prepare for marshaling. In your use case, it will not get called if you target the method calls to use the method overload best suited for your task. In cases where it is necessary, it the most optimized way, other than using `unsafe` code, to marshal blittable structures.

> With the standard pinvoke signatures an instance like this will have very little impact on memory usage because it is an empty class which don't store any data (except the StringBuilder and other unavoidable temporary variables). But with you API, both GetClassName() and SendMessage() creates and store several members for nothing, just to pass an IntPtr.

Hopefully you see now that this is not the case. There is nothing stored when you use the right signature.

In your code, to call the best overload you need to change the signature of your second SendMessage call to:
```cs
SendMessage(hWnd, (uint)WindowMessage.WM_GETTEXT, (IntPtr)sb.Capacity, sb);
// (uint) casts WindowMessage so it doesn't pull one of generic methods
// (IntPtr) is needed since WPARAM is an IntPtr and not an Int32.
```

In many cases, casts like the above are critical, just like in native C, to ensure memory alignment, type enforcement, function selection, etc.

If you have further questions, feel free to respond to this thread.

**Comment by netcorefan1** [comment]
Many thanks for your detailed explanation. I am glad to see that my assumptions were totally wrong and that basically there are no differences. This is exactly what I was hoping to hear from you.
If I have understood well, this is what you recommend:
- When Vanara offers generic methods, it is always better to do the casting and use the non generic ones
- If a function expect a particular type, do the appropriate casting to ensure it get the expected type. Do not pass a different type just because it works and make code more readable

These rules are easy to follow when types are the built-in ones. But in case of Vanara custom ones how can I know when it is needed casting? For example, in the case of HWND, I know that I can safely pass IntPtr without doing "new HWND(IntPtrHandle)" because Vanara take care of the casting. I know this only because I have investigated and checked the source code. How can I know it is safe for other Vanara special types without checking every time the source code?

Many thanks for your tips about my sample code. Without your help I would have taken the wrong track due to the temptation of making the code shorter and more readable (and I wrongly believed this was the best practice!).
Do you recommend to change my "TargetWindow" class into a struct? Until I come to the result, I may need to temporarely implement some sort of tracking mechanism if GetClassName() does not returns a unique result on each instance (probably a string representing GetClassName()+CounterID.) I hope to avoid this by calling GetDlgCtrlID(), but if the ControlID will change dynamically, then I will be forced to do. I wanted to let you know to see if a struct could be still a good candidate even in this evenience.
Thanks

**Comment by dahall** [comment]
> When Vanara offers generic methods, it is always better to do the casting and use the non generic ones

I don't know that I agree with this. I implement generic methods when conversions or complexities are common when using the rawest function definition. There is usually some overhead, but it is the same overhead the developer would have to manually use to get the function to work.

I would instead say: Check all overloads for the one that most closely matches the pattern you desire and then ensure the parameters match that definition exactly. If the call is generic, make sure your parameter values match the generic conditions ("where ...") of the method.

> But in case of Vanara custom ones how can I know when it is needed casting?

Check the object for implicit and explicit operators. All handles do exactly the same conversions to/from IntPtr.

> Do you recommend to change my "TargetWindow" class into a struct?

Personally, I'd make extension methods for HWND.
```cs
public static string GetClassName(this HWND hWnd)
{
   var sb = new StringBuilder(256);
   var len = GetClassName(hWnd, sb, sb.Capacity);
   return len > 0 ? sb.ToString() : throw Win32Error.GetLastError().GetException();
}
```
If you need a unique id for a window, then class name plus the hex value of the HWND would be sufficient. That's not 100% guaranteed, but would be close.
```cs
public static string GetUID(this HWND hWnd)
{
   var sb = new StringBuilder(256);
   var len = GetClassName(hWnd, sb, sb.Capacity);
   return len > 0 ? $"{sb}+{(IntPtr)hWnd}" : throw Win32Error.GetLastError().GetException();
}
```

**Comment by dahall** [comment]
Would you mind if I extract portions of this thread and the last to put in the documentation for the project? Also, if I've answered all your questions, will you close this issue?

**Comment by netcorefan1** [comment]
Many thanks for your detailed explanations. Now it's everything clear! Feel free to reuse this or other threads to make the documentation better. The more the people are aware of such things the better is for all of us. Thanks
