### ISSUE TITLE
shellscalingapi.h

### ISSUE THREAD

**Issue by NiclasOlofsson** [dahall/Vanara#193]
Love your project. Saves so much time.

I would like to request support for the following API since I use some of it myself:

shellscalingapi.h https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/

**Comment by dahall** [comment]
Are there a few specific functions that would help you get started?

**Comment by dahall** [comment]
There were really only a few exported functions, so I did them all. It will be in the next release.
