### ISSUE TITLE
 Windows Remote Management 

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#194]
**Is your feature request related to a problem? Please describe.**
No pinvoke for WinRM

**Describe the additions or enhancements you'd like**
https://docs.microsoft.com/en-us/windows/win32/api/wsman/

**Previous work**
If work on these imports have been done, please provide links.

**Comment by dahall** [comment]
Are there a few specific functions that would help you get started?

**Comment by NN---** [comment]
I just paid attention that these functions are not present.

I guess it has to be started from basic functions like

WSManInitialize
WSManDeinitialize
WSManCreateSession
WSManCloseSession
WSManCreateShell
WSManCloseShell

**Comment by dahall** [comment]
This is done. Let me know if there more functions or interfaces that would be of use. It is only partially complete. I'll keep working on it based on interest and time.
