### ISSUE TITLE
ShellContextMenu doesn't provide some items such as "Scan with Microsoft Defender"

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#198]
**Describe the bug**
Lack some items for unknown reason

**What code is involved**
```csharp
ShellContextMenu.GetItems();
```

**Expected behavior**
Should provide all context menu items just like the menu in Windows Explorer

**Comment by dahall** [comment]
What extension are you viewing?

**Comment by zhuxb711** [comment]
A Folder, compare to the context menu in Windows Explorer, you will find some of the items missing

**Comment by dahall** [comment]
Does this help? https://stackoverflow.com/questions/63789282/different-shell-context-menu-versus-windows-explorer-context-menu

**Comment by zhuxb711** [comment]
No, because "Scan with Microsoft Defender" is not a submenu item. We should find it in the context menu directly.

**Comment by dahall** [comment]
The entire "context menu" is a submenu. Do you have a means of seeing window messages to determine if other items are getting inserted that way as the article suggests?

**Comment by dahall** [comment]
Also, have you tried passing different combinations of the `CMF` enum to `GetItems`?

**Comment by dahall** [comment]
Which method of `ShellContextMenu` are you using to get or display the menu?

**Comment by zhuxb711** [comment]
Yes I tried different CMF but helpless.
I use GetItems() to get the context menu and just get the info from it. I will display context menu on my own flyout.

**Comment by dahall** [comment]
A few interesting notes:
1. Build the DLL as x64 and you will get different menu items
2. Use `CMF_EXPLORER | CMF_CANRENAME | CMF_EXTENDEDVERBS` for the most complete list.

Let me know your findings with those helps.

**Comment by zhuxb711** [comment]
Interesting.
But we still get part of the context menu item, not all of them.

**Comment by dahall** [comment]
From my reading, I believe there are menu items that Explorer manually inserts from the ProgID which are not incorporated via the calls with IContextMenu.

**Comment by dahall** [comment]
From what I understand, you need to open the ProgId in the registry, go to the `shellex\ContextMenuHandlers` key and the create each CLSID referenced and then query it's IContextMenu for additional menu items. I have found no information on how to insert them into the correct places in the menu.

**Comment by dahall** [comment]
If you find a way to get the full menu, please send me details and I'll work on incorporating them or make the changes and submit a PR.

**Comment by dahall** [comment]
It appears, looking at a registry trace while loading a context menu for a folder in Explorer, that it enumerates the entries in HKCR\Software\Classes\Directory\background\shellex\ContextMenuHandlers and the opens the PROGID for each handler and then opens the file (I assume for reading its IContextMenu). What I can't tell is order. I would try an experiment of passing the HMENU that comes from the IShellFolder based query and passing it to one of your special handlers to see if they put their menu item into the menu. Whichever of us gets to it first, let's post our findings here.

**Comment by zhuxb711** [comment]
I found that if we need to fetch all menus, we should fetch it in STA thread with 
```csharp
Shell32.CMF.CMF_NORMAL | Shell32.CMF.CMF_SYNCCASCADEMENU
```

**Comment by dahall** [comment]
Cool. Can we close this issue then? I'll put these instructions in the help for the GetItems method.

**Comment by zhuxb711** [comment]
Yes I will close it

**Comment by dahall** [comment]
So, for the documentation, you gave me the two enum values and the STA thread requirement. Were there other CMF values? Also, are you running as x86, x64 or Any CPU?

**Comment by zhuxb711** [comment]
For extra items use CMF_EXTENDEDVERBS. My program run as X64. But I think it should be work on other. The key point is STA thread
