### ISSUE TITLE
How to read data from SafeHGlobalHandle buffer 

### ISSUE THREAD

**Issue by Pardeep212** [dahall/Vanara#199]
Hi All,

I need your help.
I am using Vanara.PInvoke.WinINet to send request to server and reading the response back. Using the functions, i am successfully able to connected to my server,  sent the request and got the response. 
Now i have the response in mem(object of SafeHGlobalHandle class) i guess, as in the last parameter of function 
InternetReadFile(hReq, mem, mem.Size, out var read), i got the the bytes returned.

Here I want to know, how i can get the data from the buffer(mem) to string variable to process further?

Thanks..

**Comment by dahall** [comment]
There are a number of methods on `SafeCoTaskMemHandle` that allow you to extract different types from the memory starting with `To..`. The one I think you might need is [`ToString(int len, CharSet charSet)`](https://github.com/dahall/Vanara/blob/4a55c16fee633db8d4ecaeb7f1940653b1cc5a15/Core/InteropServices/SafeMemoryHandle.cs#L547). If it is a null-terminated string, you can pass `-1` as `len` and it will find the full string. Make sure to specify a character set if it is not Unicode.

**Comment by Pardeep212** [comment]
Hi David, 
Thanks for your response and sorry to ask for your help again as i am new to C# programming specially when need to do out of the box tasks.
Let me explain what i actually needed. I am creating a function which send requests to a server (FTP/HTTP). The request type can be either GET or Post.  So the function actually send request to server and get response from it in the form of string. Following is my function code file attached.
[SendRequestToServer Function.txt](https://github.com/dahall/Vanara/files/5873355/SendRequestToServer.Function.txt)
 
i believe the changes should be at lines 157-159 (in order to send extra data in  WinINet.HttpSendRequest() method) with post request and at line 174 to fetch response from buffer. 

i will be very thankful of you if you correct these line to make the function in working mode. Believe me it will make my day. 
Thanks in advance. Have a good day.

**Comment by dahall** [comment]
If you are new to C#, I would __strongly__ suggest you use the `System.Net` classes (see https://docs.microsoft.com/en-us/dotnet/framework/network-programming/how-to-upload-files-with-ftp).

**Comment by Pardeep212** [comment]
I can't because, i have to convert the same code from VBA to C#. Its working well in VBA. 
I would be more than happy if you please have a look in the text file i attached. Thanks

**Comment by dahall** [comment]
I'd rewrite those lines as follows:
```cs
using var strPtr = new SafeCoTaskMemString(lpszPostData, CharSet.Auto);
bRet = WinINet.HttpSendRequest(hHttpOpenRequest, "", 0, strPtr, strPtr.Size);  //Need To Be Changed In Case of Post Request.
// Not Used: a = Marshal.GetLastWin32Error();

if (bRet == false)
	returnStr = "NoNET";
else
{
	sBuffer = "";
	bDoLoop = true;
	using var sReadBuffer = new SafeCoTaskMemHandle(2048);						
	while (bDoLoop)
	{								  
		bDoLoop = WinINet.InternetReadFile(hHttpOpenRequest, sReadBuffer, sReadBuffer.Size, out var lNumberOfBytesRead);
		// Not Used: a = Marshal.GetLastWin32Error();
		if (bDoLoop && lNumberOfBytesRead > 0)
			sBuffer += sReadBuffer.ToString(lNumberOfBytesRead / StringHelper.GetCharSize(), CharSet.Auto);
		else
			bDoLoop = false;
	}
	returnStr = sBuffer;
}
```
