### ISSUE TITLE
DwmSetWindowAttribute error

### ISSUE THREAD

**Issue by xjfnet** [dahall/Vanara#2]
DwmSetWindowAttribute DWMWA_NCRENDERING_POLICY DWMNCRENDERINGPOLICY cause exception

**Comment by dahall** [comment]
What exception? Are you calling the function
`HRESULT DwmSetWindowAttribute(IntPtr hwnd, DWMWINDOWATTRIBUTE dwAttribute, [In] IntPtr pvAttribute, int cbAttribute)`
OR
`HRESULT DwmSetWindowAttribute<T>(IntPtr hwnd, DWMWINDOWATTRIBUTE dwAttribute, [In] T pvAttribute)`

**Comment by dahall** [comment]
Thanks for the catch. Turns out the same bug shows up for `DwmSetWindowAttribute` too. I've corrected both in source and will publish in next build (1.0.7).
