### ISSUE TITLE
Improving constraint for BitHelper

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#20]
```cs
public static bool GetBit<T>(T bits, byte idx) where T : IConvertible
```

Just wondering, did you want to specify T : unmanaged perhaps ?
Check here:
https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/constraints-on-type-parameters
https://blogs.msdn.microsoft.com/seteplia/2018/06/12/dissecting-new-generics-constraints-in-c-7-3/

**Comment by dahall** [comment]
Thanks for bringing this to my attention. I hadn't seen this yet. I'll look to implement in the next release along with all the handle changes. If you have time to do a PR for this, I'd be very appreciative.

**Comment by NN---** [comment]
Did you use IConvertible in other places where thr meaning was unmanaged constraint ?

**Comment by dahall** [comment]
I tried to follow the pattern using `struct, IConvertible` constraints whenever specifying `enum` or number types. I used the `struct` constraint and exceptions when looking for blittable types.

**Comment by dahall** [comment]
In this particular BitHelper extension, I was attempting to constrain to the set of items that could be converted to a number.

**Comment by NN---** [comment]
So BitHelper definitely should use unmanaged to cover all blittable types.
As for enum there is Enum constraint in C# 7.3 and interesting workaround in older version.

https://stackoverflow.com/a/28527552

**Comment by NN---** [comment]
Actually if I understand correctly BitHelper is intended for types smaller or equal than Int64 ?

Is it correct ?
If yes, then a correct answer is to just have overloads for all primitive types and not using IConvertible.
In case you say it is too much code to write, just use T4.
See how CodeJam uses it to generate all required overloads: https://github.com/rsdn/CodeJam/blob/master/Main/src/Algorithms/Algorithms.EqualRange.tt

**Comment by NN---** [comment]
There is also possible NRE since you can pass null in 'bits' parameter.

**Comment by dahall** [comment]
To simplify and _help_ make more foolproof, I have extended the list of constraints to `struct, IComparable, IComparable<T>, IConvertible, IEquatable<T>, IFormattable` in 2.0. Not perfect, but better.
