### ISSUE TITLE
Error NETSDK1136: The target platform must be set to Windows (User32 only)

### ISSUE THREAD

**Issue by netcorefan1** [dahall/Vanara#200]
**Describe the bug**
After I upgraded Vanara.PInvoke.User32 from 3.3.0 to 3.3.2 (or any other version above 3.3.0) I get the error described in the title.

**What code is involved**
.Net 5 (default VS .Net Core library project). This only happens with Vanara.PInvoke.User32. It doesn't with  Vanara.PInvoke.Kernel32 (didn't tried other packages)

**Expected behavior**
No window runtime dependency, just like 3.3.0.

**Comment by dahall** [comment]
Thanks for bringing this to my attention. I have resolved it in the latest commit for 3.3.3. It will release in the next few days.

**Comment by netcorefan1** [comment]
@dahall You're amazing! As always!
