### ISSUE TITLE
Vanara.PInvoke.User32.EndDialog thrown System.AccessViolationException

### ISSUE THREAD

**Issue by zy97** [dahall/Vanara#201]
**Describe the bug**
i have an application,it will show a dialog,i get the hwnd of the dialog,then i use EndDialog but it throw an AccessViolationException

**What code is involved**
Vanara.PInvoke.User32.EndDialog(hwnd,intprt.zero)

**Expected behavior**
the dialog will close

**Screenshots**

**Comment by dahall** [comment]
What function are you using to create the dialog? I've seen this happen when the creation returns a SafeHandle derivative that already destroys the handle.

**Comment by zy97** [comment]
the dialog is other application‘s ，sush as c# MessageBox.Show ，window system created

**Comment by dahall** [comment]
I've checked the syntax against other repositories and the native declaration. It is correct. My guess is that it is a dialog whose message pump does not handle `EndDialog` gracefully. I've seen this with property pages and other modeless dialogs.

**Comment by zy97** [comment]
thx
