### ISSUE TITLE
Extension function ToBitmap() flip the bitmap after last commit

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#202]
**Describe the bug**
I think it might be cause by this line:
https://github.com/dahall/Vanara/blob/1608010064a59c5dca107b5a117bd900d4dde77f/PInvoke/Gdi32/GdiObjExtensions.cs#L95

Now I got flip Bitmap. And it is very strange.

**What code is involved**
```csharp
//BitmapHandle is HBITMAP
BitmapHandle.ToBitmap();
```

**Expected behavior**
Do not flip

**Screenshots**
![image](https://user-images.githubusercontent.com/42038175/106120668-9bfaf700-6191-11eb-953c-28bafaa6bf09.png)

**Comment by dahall** [comment]
I reverted back to the old code so it works again. I'd tried to add code to support transparency and lesser bpp formats, but failed.
