### ISSUE TITLE
Value does not fall within the expected range.

### ISSUE THREAD

**Issue by GF-Huang** [dahall/Vanara#203]
What happen?

![image](https://user-images.githubusercontent.com/4510984/106266953-fb293c00-6263-11eb-9b98-79c906bb567b.png)

**Comment by hellojayjay** [comment]
> What happen?
> 
> ![image](https://user-images.githubusercontent.com/4510984/106266953-fb293c00-6263-11eb-9b98-79c906bb567b.png)

Have resolve it?

**Comment by dahall** [comment]
Please read the documentation for that function. You have to supply a valid HINTERNET handle.

**Comment by hellojayjay** [comment]
```
        private static void TransferData(CF_CONNECTION_KEY connectionKey, CF_TRANSFER_KEY transferKey, IntPtr transferData, long startingOffset, long length, NTStatus completionStatus)
        {
            var opInfo = new CF_OPERATION_INFO
            {
                StructSize = (uint)Marshal.SizeOf<CF_OPERATION_INFO>(),
                Type = CF_OPERATION_TYPE.CF_OPERATION_TYPE_RESTART_HYDRATION,
                ConnectionKey = connectionKey,
                TransferKey = transferKey
            };
            var opParams = new CF_OPERATION_PARAMETERS
            {
                ParamSize = (uint)Marshal.SizeOf<CF_OPERATION_PARAMETERS.TRANSFERDATA>(),
                TransferData = new CF_OPERATION_PARAMETERS.TRANSFERDATA
                {
                    CompletionStatus = completionStatus,
                    Buffer = transferData,
                    Offset = startingOffset,
                    Length = length
                }
            };

            CfExecute(opInfo, ref opParams).ThrowIfFailed();
        }
```

```CfExecute(opInfo, ref opParams).ThrowIfFailed(); ``` throw the exception above. What may be the problem?

**Comment by dahall** [comment]
That exception translates to E_INVALIDARG, which is a very common error code for API calls. It almost always means that there is a problem with one of the arguments. I would go back and check those two structures you're passing into the function.
