### ISSUE TITLE
MiniDumpWriteDump is not defined

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#204]
**Is your feature request related to a problem? Please describe.**
https://docs.microsoft.com/en-us/windows/win32/api/minidumpapiset/nf-minidumpapiset-minidumpwritedump

**Previous work**
https://www.pinvoke.net/default.aspx/dbghelp/MiniDumpWriteDump.html

**Comment by dahall** [comment]
Working on it. It is pretty messy. Lots of things that don't translate well into C#.

**Comment by NN---** [comment]
I have a working declaration if you need any help.

**Comment by NN---** [comment]
Pay attention that MINIDUMP_EXCEPTION_INFORMATION structure has packing of 4 and not 8 :)

**Comment by dahall** [comment]
@NN--- I have some working code, but would appreciate comparing to yours before I release.

**Comment by dahall** [comment]
I just pushed my commit of the work. Please check against your working definitions and let me know where there are differences.

**Comment by dahall** [comment]
If you have code you can test against the definition, there is a 3.3.3 build on AppVeyor's NuGet feed (see homepage) you can use.

**Comment by NN---** [comment]
Seems like everything is good.
The only issue is the test :)

**Comment by dahall** [comment]
Thanks for the help. It is all now implemented and somewhat tested. I'll release it shortly in 3.3.3.
