### ISSUE TITLE
ShellContextMenu will threw ArgumentException if we give Desktop path to it

### ISSUE THREAD

**Issue by talenthe** [dahall/Vanara#206]
**Describe the bug**
Threw ArgumentException

**What code is involved**
```csharp
//Path is the path of Desktop
using (ShellItem Item = ShellItem.Open(Path))
using (ShellContextMenu ContextMenu = new ShellContextMenu(Item))
{
       //Do something
}
```

**Expected behavior**

**Screenshots**

**Comment by dahall** [comment]
Thanks. Fixed for 3.3.4. Check temp build on AppVeyor (see home page) for early testing.
