### ISSUE TITLE
ShellContextMenu will throw System.Runtime.InteropServices.InvalidComObjectException

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#208]
**Describe the bug**
![image](https://user-images.githubusercontent.com/42038175/107143123-3ca99d80-696e-11eb-84cc-541621af5b1e.png)

I think this is caused by ShellFolder.Desktop
![image](https://user-images.githubusercontent.com/42038175/107143154-606ce380-696e-11eb-93d7-d8af1c1e80a3.png)

**What code is involved**
Make sure the code in invoke from STA thread. 
Call run STA thread for 2-3 times.
```csharp
using (ShellItem Item = ShellItem.Open(Path))
using (ShellContextMenu ContextMenu = new ShellContextMenu(Item))
{
        //Dosomething
}
```

**Expected behavior**
Should not threw exception

**Comment by dahall** [comment]
I think this is fixed in my latest commit. I am able to run that snippet you provided 20 times without any exceptions.
