### ISSUE TITLE
Add IContextCallback

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#209]
https://docs.microsoft.com/en-us/windows/win32/api/ctxtcall/nn-ctxtcall-icontextcallback
https://doxygen.reactos.org/d2/d40/ctxtcall_8idl_source.html
https://github.com/microsoft/CsWinRT/blob/cfbc973fd48453d53311706a3f4a9b8730c762c6/src/WinRT.Runtime/Interop/IContextCallback.cs#L11

```cs
    struct ComCallData
    {
        public int dwDispid;
        public int dwReserved;
        public IntPtr pUserDefined;
    }

    delegate int PFNCONTEXTCALL(in ComCallData data);

    [Guid("000001da-0000-0000-C000-000000000046")]
    interface IContextCallback
    {
        // pUnk must be zero
        void ContextCallback(
            PFNCONTEXTCALL pfnCallback,
            in ComCallData pParam,
            in Guid riid,
            int iMethod,
            IntPtr pUnk);
    }
```

**Comment by dahall** [comment]
I've added this to the Ole.Ole32 class

**Comment by NN---** [comment]
Sorry to bother forgot to mention CLSID_ContextSwitcher as well.

See usage sample https://docs.microsoft.com/en-us/windows/win32/api/combaseapi/nf-combaseapi-codisconnectcontext

**Comment by dahall** [comment]
Ah, I thought I'd set a record for closing an issue in 25 minutes. I can't find an actual GUID for that CLSID. The header file has it specified as `extern`. Do you know what it is?

**Comment by NN---** [comment]
Don’t get it wrong . You did everything in the best way:)
It is my fault.
I’ll add PR tomorrow with the CLSID.
Where is the right place to put it in?
Ole32 class?

**Comment by dahall** [comment]
Please add it to the file `PInvoke/Ole/Ole32/CtxtCall.cs`. Please add it near the top as
```cs
/// <summary>CLSID_ContextSwitcher</summary>
public static readonly Guid CLSID_ContextSwitcher = new Guid("xxx-xx-xxx...");
```
