### ISSUE TITLE
Target Framework Moniker is required on some packages

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#210]
**Describe the bug**
Vanara.PInvoke.Kernel32, Vanara.PInvoke.IpHlpApi packages don't require target framework moniker: net5.0-windows
However Vanara.PInvoke.Gdi32, Vanara.PInvoke.Ole32 do require specifying TFM and changing project target to net5.0-windows.

**Expected behavior**
Consistency between packages.
Either all or none of them require TFM.

**Comment by dahall** [comment]
See #207. It is actually on all the projects. However, the compiler only complains when the <UseWinForms> or <UseWPF> tags are included in the project.

**Comment by dahall** [comment]
If I add those tags to projects that don't need them, then it pulls down a bunch of unnecessary dependencies for those projects.

**Comment by dahall** [comment]
@NN---  Given my notes above, what are your thoughts?

**Comment by NN---** [comment]
I see. What if you remove UseWinForms and add references manually ? Does it solve it ?

**Comment by dahall** [comment]
It doesn't. Microsoft has changed the build model under net5.0 so that when you need winforms or wpf, it automatically chooses the correct assemblies based on those tags. The tags also affect capabilities within Visual Studio. My understanding is that it is preparation for WinUI 3.0 capabilities.

**Comment by NN---** [comment]
I understand.
The only thing that makes it less obvious is that I have tests divided between net5.0 and net5.0-windows.
Seems like it is easier for me to make all my projects net5.0-windows cause the project is totally for Windows anyway.

**Comment by dahall** [comment]
That's exactly where I ended up.

**Comment by NN---** [comment]
Seems like adding Windows TFM adds bunch of unused dlls.
I just needed a single PInvoke and it adds about 60MB of dlls.
Seems like trimming doesn't work well here, so instead of 20MB executable I get 60.

**Comment by NN---** [comment]
The dependency is Ole->Gdi32->UseWindowsForms.
