### ISSUE TITLE
Add assembly for methods in cfgmgr32.dll.

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#222]
**Describe the bug**
No CM_....... function in SetupAPI class.

**Expected behavior**
SetupAPI should include the function like:
CM_Request_Device_Eject()
CM_Get_Parent()

They are in cfgmgr32.h but we could use it by using
```csharp
[DllImport("setupapi.dll", CharSet = CharSet.Unicode)]
 private static extern int CM_Request_Device_Eject(
            uint dnDevInst,
            out PNP_VETO_TYPE pVetoType,
            StringBuilder pszVetoName,
            int ulNameLength,
            int ulFlags);
```

**Comment by dahall** [comment]
I found very little online referencing these functions so I ignored them. Have you found practical uses for them?

**Comment by zhuxb711** [comment]
[Check here](https://github.com/zhuxb711/RX-Explorer/blob/5162c8033e88848ac390fa8309beab497c8b57d8/FullTrustProcess/USBController.cs#L223)

I use them to Eject the USB device. But I don't have too much article about cfgmgr32.h

**Comment by dahall** [comment]
Doing a little more checking, those methods are only referenced in SetupApi.dll. They are declared and defined in CfgMgr32.dll. I'll put it on the list of assemblies to create. I'm going to change the title to reflect the change.

**Comment by dahall** [comment]
Out on AppVeyor is a pre-release for the CfgMgr32 assembly with all the documented methods and some helper functions and classes as well. Maybe some will be of use to you.
