### ISSUE TITLE
SendInput not working as expected in .NET Core project

### ISSUE THREAD

**Issue by sunny-lan** [dahall/Vanara#223]
**Describe the bug**
In a .NET Core project, SendInput for a Keyboard Event does nothing

**What code is involved**

Versions:
- Vanara.User32: 3.3.8
- Target: net5.0-windows

Reproduce steps:
- Call `User32.SendInput` with a keyboard down event to press 'm'

**Expected behavior**
The key 'm' is pressed.

**Comment by dahall** [comment]
Can I guess that it is 64-bit? I made an assumption on the INPUT structure offset of the union that I'm guessing doesn't align.
