### ISSUE TITLE
ExplorerBrowser throws ArgumentNullException in Designer

### ISSUE THREAD

**Issue by tajbender** [dahall/Vanara#225]
**Describe the bug**
ExplorerBrowser throws ArgumentNullException when a new instance is dropped in Designer, cause in Design-Mode there is no ExplorerBrowser-Instance that has been created. That's why `GetFolderView2()` fails.

**What code is involved**
`Windows.Forms/Controls/ExplorerBrowser.cs` -> `get_ThumbnailSize()`

**Expected behavior**
See the attached Patch-File. Using that would fix the Issue, but please take a look if it's exactly the behavior you intended. Using this (quick-fix) solved the problem for me:

[21-04-22 ExplorerBrowser Designer-ThumbnailSize.zip](https://github.com/dahall/Vanara/files/6358698/21-04-22.ExplorerBrowser.Designer-ThumbnailSize.zip)

**Screenshots**
![ExplorerBrowser - ThumbnailSize](https://user-images.githubusercontent.com/10961499/115723798-9ff97800-a380-11eb-9445-69a80ca7533b.png)

**Comment by tajbender** [comment]
Sorry, wait a moment... This doesn't fix the problem in `ExplorerBrowserTestForm` cause of the `PropertyGrid`.

**Comment by dahall** [comment]
Finally got this fixed. Sorry for the delay.
