### ISSUE TITLE
Allow abort in ShellFileOperations

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#227]
**Is your feature request related to a problem? Please describe.**
For the time being, we could not abort the opration in ShellFileOperations

**Describe the additions or enhancements you'd like**
Provide an easy way to abort

**Previous work**
[I think this might help you
](https://github.com/electron/electron/blob/25f5c01cecab349ab687ed70199b64b5264a2cb8/shell/common/platform_util_win.cc#L110)

It returns a "E_ABORT" to stop the operation

**Comment by dahall** [comment]
In any operation? If just one of them (copy, move, delete, etc.), please let me know.

**Comment by dahall** [comment]
Are you using the queueing model (e.g. QueueCopyOperation + PerformOperations) or the methods (e.g. Copy, Delete, ...)?

**Comment by dahall** [comment]
If that code you referenced works, then you should be able to duplicate that behavior in the existing code. All of the event handlers look for exceptions and process any embedded `HRESULT` values. To return `E_ABORT`, then just throw a `System.Runtime.InteropServices.COMException` with that error code.

The code below mimics that of the sample you sent:
```cs
shellOp.PreDeleteItem += (s, e) => {
   if (!e.Flags.IsFlagSet(TransferFlags.DeleteRecycleIfPossible))
      throw new System.Runtime.InteropServices.COMException(null, HRESULT.E_ABORT);
};
```

**Comment by dahall** [comment]
Doing a little more research, you can actually throw a `COMException` with any `HRESULT` value to abort. When the operation completes, you can check the `AnyOperationsAborted` property to see if any operations were aborted.

**Comment by dahall** [comment]
I've looked at the current implementation and cannot find a way to do this with a method call that results in deterministic behavior. The problem stems from calling a method during thread execution that is attempting to abort out-of-line operations on that same thread. If called within an event handler, you will end up with different timing than if called outside those handlers.

You're welcome to look at the code and suggest ways that fit the model you're conceptualizing or even submit a PR.
