### ISSUE TITLE
GetModuleInformation throws EntryPointNotFoundException

### ISSUE THREAD

**Issue by IllidanS4** [dahall/Vanara#230]
**Describe the bug**
```
System.EntryPointNotFoundException: Unable to find an entry point named 'GetModuleInformation' in DLL 'kernelbase.dll'.
   at Vanara.PInvoke.Kernel32.GetModuleInformation(HPROCESS hProcess, HINSTANCE
hModule, MODULEINFO& lpmodinfo, UInt32 cb)
```
Tested on Windows 7, 64-bit.

**What code is involved**
`Vanara.PInvoke.Kernel32.GetModuleInformation`

**Expected behavior**
I haven't tested other psapi functions, but this was the only P/Invoke declaration that worked for me:
```cs
[DllImport(Lib.Kernel32, SetLastError = true, ExactSpelling = true, EntryPoint = "K32GetModuleInformation")]
[return: MarshalAs(UnmanagedType.Bool)]
static extern bool GetModuleInformation(HPROCESS hProcess, HINSTANCE hModule, out MODULEINFO lpmodinfo, uint cb);
```
It is not in KernelBase, and must used the entry point "K32GetModuleInformation". It is also consistent with the [documentation](https://docs.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getmoduleinformation):

> Programs that must run on earlier versions of Windows as well as Windows 7 and later versions should always call this function as K32GetModuleInformation.

**Comment by dahall** [comment]
Thanks for bringing this to my attention. After some research and testing, it appears that importing from PSAPI.DLL allows the functions to work on all Windows versions (at least Vista - 10). I'll get the fixes pushed shortly and then they'll show up in the next released build.
