### ISSUE TITLE
FDICopy is incorrectly declared

### ISSUE THREAD

**Issue by IllidanS4** [dahall/Vanara#232]
**Describe the bug**
`FDICopy` inside the Cabinet declarations is not working right now, as the `PFNFDINOTIFY` does not correspond to what Windows accepts.

**What code is involved**
Fdi.cs, `FDICopy` and `PFNFDINOTIFY`.

**Expected behavior**
The function expects two pointers, `PFNFDINOTIFY` and `PFNFDIDECRYPT`. As can be seen [here](https://source.winehq.org/WineAPI/FDICopy.html), the declaration of the first pointer should actually be something like this:
```cs
public delegate IntPtr PFNFDINOTIFY(int fdint, ref FDINOTIFICATION pfdin);
```
(the first parameter could be an enum `FDINOTIFICATIONTYPE`).

Right now, `PFNFDINOTIFY` is actually declared to match `PFNFDIDECRYPT` which is not named anywhere in Fdi.cs except the docs. Together, the rest should look like this:
```cs
public delegate int PFNFDIDECRYPT(ref FDIDECRYPT pfdid);

[DllImport("cabinet.dll", SetLastError = false, ExactSpelling = true, CharSet = CharSet.Ansi)]
public static extern bool FDICopy(HFDI hfdi, string pszCabinet, string pszCabPath, int flags, PFNFDINOTIFY pfnfdin, PFNFDIDECRYPT pfnfdid, IntPtr pvUser);
```

**Edit:**
More issues have cropped up as I tried to use the API, so I have added them as separate comments. Frankly, I am not surprised there are so many of them, as cabinet.dll is like nothing I have ever seen in WinAPI before.

**Comment by IllidanS4** [comment]
And, actually, the `long` members that contain the cabinet size should be `int` (or `uint` perhaps), both `FDICABINETINFO.cbCabinet` and `FDINOTIFICATION.cb`.

Another minor nuisance: all the `HFILE` occurences should really be just `IntPtr`, since it is meant to be used as an opaque pointer controlled solely through `HFDI`. Underneath it could be `HFILE`, file descriptor, string, GCHandle or whatever; the implementation does not care.

I will probably discover more things to report as I go through the library.

**Comment by IllidanS4** [comment]
Last issue I guess: `FDINOTIFICATION.psz2` is declared as string, but in case of `fdintNEXT_CABINET`, the field is actually the file handle (`HFILE` or `IntPtr`).

**Comment by IllidanS4** [comment]
Another observation: `ERF` is not blittable (because it contains a `bool` field) so it must be always marshalled, however `FDICreate` assumes the pointer will be available even *after* the context is created, which it of course isn't (as .NET has to provide a temporary variable before calling `FDICreate` expecting it to be filled by the function).

Simply changing the `bool` to `int` should work, however I am not really sure if that is the best way to handle that. It would work to me, but could be quite confusing to people who would reasonably expect the usual behaviour of `out` parameters. I could imagine another overload that allocates 12 bytes for `ERF`, passes that to `FDICreate` and stores it alongside the result in `SafeHFDI` (or some new class) since, after the `HFDI` cannot outlive the `ERF`.

Another possibility is to create a *class*:
```cs
[StructLayout(LayoutKind.Sequential)]
public class PERF
{
    public ERF Value;
}
```
`FDICreate` would then take this object, allocate a pinned `GCHandle` to it and pass the pinned pointer to the inner `FDICreate`. Again, the object is only allowed to be unpinned after `FDIDestroy`.

**Comment by dahall** [comment]
@IllidanS4 I think I've addressed all your issues and then fixed a few other things while in there.
1. Implemented PFNFDINOTIFY as requested along with enum type for first param
2. Changed incorrect `long` fields to `int` and all `HFILE` references to `IntPtr`
3. Changed `FDINOTIFICATION.psz2` to an `IntPtr`. Please let me know if your testing shows I need to attribute all delegates to explicitly be called as `__cdecl`.
4. All methods taking `ERF` now require a `ref` instance and the marshaled `bool` field now uses `BOOL` -- a blittable structure defined in my lib that auto converts to `bool` in use.

**Comment by dahall** [comment]
I've made lots of further changes and think it is near complete. If you have a framework within which you can fully test it, I'd appreciate the validation. Check out the NuGet feed on AppVeyor to get the 3.3.10 pre-build (instructions on home page).

**Comment by IllidanS4** [comment]
Thanks for the update! Unfortunately the reading does not work at the moment, as the `[In]`/`[Out]` attributes are not correctly set on the delegates now. `PFNREAD` should be only `[Out]` and `PFNWRITE` should be only `[In]`.

Personally however, I have preferred the `IntPtr` versions. I intend to run a lot of in-memory extractions using the library and I can provide my own buffers or copy the bytes directly from memory. Not sure if .NET is able to reuse the arrays, but I would prefer to have full control of that. Not sure how to best solve this thing, but if possible, an overload could work.

**Comment by dahall** [comment]
Would the following declarations work:
```cs
public delegate uint PFNREAD(IntPtr hf, [Out] IntPtr memory, uint cb);

public delegate uint PFNWRITE(IntPtr hf, [In] IntPtr memory, uint cb);
```

**Comment by IllidanS4** [comment]
> Would the following declarations work:
> 
> ```cs
> public delegate uint PFNREAD(IntPtr hf, [Out] IntPtr memory, uint cb);
> 
> public delegate uint PFNWRITE(IntPtr hf, [In] IntPtr memory, uint cb);
> ```

Sure, but .NET doesn't care much about `[In]`/`[Out]` on `IntPtr` parameters (I suppose).

**Comment by dahall** [comment]
I put those attributes there more for the developer. I'll push these updates then. Please retest if you can.

**Comment by IllidanS4** [comment]
@dahall Yes, it seems to be nicely working now.

**Comment by dahall** [comment]
Thanks for validating it. I'll get it pushed shortly.

**Comment by IllidanS4** [comment]
For some reason, `FDINOTIFICATION.psz2` didn't really contain the pointer I expected there in case of `fdintNEXT_CABINET`, only something that seemed like an empty string. I know .NET couldn't mess that up as it's just `IntPtr` now, so it seems something in the implementation (or documentation) is wrong.

It's not a deal breaker for me; just something worth pointing out if others get the same issue. Frankly the only workaround I could imagine would be to encode each stream pointer in base64 and pass it around like a string, so it will at least get correctly converted (assuming this is what went wrong) to what the caller expected.

Having tested the library on more archives in the meantime, I'd say other things work great however!

**Comment by dahall** [comment]
Does the `psz2` field value not equal the handle you returned from `fdintCOPY_FILE`? I would surprise me, given the simple layout of those first fields in `FDINOTIFICATION1` if alignment was a problem. I'm not sure if you're using any of Vanara's SafeXX.. handle classes. If you are, the return value from `fdintCOPY_FILE` may need to be the extracted handle value from the SafeXX handle. For example:
```cs
SafeHFILE hfile = CreateFile(...);
return hfile.ReleaseOwnership();
```
The above prevents `SafeHFILE` from automatically closing the handle on disposal.

**Comment by IllidanS4** [comment]
Yeah it surprised me too. I used GCHandles actually and .NET was quick to warn me when something went wrong there. It's not an alignment issue, as the structure is fine otherwise, but the pointer is definitely not something returned from `fdintCOPY_FILE`.
