### ISSUE TITLE
Using GetDpiForMonitor in .NET Core/.NET 5 will throw an EntryPointNotFoundException

### ISSUE THREAD

**Issue by XuanchenLin** [dahall/Vanara#235]
**Describe the bug**
Using GetDpiForMonitor in .NET Core/.NET 5 will throw an EntryPointNotFoundException, but in .NET Framework it is correct.

There is my code:

```C#
var hMonitor = MonitorFromWindow(handle, MonitorFlags.MONITOR_DEFAULTTONEAREST);
GetDpiForMonitor(hMonitor, MONITOR_DPI_TYPE.MDT_EFFECTIVE_DPI, out var dpiX, out _);
```

I try to use this api directly and change the string "SHCore.dll" to "Shcore.dll", and it will be ok in ether .NET Core/5 or .NET Framework.
```C#
[DllImport("Shcore.dll", ExactSpelling = true)]
[PInvokeData("shellscalingapi.h", MSDNShortId = "NF:shellscalingapi.GetDpiForMonitor")]
private static extern HRESULT GetDpiForMonitor([In] HMONITOR hmonitor, [In] MONITOR_DPI_TYPE dpiType, [Out] out uint dpiX, [Out] out uint dpiY);
```
Sorry for my poor English...

**What code is involved**

**Expected behavior**

**Screenshots**

**Comment by dahall** [comment]
Thanks for pointing out this behavior. The problem is case-sensitive loading of PE dlls starting with .NET 5. I've corrected the problem by making all dll references lowercase.
