### ISSUE TITLE
CldApi -> Is it possible to change the type of CF_PLACEHOLDER_CREATE_INFO#CreateUsn from "int" to "long"

### ISSUE THREAD

**Issue by stefan-agl** [dahall/Vanara#241]
**Is your feature request related to a problem? Please describe.**
In trying to implement the CldApi sync-engine callbacks and am facing an issue in the `CF_CALLBACK_TYPE.CF_CALLBACK_TYPE_FETCH_PLACEHOLDERS` callback, which is manifested by an exception whose cause for me is still unknown. 
The exception - `System.AccessViolationException` :  "Attempted to read or write protected memory. This is often an indication that other memory is corrupt". 

The interesting bit about this exception is that it does not occur when I limit the number of placeholders being returned by the callback to only one. I started comparing the definitions of the structures in Vanara and the C header where in `cfapi.h` I find: 

`typedef struct CF_PLACEHOLDER_CREATE_INFO {
    ... ... ...
    USN CreateUsn;
} CF_PLACEHOLDER_CREATE_INFO;`

with **USN** being defined as follows: 

`typedef LONGLONG USN;`

Compared, to Vanara where the structure is mapped like this:

`public struct CF_PLACEHOLDER_CREATE_INFO
    {
      ... ... ...
      **public int CreateUsn;**
      ... ... ...
    }`

**Describe the additions or enhancements you'd like**

Could `public int CreateUsn;` be changed to `public long CreateUsn;` 

I think this has an effect on `Marshal.SizeOf(...)` for that type, which then affects how many bytes get allocated through `Marshal.AllocHGlobal(...)`

Please correct me if I am wrong, and do let me know where my logic fails!

Thanks, and regards!
Stefan

**Comment by stefan-agl** [comment]
Great, thanks!

I have been trying to build it locally in order to try it out, but still have not found out how to make my project depend on the locally built version instead of on the nugget package. 

But, I can wait for a build, although I will be away until Monday and could only give it a try then.

**Comment by stefan-agl** [comment]
Actually, I was able to build `Vanara.PInvoke.CldApi` and depend my project on the local dlls. 

Now it seems the exception is gone and files/folders are being processed correctly when returned by the callback.

I will be looking forward to the next release that will contain this correction. 

Regards,
Stefan

**Comment by dahall** [comment]
> I have been trying to build it locally in order to try it out, but still have not found out how to make my project depend on the locally built version instead of on the nugget package.
This is kind of a pain. You have to establish a local NuGet repository, make sure the version is higher, push the built package to the repository, make sure you've removed the old NuGet dependency from all projects and cleaned all projects, clear the local NuGet caches, and the re-add the package from your local repository. I usually do exactly what you did.
> Now it seems the exception is gone and files/folders are being processed correctly when returned by the callback.
Is the only change you made updating the `CreateUsn` field to `long`?

**Comment by stefan-agl** [comment]
Yes, this was the only change I made locally 

int -> long

**Comment by dahall** [comment]
I have pushed the updates (there were actually a number of places where I'd used `int` for `USN` incorrectly). An updated NuGet package should be ready for testing from AppVeyor's NuGet repository in the next 10 minutes. See the project homepage for details on connecting to that repository for your testing.

**Comment by dahall** [comment]
In case you hadn't seen it, I created a wrapper class around the CLDAPI methods for testing that may be of use: https://github.com/dahall/Vanara/blob/master/UnitTests/PInvoke/CldApi/CloudSyncProvider.cs

**Comment by stefan-agl** [comment]
I found the unit test only recently; the code there could be a starting point and a source of inspiration as this is my first real exposure to .NET/C# since university.
