### ISSUE TITLE
Accessing ShelItem's Properties leaves an open file handle

### ISSUE THREAD

**Issue by gave92** [dahall/Vanara#242]
**Describe the bug**
It appears that sometimes accessing a shell item's properties results in a file handle remaining open after shell item is disposed.
The file type seems important: a docx file will have this issue while a txt file won't.
This happens specifically when getting the NTFS file id property ("System.FileFRN") but I haven't tested it with other properties.

**What code is involved**
```cs
using Vanara.Windows.Shell;
using (var si = new ShellItem(@"PATHTOSOMEFILE.docx"))
{
    Console.WriteLine((ulong?)si.Properties["System.FileFRN"]);
}
// File here will still be in use (e.g explorer won't let me rename the parent folder)
```

**Expected behavior**
All file handles closed after ShellItem is disposed.

**Version**
Vanara.Windows.Shell 3.3.11
Windows 10 21H1

**Comment by dahall** [comment]
I'm away from a computer for a little while, but will you check past issues? I believe this was a topic found by another user who found some information on the Internet about why this happens with Microsoft documents.

**Comment by gave92** [comment]
Indeed my issue looks similar to #214. There's a workaround posted there and for me this is not a blocking issue (I've just resorted to use GetFileInformationFromHandleEx to get the same info).

**Comment by dahall** [comment]
Just for grins, what happens if you call `GC.Collect()` after your using statement? Are you then able to lock the file?

**Comment by dahall** [comment]
@gave92 To improve the speed of your code, consider using `PROPERTYKEY.System.FileFRN` instead of the string value equivalent. Otherwise, the indexer calls a method to get the `PROPERTYKEY` value from the string.
```cs
Console.WriteLine((ulong?)si.Properties[PROPERTYKEY.System.FileFRN]);
```

Also, if you don't know if the value exists, doing the following is more performant as well:
```cs
if (si.Properties.TryGetValue(PROPERTYKEY.System.FileFRN, out ulong frn))
   Console.WriteLine(frn);
```

**Comment by gave92** [comment]
Thanks!

**Comment by dahall** [comment]
After some further adjustments, I have eliminated the need to garbage collect when `ShellItem` is manually disposed. Your initial code submission for the issue should now run without error. Release 3.3.12 will have the fix. You can use it now by using the AppVeyor NuGet repo (see homepage).
