### ISSUE TITLE
mouse_event  Coordinates under multiple screens are negative

### ISSUE THREAD

**Issue by shouhujishu** [dahall/Vanara#248]
**Describe the bug**
User32.mouse_event 
uint dx, uint dy
Coordinates under multiple screens are negative

**Expected behavior**
int dx, int dy

**Comment by dahall** [comment]
Thanks for the report. I have adjusted the parameters and committed those changes. It will go out in the next release.

Until then, you can use the following to pass negative values:
```cs
mouse_event(0, unchecked((uint)-15), unchecked((uint)-30), 0, default);
```
