### ISSUE TITLE
AuthzReportSecurityEvent method call error Index not found. (0x80131124)

### ISSUE THREAD

**Issue by lovesuch** [dahall/Vanara#251]
Hello, AuthzReportSecurityEvent method call error

System.BadImageFormatException: 'Index not found. (0x80131124)'

![AuthzReportSecurityEvent](https://user-images.githubusercontent.com/8306762/139870882-6d015cf8-07b8-4d9a-b2de-4393905c9f4c.png)

**Comment by dahall** [comment]
I can't see how you've used the function. Does this sample code help? https://github.com/dahall/Vanara/blob/3e1596ba7f60f6478e9efd0d5c1b30d102df9439/UnitTests/PInvoke/Security/Authz/AuthzTests.cs#L334

**Comment by lovesuch** [comment]
Sample code error
![image](https://user-images.githubusercontent.com/8306762/140310779-78198508-a1d5-4c63-99b2-b157e5d50bf6.png)

**Comment by dahall** [comment]
What error did the line above report?

**Comment by lovesuch** [comment]
Sometimes returns false

![image](https://user-images.githubusercontent.com/8306762/140329931-84b85af5-2b02-4968-8906-428f5ae2bd5e.png)

**Comment by lovesuch** [comment]
the first time
![1](https://user-images.githubusercontent.com/8306762/140651339-73a28ceb-4150-42d4-87f8-88507470e02f.png)

the second time
![2](https://user-images.githubusercontent.com/8306762/140651356-1962d10a-8772-455c-b71b-b559bbd9e483.png)

**Comment by lovesuch** [comment]
![image](https://user-images.githubusercontent.com/8306762/140652143-ce42ddf4-d9eb-4cf5-ba2a-f3cfe4c635d1.png)

Write once, there are two logs
![image](https://user-images.githubusercontent.com/8306762/140652171-c2ae5a7e-45da-43ff-98bb-752a4adb8368.png)

**Comment by dahall** [comment]
On the failure for a second call to `AuthzRegisterSecurityEventSource`, check [here](https://stackoverflow.com/questions/18219559/error-1314-when-i-call-authzregistersecurityeventsource-in-windows-2008-but-wo).

I'm not clear from your screen captures what the steps are to reproduce each problem. Will you please outline those steps?

**Comment by lovesuch** [comment]
Thank you very much for your reply.

How to add Name property to EventData Data？

Like this
![1](https://user-images.githubusercontent.com/8306762/140689905-dd390f0e-dd36-4195-8c46-aa6387f9a757.png)

How to add multiple EventData Data？

**Comment by dahall** [comment]
I don't have an answer yet on your `Name` attribute question, but have corrected and tested the code to get multiple `Data` elements. See test case [here](https://github.com/dahall/Vanara/blob/03bd938b7c1644a46d73eac060fc0767b2217549/UnitTests/PInvoke/Security/Authz/AuthzTests.cs#L252). Using that pattern also avoids the privilege error.

**Comment by dahall** [comment]
I have fixed problems now with `AuthzReportSecurityEventFromParams` and verified that there is no user API that allows the Name attribute to be added to the Data element.
