### ISSUE TITLE
Vanara.PInvoke.Shell32 and IStorageProviderCopyHook

### ISSUE THREAD

**Issue by Blair88** [dahall/Vanara#252]
**Is your feature request related to a problem? Please describe.**
I'm currently trying to implement a cloud sync engine using **Vanara.PInvoke.CldApi** and found out that I am unable to invoke a copy hook handler (**ICopyHook**) from **Vanara.PInvoke.Shell32** on folders that are being managed by a cloud provider.

As I am new to the Vanara project and also the CloudAPI, I might be doing something wrong but I followed the references from Microsoft and was able to register a copy hook handler. However, it does not get invoked at all so I searched for solutions and found [IStorageProviderCopyHook](https://docs.microsoft.com/en-us/windows/win32/shell/nn-shobjidl-istorageprovidercopyhook). From what I read it seems that this is actually the intended method for invoking copy hook handlers on folders managed by a cloud provider.

I looked through all the libraries supported by Vanara and also did a git search but was unable to find anything related to IStorageProviderCopyHook. If it exists, I'd be grateful if someone could point me to it.

**Describe the additions or enhancements you'd like**
Would it be possible to add the [IStorageProviderCopyHook](https://docs.microsoft.com/en-us/windows/win32/shell/nn-shobjidl-istorageprovidercopyhook) interface to Vanara.PInvoke.Shell32 in order to be able to install a CopyHook handler for folders located under a cloud provider's sync root from the CloudAPI.

**Previous work**
I'm not aware of any previous work on this issue.

**Comment by dahall** [comment]
It is committed and will go out in the next release. While you wait, you can pull the current build from AppVeyor as described in README.md.

**Comment by Blair88** [comment]
This is perfect, thank you very much for your quick reply.

**Comment by dmitryshunkov** [comment]
Blair88, have you been successful with the implementation? I tried to get the IStorageProviderCopyHook implementation to work, but the CopyCallback method isn't invoked for some reason, only a constructor and a destructor.

**Comment by wangfu91** [comment]
@dmitryshunkov  `IStorageProviderCopyHook` only work on **folders**,  renaming a file won't trigger the `CopyCallback`.
