### ISSUE TITLE
No WS_EX_NOREDIRECTIONBITMAP in WindowStylesEx

### ISSUE THREAD

**Issue by XuanchenLin** [dahall/Vanara#254]
Hi,
Recently, I needed to use the CreateWindowEx to create a window without a redirection surface, but I found that there is no WS_EX_NOREDIRECTIONBITMAP value in WindowStylesEx. Will this enumeration value be added in a future version?

**Comment by dahall** [comment]
Looks like that value is 0x00200000. I'll get that added and it will show up in the next release.
