### ISSUE TITLE
BasicMessageWindow does not check WindowClass.Unregister() return value

### ISSUE THREAD

**Issue by oysteinkrog** [dahall/Vanara#259]
**Describe the bug**
BasicMessageWindow creates a WindowClass, and on dispose/finalizer it calls Unregister on this WindowClass instance, but it does not check the return value.

**Expected behavior**
The code should check the return bool, and throw Win32Exception if false.

**Comment by dahall** [comment]
This is on purpose. There is a race condition where the Unregister method fails. Since it was indeterminate, I decided to not check the return value. Is there a condition where it fails and that is a problem?

**Comment by oysteinkrog** [comment]
In our application (not using Vanara yet) I found that it can leak classes, as UnregisterClass will fail if you try to unregister before all windows that use that class are closed. I am investigating replacing all of our own bindings with Vanara, but want to make sure that we are not introducing any errors in doing so.
The scenario with leaking classes will slowly fill up the atom tables, and in artificial tests I've been able to crash the entire user session to the point where opening new applications will fail.
I don't know if your code has the leaking classes problem, just that it seems prudent to check the return value.
I guess if you are certain that BasicMessageWindow will never unregister the class until the window is fully closed it should be safe.
What kind of race condition are you referring to?

**Comment by oysteinkrog** [comment]
In general, I wonder if API with error codes as return value should be annoated with [MustUseReturnValue]?
It's safer as it will give developers feedback if they forget, and if you truly don't want to check the return value it's always possible to ignore compile errors/warnings on specific lines.

**Comment by dahall** [comment]
To your point, you cannot unregister a class until all windows are closed. Even when the system destroys a window, the OS does not immediately decrement the class count. Therefore there is an arbitrary amount of time between calling DestroyWindow and UnregisterClass where it will fail. I've thought of doing what is done in .NET forms, where there is a separate garbage collector process that unregisters classes, but it seemed like overkill.
