### ISSUE TITLE
Annotate Vanara libraries for trimming

### ISSUE THREAD

**Issue by caesay** [dahall/Vanara#261]
It is possible to manually mark Vanara for Trimming by adding hints to the csproj of every project that uses it, but this is laborious and repetitive. For example, if using just `Vanara.PInvoke.User32` in a net6 app, I would need to add the following to the csproj of each exe to enable trimming:

```xml
<ItemGroup>
  <!-- trim Vanara.PInvoke.User32 and all of it's dependencies -->
  <TrimmableAssembly Include="Vanara.Core" />
  <TrimmableAssembly Include="Vanara.PInvoke.Gdi32" />
  <TrimmableAssembly Include="Vanara.PInvoke.Kernel32" />
  <TrimmableAssembly Include="Vanara.PInvoke.Shared" />
  <TrimmableAssembly Include="Vanara.PInvoke.User32" />
</ItemGroup>
```

It would be more convenient if Vanara libraries are already pre-annotated for trimming, so this happens automatically. This can be done by adding the `[AssemblyMetadata("IsTrimmable", "True")]` attribute to each Vanara assembly.

Additionally, it might be useful to annotate any functions which use reflection (if there are any) with `RequiresUnreferencedCode` and/or `DynamicallyAccessedMembers`, as appropriate, to give hints to the trimmer and produce better results/warnings. 

See also 
- https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options
- https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/prepare-libraries-for-trimming

**Comment by dahall** [comment]
Great suggestions. I'll look at including soon.

**Comment by dahall** [comment]
Reading the supporting materials, can I just add the `<IsTrimmable>true</IsTrimmable>` to all the project files or does that have a different effect than `[AssemblyMetadata("IsTrimmable", "True")]`?

**Comment by dahall** [comment]
I also just read that COM is disabled when trimming. COM is used in almost all of the assemblies. Do you know any more about that?

**Comment by dahall** [comment]
I've added it to the 3.4.0 build on AppVeyor. See home page for info on pulling NuGet packages. Please let me know if this accomplishes what you wanted. I also added builds for .NET 6.0.

**Comment by caesay** [comment]
COM is disabled by default when trimming is enabled. This applies to the Vanara libraries whether or not they are marked as trimmable. It's something that people performing assembly Trimming need to be aware of if they are deploying apps or dependencies that use COM.

Generally speaking, if you are using the `net6.0-windows` target (and not just `net6.0`), and you re-enable COM using `<BuiltInComInteropSupport>true</BuiltInComInteropSupport>`, most COM will work properly. 

I appreciate you adding this in, and for your amazing continued effort on this library. Do you plan to accept donations? I'd gladly contribute. I'll check it out 3.4 today or tomorrow and will let you know if it is working and test some of the COM bits in the Windows.Shell library.

**Comment by hez2010** [comment]
To enable trimming, Vanara must annotate itself to make sure all members in an interface are kept if the interface is used, because COM is member order/index-awareness.

**Comment by dahall** [comment]
> To enable trimming, Vanara must annotate itself to make sure all members in an interface are kept if the interface is used, because COM is member order/index-awareness. An interface can be trimmed away, but a member in an interface cannot be trimmed.

So every COM interface must be annotated or every member of every COM interface? Where can I find details about this process?

**Comment by hez2010** [comment]
The built-in COM interop in .NET cannot ensure this. To support trimming, you need to use COMWrappers.

**Comment by dahall** [comment]
Well over half of the COM interfaces in Vanara are extracted from C++ and do not have Type Library support. In the past, all COMWrapper generation only worked with typelibs. Maybe that will change, but I really doubt it. I'm going to start a Discussion and reference this thread. This is a area that obviously needs more research and better support.
