### ISSUE TITLE
User32_Gdi parameter type improvements

### ISSUE THREAD

**Issue by sclarke81** [dahall/Vanara#27]
I have been making use of User32_Gdi recently and feel that some of the parameter types could be improved. Some examples that I've come across are:

1. The `nIndex` parameter of `SetWindowLong` and `GetWindowLong` could be `WindowLongFlags`.
1. There is no overload of `SendMessage` that accepts a `WindowMessage` as `msg` with defaults for `wParam` and `lParam`.
1. Having to create an `IntPtr` when calling `SetWindowLong` is annoying; perhaps it could accept an enum and do the conversion internally.
1. I don't think `WindowLongFlags` should be flags as it is specifying the value to retrieve.

**Comment by dahall** [comment]
1. Done. Oversight on my part.
2. Problem with changing `uint` to `WindowMessage` is that other window types (mostly controls) define their own messages. C# doesn't allow inheritance on enums, so the only common value is `uint`. If you cast to `uint`, it should accept the defaults. (e.g. `SendMessage(hWnd, (uint)WindowMessage.WM_CREATE);`)
3. Agreed. I created an overload of `SetWindowLong` that accepts an `int` and returns an `int`.
4. Agreed. Removed `[Flags]` attribute.

You'll see these changes in the next release.
