### ISSUE TITLE
How to undo IFileOperation?

### ISSUE THREAD

**Issue by milos12345** [dahall/Vanara#273]
ShObjIdl.IFileOperation.cs has option for FOFX_ADDUNDORECORD and I can use CopyItem, MoveItem or DeleteItem, but I don't see a way to undo these. If I delete item with this, the record is created and in Explorer's shell context menu there is option to undo, but how to use Vanara.Shell32 to undo it from code?

**Comment by dahall** [comment]
That value is set or unset by setting the flags parameter of IFileOperation.SetOperationFlags

**Comment by milos12345** [comment]
Yes, I can already set the flags that way. But is there an API in Vanara.Shell to use that undorecord in order to undo the file operation like move or delete that was completed while using that flag?

**Comment by dahall** [comment]
You can use the [`RecycleBin`](https://github.com/dahall/Vanara/blob/bd707099f89d1b7a6436ccb61a97a652cc0ce1d2/Windows.Shell.Common/RecycleBin.cs#L13) class.

**Comment by milos12345** [comment]
I have idea on how to improvise undoing RecycleBin operation. I assume that there is no way to access the same API as Explorer to undo last Copy/Move operation with the help of FOFX_ADDUNDORECORD. If I ever find it I'll post it here.

**Comment by dahall** [comment]
The only information I could relate to the documentation for FOFX_ADDUNDORECORD ties to either `IOleUndoManager` or `IOleInPlaceSite`. Those may be places to start.
