### ISSUE TITLE
Calling GetProcessInformation<PROCESS_POWER_THROTTLING_STATE>... returns error.

### ISSUE THREAD

**Issue by speed2048** [dahall/Vanara#275]
Setup

Running this on Windows 11 on a I7 Gen 12 processor.

When I call 
PROCESS_POWER_THROTTLING_STATE ppts = GetProcessInformation<PROCESS_POWER_THROTTLING_STATE>(GetCurrentProcess(), PROCESS_INFORMATION_CLASS.ProcessPowerThrottling);

I get the following exception.

Value does not fall within the expected range.

**What code is involved**

using static Vanara.PInvoke.Kernel32;
class Program
{
static void Main(string[] args)
    {

try
        {
PROCESS_POWER_THROTTLING_STATE ppts = GetProcessInformation<PROCESS_POWER_THROTTLING_STATE>(GetCurrentProcess(), PROCESS_INFORMATION_CLASS.ProcessPowerThrottling);
}  catch (Exception ex)
        {
            string x = ex.Message;
        }
}
}

**Expected behavior**
Exception not to occur and ppts struct filled in.

**Comment by dahall** [comment]
Calling this same function from C has the same error (ERROR_INVALID_PARAMETER). This is a system/Windows problem.
```c
if (GetProcessInformation(GetCurrentProcess(), PROCESS_INFORMATION_CLASS::ProcessPowerThrottling, &state, sizeof(state)))
{
   std::cout << state.Version << " : " << state.StateMask << "\n";
}
else
{
   std::cout << GetLastError() << "\n";
}
```

**Comment by speed2048** [comment]
Do you know how to contact the the Windows team to send a bug report?

**Comment by dahall** [comment]
If you belong to a company, I have found https://support.serviceshub.microsoft.com/supportforbusiness to be the most responsive. Otherwise, you have to use Contact Hub (https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).

**Comment by speed2048** [comment]
Thanks, Could you send the complete c file. So I can submit it to them.

**Comment by dahall** [comment]
Other than header includes and a main function, that's it

**Comment by speed2048** [comment]
Microsoft has fixed this issue in Windows 11 22H2, the C++ code that you supplied does work with a slight modification, however the Vanara package still returns  an exception System.ArgumentException:' Value does not fall withing the expected range' . The issue is you have to populate  the PROCESS_POWER_THROTTLNG_STATE first before you invoke the function. 

If that is not there you will get the exception. In the  c++  version I did populate the state and it still returned the error so Microsoft did fix this.

code  snippet to populate Process Power throttling  state.

`PROCESS_POWER_THROTTLING_STATE state;`
 `RtlZeroMemory(&state, sizeof(state));`
 `state.Version = PROCESS_POWER_THROTTLING_CURRENT_VERSION;`

**Comment by dahall** [comment]
In this case, since it is not a pure `out` parameter, you'll need to use the overload that allows for a reference.
```cs
var state = new PROCESS_POWER_THROTTLING_STATE(0, 0);
using var pin = new PinnedObject(state);
Win32Error.ThrowLastErrorIfFalse(GetProcessInformation(GetCurrentProcess(),
   PROCESS_INFORMATION_CLASS.ProcessPowerThrottling, pin,
   (uint)Marshal.SizeOf<PROCESS_POWER_THROTTLING_STATE>()));
```
