### ISSUE TITLE
`SHAppBarMessage` not working correctly. 

### ISSUE THREAD

**Issue by ranbims** [dahall/Vanara#276]
I tried to setup an appbar with this API. It doesn't work correctly. After failed several times, I could make it work by `DllImport` internally in the project with the same piece of code. 

I noticed the APPBARDATA defined in this repo as below.
```
		public struct APPBARDATA
		{
			public uint cbSize;

			public HWND hWnd;

			public IntPtr lParam;

			public RECT rc;

			public uint uCallbackMessage;

			public ABE uEdge;
		}
``` 

However, in the official document, the structure is defined as below.

```
typedef struct _AppBarData {
  DWORD  cbSize;
  HWND   hWnd;
  UINT   uCallbackMessage;
  UINT   uEdge;
  RECT   rc;
  LPARAM lParam;
} APPBARDATA, *PAPPBARDATA;
```

The sequence is different, but I am not sure if this is the reason why it didn't work.

**Comment by dahall** [comment]
You got it. Somehow I got the order messed up. My apologies for your frustration and thanks for your report. I just pushed a commit with the fix. Until I push the next release to NuGet.org, you can pull a pre-build from AppVeyor (see README for how to connect).
