### ISSUE TITLE
COMException with 'STG_E_FILEALREADYEXISTS' should also consider as exception or normal status?

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#277]
https://github.com/dahall/Vanara/blob/bd707099f89d1b7a6436ccb61a97a652cc0ce1d2/Windows.Shell.Common/ShellProperties/ShellItemPropertyStore.cs#L147

It might throw COMException with 'STG_E_FILEALREADYEXISTS' when trying to get 'System.FileOfflineAvailabilityStatus' property from OneDrive files

StackTrace:
```
   At Vanara.PInvoke.Shell32.IShellItem2.GetPropertyStore(GETPROPERTYSTOREFLAGS flags, Guid& riid)
   At Vanara.Windows.Shell.ShellItemPropertyStore.GetIPropertyStore()
   At Vanara.Windows.Shell.ReadOnlyPropertyStore.Run[T](Func`2 action)
   At Vanara.Windows.Shell.ReadOnlyPropertyStore.TryGetValue[TVal](PROPERTYKEY key, TVal& value)
   At Vanara.Windows.Shell.ReadOnlyPropertyStore.TryGetValue(PROPERTYKEY key, Object& value)
   At Vanara.Windows.Shell.ReadOnlyPropertyStore.get_Item(PROPERTYKEY key)
   At Vanara.Windows.Shell.ReadOnlyPropertyStore.get_Item(String knownKey)
   At Vanara.Windows.Shell.PropertyStore.get_Item(String knownKey)
```

**Comment by dahall** [comment]
What is the expected outcome in this scenario you describe?

**Comment by zhuxb711** [comment]
> What is the expected outcome in this scenario you describe?

I'm not sure what is 'STG_E_FILEALREADYEXISTS' but it passed your exception filter

**Comment by dahall** [comment]
Doing some research, it appears that error is thrown with the file has not been closed before trying to access its property store. I think the exception should remain exposed as it is an error that prevents the property store from opening.

**Comment by dahall** [comment]
Also, it looks like you're using the 3.4 prerelease. Thank you for trying it out. Please let me know your experience.

**Comment by dahall** [comment]
@zhuxb711  Any update? If not, I'll close the issue.

**Comment by zhuxb711** [comment]
No, thanks
