### ISSUE TITLE
Could not load file or assembly 'Vanara.Windows.Shell'... manifest definition does not match the assembly reference

### ISSUE THREAD

**Issue by milos12345** [dahall/Vanara#281]
I've been getting quite a few crashes in telemetry with this content: 
```
System.IO.FileLoadException: Could not load file or assembly 'Vanara.Windows.Shell, Version=3.3.15.0, Culture=neutral, PublicKeyToken=c37e4080322237fa' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
    at   (IconsManager.cs:109) 
```
pointing to a completely irrelevant part of the code:
```
BitmapImage bi = new BitmapImage();
bi.BeginInit(); //<- ----------here
bi.UriSource = new Uri("pack://application:,,,/MyApp;component/Images/icon.png", UriKind.Absolute);
```
and that static class doesn't even have Vanara.* in the using

I had this with 3.3.13.0 also.
.NET4.8
Added through NuGet
Do you have any suggestions on how to determine the cause of this?

**Comment by dahall** [comment]
This is curious. If you can, will you try replacing `Vanara.Windows.Shell` with `Vanara.Windows.Shell.Common` 3.4.0 from the NuGet repository at https://ci.appveyor.com/nuget/vanara-prerelease? We've dramatically reduced dependencies and I'm interested to know if that helps your issue.

**Comment by milos12345** [comment]
After getting more detailed reports it looks like this is happening for users who updated from the version that used `Vanara.Windows.Shell` version 3.3.13.0, but the updater should be replacing all the files including that dll, so I am not sure if that is relevant. But I will pack a version with `Vanara.Windows.Shell.Common` and get back with findings

**Comment by dahall** [comment]
Version 3.4.0 was just released. Let me know if your problem persists.

**Comment by milos12345** [comment]
I have switched to `Vanara.Windows.Shell.Common` and I didn't get any `System.IO.FileLoadException` anymore. I like that it has less dependencies.

I did get a a different error but I have to check first if those are just users deleting dependencies

**Comment by dahall** [comment]
@milos12345 If your issue is resolved, please close it. If not, let me know what you're finding.
