### ISSUE TITLE
Add getSafeHDEVINFO and getSPDEVINFODATA to Device class

### ISSUE THREAD

**Issue by ymg2006** [dahall/Vanara#282]
Hello,
If one wants to remove a device from a local pc, it is necessary to have these two properties(Device.hdi and Device.data) which are private.
Either modify Access Modifiers or add two functions like:
public getSafeHDEVINFO => hdi;
public  getSPDEVINFODATA  => data;

But the best solution is to make each of them a property with a private setter.
https://github.com/dahall/Vanara/System/Computer/DeviceManager.cs

The DeviceManager.LocalInstance.GetDevices() throws an exception, one could be able to change the DeviceCollection(DIGCF filter) to fix it. It would be great to make this parameter optional like where on can change the filter to what he wants:
DeviceManager.LocalInstance.GetDevices(DIGCF filter = DIGCF.DIGCF_PRESENT);

the latest is optional since one can create a device collection with a filter but I think its a good way to make this optional.

I could not compile this repo to create changes and make a PR.
Thank you in advance.

**Comment by dahall** [comment]
Great suggestions. I've incorporated them and they will be in v3.4.0.

I'm using VS2022, so that may be what is preventing your builds.
