### ISSUE TITLE
User32.SystemParametersInfo User32.SPI.SPI_SETDROPSHADOW takes a raw bool instead of pointer as parameter

### ISSUE THREAD

**Issue by shirok1** [dahall/Vanara#283]
```csharp
User32.SystemParametersInfo(User32.SPI.SPI_SETDROPSHADOW, value, broadcastChange:false); // not working
User32.SystemParametersInfo(User32.SPI.SPI_SETDROPSHADOW, 0, new IntPtr(value ? 1 : 0), User32.SPIF.None); // worked
```

This is a strange behavior. I wonder if their is more SPI works like this...

**Comment by shirok1** [comment]
PS value is a bool

**Comment by dahall** [comment]
Thank you for reporting this. It helped me find a number of problems with this method and the overloads I created.

**Comment by shirok1** [comment]
Forgive me about my rudeness, I wonder when will the NuGet package be updated?

**Comment by dahall** [comment]
Not rude, just curious. I'm testing a major release now and plan to release within the next two weeks. Before then, you can pull the current packages from the project AppVeyor NuGet feed as detailed on the project home page.
