### ISSUE TITLE
Could not load file or assembly 'System.Security.Permissions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)'

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#286]
**Describe the bug**
This exception was threw if I remove this from my net6.0-windows10.0.19041 console project
```
<UseWindowsForms>true</UseWindowsForms>
```

StackTrace:
```
   at Vanara.Windows.Shell.ShellLink.LoadAndResolve(String linkFile, SLR_FLAGS resolveFlags, HWND hWin, UInt16 timeOut)
   at Vanara.Windows.Shell.ShellLink..ctor(String linkFile, LinkResolution resolveFlags, HWND window, TimeSpan timeOut)
   at FullTrustProcess.Program.<HandleCommand>d__18.MoveNext() in C:\Users\ruofan.a.zhu\source\repos\RX-Explorer\FullTrustProcess\Program.cs:line 2454
```

**What code is involved**
```csharp
ShellLink Link  = new ShellLink("Path");
```

**Expected behavior**
Should not threw exception

**Screenshots**
None

**Comment by zhuxb711** [comment]
Add 'System.Security.Permissions' nuget package to my project fixed that issue, but I think Vanara should include that component with it

**Comment by dahall** [comment]
`Vanana.Windows.Shell.Common` references `System.Security.Permissions` v5.0.0 already.

**Comment by zhuxb711** [comment]
Install Vanana.Windows.Shell.Common is not work for me

**Comment by dahall** [comment]
Are you using v3.3.15 or earlier then of `Vanara.Windows.Shell`?

**Comment by zhuxb711** [comment]
![image](https://user-images.githubusercontent.com/42038175/158504645-7a71e27f-e0b3-4713-893b-8032713ae82e.png)
I'm using v3.4.0 for all Vanara packages

**Comment by zhuxb711** [comment]
I could not reproduce this issue in new console project. 

In case if you have interest in this issue, you could download repro from [here](https://github.com/zhuxb711/RX-Explorer). Remove "System.Security.Permission" nuget package from "FullTrustProcess" project and then run "Package" project with debugger attached to the process of "FullTrustProcess". Navigate to Desktop folder in RX will trigger this issue. 

Appreciate to any helps.

**Comment by dahall** [comment]
@zhuxb711 Are you still seeing this issue?

**Comment by zhuxb711** [comment]
> @zhuxb711 Are you still seeing this issue?

Not sure because I added an independent package for that dll to fix this issue

**Comment by zhuxb711** [comment]
Not seen this issue and I have already remove the independent System.Security.Permission nuget package
