### ISSUE TITLE
System.Drawing.Color and Vanara.PInvoke.Gdi32.RGBQUAD cast

### ISSUE THREAD

**Issue by shirok1** [dahall/Vanara#287]
Hello, I found implicit cast between `Color` and `RGBQUAD` is removed in 3.4.0 . Is that an intended refactor? I do find a struct called `COLORREF` which can implicit cast from/to `Color`, and also implicit cast from/to `RGBQUAD`, which means I can still finish my prop assignment in one line, but I need to add a *transit* like this:

```csharp
// Before 3.4.0
parameters.clrColor = data.AeroColor;

// After 3.4.0
// parameters.clrColor = new Gdi32.RGBQUAD {Color = data.AeroColor};
parameters.clrColor = (COLORREF) data.AeroColor;
```

**Comment by shirok1** [comment]
I forked this repo and found that `COLORREF` is in a seperate project, which references System.Drawing itself..... I wonder why not seperate this cast to an extension class

**Comment by shirok1** [comment]
> I could move RGBQUAD into `Vanara.PInvoke.Shared` alongside COLORREF and put back the implicit conversion. Then the dependency on `System.Drawing` is restricted to that one assembly and it can easily be trimmed. What do you think of that option?

Well, I don't even known the exact pros and cons of removing dependency, because I don't have a scene where I need to call Win32 while System.Drawing unavailable 🤣

> On your second message, unfortunately, .NET does not allow for implicit conversion operators to be defined in extension methods.

Hmm, I think I'm talking about extension methods like ToColor, not necessarily a cast.

**Comment by dahall** [comment]
I just committed these changes to master. Check them out [here](https://github.com/dahall/Vanara/blob/master/PInvoke/Shared/WinGdi/WinGdi.RGBQUAD.cs).

**Comment by dahall** [comment]
@shirok1 Thoughts on the changes made?
