### ISSUE TITLE
Add NT API

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#289]
Add NT API functions.
It would be nice to have everything in one library.

https://github.com/googleprojectzero/sandbox-attacksurface-analysis-tools/tree/main/NtApiDotNet

**Comment by dahall** [comment]
This is a major uplift and the project you reference is really complete and active. Many of the memory management and helper functions from Vanara.Core and Vanara.PInvoke.Shared should help when using the Google Project Zero code. I may add a few methods to Vanara.PInovke.NtDll, but I doubt I'll ever catch up with this other project.
