### ISSUE TITLE
Cannot generate Success Audits using AuthzReportSecurityEventFromParams 

### ISSUE THREAD

**Issue by menonsoftware** [dahall/Vanara#291]
**Describe the bug**
Cannot generate Success Audits using AuthzReportSecurityEventFromParams 

          using (new ElevPriv("SeAuditPrivilege"))
            {
                AUTHZ_SOURCE_SCHEMA_REGISTRATION srcReg = new()
                {
                    dwFlags = SOURCE_SCHEMA_REGISTRATION_FLAGS.AUTHZ_ALLOW_MULTIPLE_SOURCE_INSTANCES,
                    szEventSourceName = eventSource,
                    szEventMessageFile = eventFile,
                    szEventAccessStringsFile = eventFile,
                };
                try
                {
                    AuthzInstallSecurityEventSource(0, srcReg);
                    AuthzRegisterSecurityEventSource(0, eventSource, out SafeAUTHZ_SECURITY_EVENT_PROVIDER_HANDLE hEvtProv);
                    using SafeCoTaskMemString data = new(eventFile);
                    using SafeNativeArray<AUDIT_PARAM> mem = new(new[] {
                        new AUDIT_PARAM(AUDIT_PARAM_TYPE.APT_String, data),
                        new AUDIT_PARAM(AUDIT_PARAM_TYPE.APT_Ulong, new IntPtr(123)),
                    });
                    AUDIT_PARAMS ap = new() { Count = (ushort)mem.Count, Parameters = mem };
                    AuthzReportSecurityEventFromParams(auditType, hEvtProv, eventId, PSID.NULL, ap);

                }
                catch(Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                    MessageBox.Show($"{ex.Message}");
                }
            }

**Expected behavior**
Should create an audit depending on auditType (0,1)?

**Comment by dahall** [comment]
Hm. I just ran the following code from my test unit (which I think is what you've used as your base) and it works. I'd check on the changes you made. The first parameter should always be 0 according to the documentation.
```cs
public void AuthzReportSecurityEventFromParamsTest()
{
   const int eventId = 4624;
   const string eventFile = "Some random string";
   const string eventSource = "TestAddEventSource";

   using (new ElevPriv("SeAuditPrivilege"))
   {
      AUTHZ_SOURCE_SCHEMA_REGISTRATION srcReg = new()
      {
         dwFlags = SOURCE_SCHEMA_REGISTRATION_FLAGS.AUTHZ_ALLOW_MULTIPLE_SOURCE_INSTANCES,
         szEventSourceName = eventSource,
         szEventMessageFile = eventFile,
         szEventAccessStringsFile = eventFile,
      };
      Assert.IsTrue(AuthzInstallSecurityEventSource(0, srcReg) || Win32Error.GetLastError() == Win32Error.ERROR_OBJECT_ALREADY_EXISTS);

      Assert.That(AuthzRegisterSecurityEventSource(0, eventSource, out SafeAUTHZ_SECURITY_EVENT_PROVIDER_HANDLE hEvtProv), ResultIs.Successful);
      try
      {
         using SafeCoTaskMemString data = new("Testing");
         using SafeNativeArray<AUDIT_PARAM> mem = new(new[] {
            new AUDIT_PARAM(AUDIT_PARAM_TYPE.APT_String, data),
            new AUDIT_PARAM(AUDIT_PARAM_TYPE.APT_Ulong, new IntPtr(123)),
         });
         AUDIT_PARAMS ap = new() { Flags = 0, Count = (ushort)mem.Count, Parameters = mem };
         Assert.That(AuthzReportSecurityEventFromParams(0, hEvtProv, eventId, PSID.NULL, ap), ResultIs.Successful);
      }
      finally { Assert.That(() => hEvtProv.Dispose(), Throws.Nothing); }
   }
}
```
![Screenshot 2022-04-11 194122](https://user-images.githubusercontent.com/14349943/162861831-fc3d5127-cc49-45ae-a238-cc90fa3d497c.png)

**Comment by menonsoftware** [comment]
Yes, perfect! Thank you so much :-)
