### ISSUE TITLE
SYMBOL_INFO Name value always marshalled as a 1 character string.

### ISSUE THREAD

**Issue by shanepowell** [dahall/Vanara#294]
**Describe the bug**
Callbacks that pass in a SYMBOL_INFO as one of it's parameters will always have the Name field be marshelled as a 1 chatacter string. e.g.  PSYM_ENUMERATESYMBOLS_CALLBACK for SymEnumSymbols

**What code is involved**
```cs
var fakeProcess = new IntPtr(1);
DbgHelp.SymInitialize(fakeProcess, null, false);
var pdbBase = DbgHelp.SymLoadModuleEx(fakeProcess, IntPtr.Zero, @"C:\Windows\System32\ntdll.dll", (string)null, 0, (uint)0, IntPtr.Zero, 0);
DbgHelp.SymEnumSymbols(fakeProcess, pdbBase, null, EnumSymbolCallback);

static bool EnumSymbolCallback(in DbgHelp.SYMBOL_INFO symbolInfo, uint symbolSize, IntPtr userContext)
{
    symbolInfo.Name will always be 1 character in length.
    Console.WriteLine("SymbolName: {0}\n", symbolInfo.Name);
    return true;
}
```
**Expected behavior**
symbolInfo.Name in the callback should be the correct string.

**Workaround**
I worked around the issue by changing the SYMBOL_INFO Name to be setup like so:
```cs
MarshalAs(UnmanagedType.ByValTStr, SizeConst = 4001)]
public string Name;
```
4001 was the value returned in the MaxNameLen field on my machine with my setup but I assume this is not the "correct" way to fix this.

I tried adding 
```cs
[VanaraMarshaler(typeof(SafeAnysizeStringMarshaler<SYMBOL_INFO>), "Ansi")]`
```
but that doesn't work. 

It looks like custom marshelers are not called in this call sequence?

**Comment by dahall** [comment]
This was a nasty bug. Thanks for reporting it. It is corrected in the latest commit. The callback method only can use native marshaling. I had to add the custom marshaler (per your idea) and then change the callback method syntax to make this work. I added a `SymEnumSymbolsEx` overload that will return all the `SYMBOL_INFO` structures in a single call:
```cs
using var fakeProcess = new ProcessSymbolHandler(new IntPtr(1), null, false);
var pdbBase = SymLoadModuleEx(fakeProcess, default, @"C:\Windows\System32\ntdll.dll");
foreach (var si in SymEnumSymbolsEx(fakeProcess, pdbBase))
    Console.WriteLine($"SymbolName: {symbolInfo.Name}");
```
