### ISSUE TITLE
AppUserModelID is not available in ShellLink

### ISSUE THREAD

**Issue by caesay** [dahall/Vanara#295]
It's unclear in the git history why AppUserModelID is commented out in `ShellLink.cs`. https://github.com/dahall/Vanara/blob/19bbc90234043b82581c925afc7b7fc9c077dd57/Windows.Shell/ShellObjects/ShellLink.cs#L112

Ideally, AppUserModelID and also ToastActivatorCLSID should be easily settable as these are very common properties.

**Comment by dahall** [comment]
I think I just decided that both could be pulled from the `Properties` property just as easily.

**Comment by caesay** [comment]
Indeed, thanks.
