### ISSUE TITLE
`IpHlpApi.GetExtendedUdpTable<IpHlpApi.MIB_UDP6TABLE_OWNER_PID>` Bug?

### ISSUE THREAD

**Issue by GF-Huang** [dahall/Vanara#296]
**Describe the bug**
I got a lot of large `PID` from UDP6 table. 

It seems like a bug. 

If I change to UDP table (IPv4) rather 6, and change `AF_INET6` to `AF_INET`. There's no any large PID, all in 5 digits.

![image](https://user-images.githubusercontent.com/4510984/166536693-d4d071cd-a226-4b2b-ac93-3c8ff49d9de8.png)

**What code is involved**
```cs
static void PrintUdpV6() {
    using var table = IpHlpApi.GetExtendedUdpTable<IpHlpApi.MIB_UDP6TABLE_OWNER_PID>(IpHlpApi.UDP_TABLE_CLASS.UDP_TABLE_OWNER_PID,
                                                                                     Ws2_32.ADDRESS_FAMILY.AF_INET6);

    foreach (var row in table) {
        Console.WriteLine($"PID={row.dwOwningPid, 10}, EndPoint={new IPEndPoint(new IPAddress(row.ucLocalAddr), (ushort)IPAddress.NetworkToHostOrder((short)row.dwLocalPort))}");
    }
}
```

**Expected behavior**
No large PID.

**Screenshots**

**Comment by dahall** [comment]
The `MIB_UDP6ROW_OWNER_PID` struct that holds that information doesn't change size or layout, so if there is an error, I would expect it to be with the system `GetExtendedUdpTable` function. Have you tried testing this in C++?

**Comment by GF-Huang** [comment]
Never, I will try it later.

**Comment by GF-Huang** [comment]
I had try, C++ works well. Ignore the IPv6 address, it's difficult to format in C++ for me.

![image](https://user-images.githubusercontent.com/4510984/166584574-d51a2b12-7fec-465a-901d-fa6722e8cc1f.png)

**Comment by dahall** [comment]
Ok. Thanks. I'll dig into it.

**Comment by GF-Huang** [comment]
I think maybe the padding cause this issue.

> The MIB_UDP6TABLE_OWNER_PID structure may contain padding for alignment between the dwNumEntries member and the first [MIB_UDP6ROW_OWNER_PID](https://docs.microsoft.com/en-us/windows/desktop/api/udpmib/ns-udpmib-mib_udp6row_owner_pid) array entry in the table member. Padding for alignment may also be present between the MIB_UDP6ROW_OWNER_PID array entries in the table member. Any access to a MIB_UDP6ROW_OWNER_PID array entry should assume padding may exist.

https://docs.microsoft.com/en-us/windows/win32/api/udpmib/ns-udpmib-mib_udp6table_owner_pid

Both Tcp table, Tcp6 table, Udp table, Udp6 table have padding.

**Comment by GF-Huang** [comment]
Should all relational struct add padding? So like `MIB_TCPTABLE`, `MIB_TCPTABLE_OWNER_MODULE`, `MIB_TCPTABLE_OWNER_PID`, `MIB_UDPTABLE`, `MIB_UDPTABLE_OWNER_MODULE`.

**Comment by dahall** [comment]
I went through every structure to ensure size is correct. Most recent commit has all those corrections.

**Comment by GF-Huang** [comment]
Thanks your great work!
