### ISSUE TITLE
open file created by shell  error

### ISSUE THREAD

**Issue by gitlsl** [dahall/Vanara#3]
https://github.com/dahall/Vanara/blob/2cfce3c7d3b9c521dc4e0989f84dd607fec81acd/UnitTests/Shell/ShellFileOperationsTests.cs#L64

above code   create an   excel  , but can not open success  （0 bytes）

**Comment by dahall** [comment]
This method will always create 0 byte files, regardless of type. In order to create a valid Excel file, you will need to use the Microsoft Office API.
