### ISSUE TITLE
Incorrect function signature for IPersistFolder3.InitializeEx

### ISSUE THREAD

**Issue by WubbaLubba** [dahall/Vanara#301]
**Describe the bug**
The function declaration for InitializeEx in the IPersistFolder3 interface is incorrect; ppfti should be nullable [according to the msdn](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ipersistfolder3-initializeex) 

**What code is involved**
[here](https://github.com/dahall/Vanara/blob/eef11ef46e77244665f398065fcbc7b0a3a01369/PInvoke/Shell32/ShObjIdl.IPersistFolder.cs#L336)

**Expected behavior**
The line should probably be
`void InitializeEx([In] IBindCtx pbc, [In] PIDL pidlRoot, [In] PERSIST_FOLDER_TARGET_INFO? ppfti);`

**Comment by dahall** [comment]
Good catch. I have corrected the syntax to
```cs
void InitializeEx([In] IBindCtx pbc, [In] PIDL pidlRoot, [In, Optional] IntPtr ppfti);
```
since nullable types (e.g. `PERSIST_FOLDER_TARGET_INFO?`) cannot be marshaled. I added an overload that still supports the old syntax and handles converting the `PERSIST_FOLDER_TARGET_INFO` value to a pointer.
