### ISSUE TITLE
Signature of ChangeServiceConfig - lpDependencies parameter does not allow multiple dependencies to be passed

### ISSUE THREAD

**Issue by ryannewington** [dahall/Vanara#304]
**Describe the bug**
The signature of the `ChangeServiceConfig` function shows the `lpDependencies` option as a string, then the function is expecting a 

```
A pointer to a double null-terminated array of null-separated names of services or load ordering groups...
```

```c#
public static extern bool ChangeServiceConfig(SC_HANDLE hService, ServiceTypes nServiceType, ServiceStartType nStartType, ServiceErrorControlType nErrorControl,
			[Optional] string lpBinaryPathName, [Optional] string lpLoadOrderGroup, out uint lpdwTagId, [In, Optional] string lpDependencies,
			[Optional] string lpServiceStartName, [Optional] string lpPassword, [Optional] string lpDisplayName);
```

The `CreateService` function has a similar signature, and this function correctly uses the `NullTermStringArrayMarshaler`, allowing one to pass in an array of strings.

```c#
public static extern SafeSC_HANDLE CreateService(SC_HANDLE hSCManager, string lpServiceName, [Optional] string lpDisplayName, uint dwDesiredAccess, ServiceTypes dwServiceType,
			ServiceStartType dwStartType, ServiceErrorControlType dwErrorControl, string lpBinaryPathName, [Optional] string lpLoadOrderGroup, out uint lpdwTagId,
			[In, Optional, MarshalAs(UnmanagedType.CustomMarshaler, MarshalTypeRef = typeof(NullTermStringArrayMarshaler), MarshalCookie = "Auto")] string[] lpDependencies,
			[Optional] string lpServiceStartName, [Optional] string lpPassword);
```

**What code is involved**
https://github.com/dahall/Vanara/blob/3e1596ba7f60f6478e9efd0d5c1b30d102df9439/PInvoke/Security/AdvApi32/WinSvc.cs#L1443

**Expected behavior**
Given this would be a breaking change, and only impacts users who need to supple multiple service dependencies, perhaps a new overload could be added that takes an array for `lpDependencies` as a parameter?

Alternatively is a there a helper class available that can convert a string array into the required format?

**Comment by dahall** [comment]
It is fixed and you can just supply a string array. The current `string` parameter had the potential for memory overruns so a breaking change is justified. Updated build should be available shortly on AppVeyor and published on NuGet in a week or so.

**Comment by ryannewington** [comment]
you rock David!
