### ISSUE TITLE
gdiplus apis support

### ISSUE THREAD

**Issue by luojunyuan** [dahall/Vanara#306]
Can we have a port for gdiplus.dll? I don't see it in these packages. I can find it on pinvoke.net. I don't know if any trouble or is that a massive work for porting.

https://docs.microsoft.com/en-us/windows/win32/gdiplus/-gdiplus-class-gdi-reference

**Comment by dahall** [comment]
After starting on it, I found that the Microsoft.Drawing.Common package already had a very complete implementation.

**Comment by luojunyuan** [comment]
Thanks for your reply and the great work! Now I'm trying to work on how to draw image on a win32 window with System.Drawing.
