### ISSUE TITLE
Possible issue with Pack=4 on AdvApi32.TRUSTEE

### ISSUE THREAD

**Issue by lennartb-** [dahall/Vanara#307]
**Describe the bug**
First of all, I can supply a sample project if required, it's a bit too large to trim down to post inline, since it involves creation of an `AppContainer` and sandboxing an application. I tried to get `AdvApi32.SetEntriesInAcl()` working to update the ACL on a file with a SID from a `AdvApi32.SafeAllocatedSID`. No matter how carefully I checked all parameters, I would always receive an error 87 ("Parameter is incorrect"). I finally tried to replicate it without Vanara and managed to get it working instantly. I _think_ I drilled down the issue to the StructLayout definition on `AdvApi32.TRUSTEE`. There, `Pack = 4` is specified. In my manual implementation, no Packing (it defaults to 0 I think) is specified, and as soon as I set it to 4 I get the same issue. On [pinvoke.net](https://www.pinvoke.net/default.aspx/Structures/TRUSTEE.html) it's also 0 (but 4 for VB .NET?).

**What code is involved**
I hope this make somewhat sense:

```
 private void GrantFolderAccess(AdvApi32.SafeAllocatedSID appContainerSid)
 {
     var file = @"C:\Users\YourUserName\Desktop\test.txt";
     var type = AdvApi32.SE_OBJECT_TYPE.SE_FILE_OBJECT;

     var access = new AdvApi32.EXPLICIT_ACCESS
     {
         grfAccessMode = AdvApi32.ACCESS_MODE.SET_ACCESS,
         grfAccessPermissions = (uint)Native.ACCESS_MASK.SHARE_ACCESS_FULL,
         grfInheritance = AdvApi32.INHERIT_FLAGS.SUB_CONTAINERS_AND_OBJECTS_INHERIT,
         Trustee = new AdvApi32.TRUSTEE
         {
             MultipleTrusteeOperation = AdvApi32.MULTIPLE_TRUSTEE_OPERATION.NO_MULTIPLE_TRUSTEE,
             ptstrName = appContainerSid.DangerousGetHandle(),
             TrusteeForm = AdvApi32.TRUSTEE_FORM.TRUSTEE_IS_SID,
             TrusteeType = AdvApi32.TRUSTEE_TYPE.TRUSTEE_IS_WELL_KNOWN_GROUP
         }
     };

     // Succeeds
     var info = AdvApi32.GetNamedSecurityInfo(file, type, SECURITY_INFORMATION.DACL_SECURITY_INFORMATION, out var ppsidOwner, out var ppsidGroup, out var ppDacl, out var ppSacl, out var ppSecurityDescriptor);

     var pListOfExplicitEntries = new[] { access };

     // Returns 87
     var entr = AdvApi32.SetEntriesInAcl(1, pListOfExplicitEntries, ppDacl.DangerousGetHandle(), out var newAcl);
 }

```

**Expected behavior**
`SetEntriesInAcl` should succeed.

Using VS 22 17.2.6 (64 Bit) on Win11.

**Comment by dahall** [comment]
Thank you. See notes for commit for details on fix. Will be in next release (within 2 weeks) and can be accessed shortly on AppVeyor build (see readme.md).
