### ISSUE TITLE
Unable to find an entry point named 'GetPackageInfo2' and 'GetStagedPackageOrigin' in DLL 'kernel32.dll'.

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#308]
**Describe the bug**
Unable to find an entry point named 'GetPackageInfo2' and 'GetStagedPackageOrigin' in DLL 'kernel32.dll'. **System.EntryPointNotFoundException** was threw.

**What code is involved**
```csharp
Kernel32.GetPackageInfo2(Reference, Convert.ToUInt32(Kernel32.PACKAGE_FLAGS.PACKAGE_FILTER_HEAD | Kernel32.PACKAGE_FLAGS.PACKAGE_FILTER_DIRECT), Kernel32.PackagePathType.PackagePathType_Install, ref InfoBufferLength, IntPtr.Zero, out _);
Kernel32.GetStagedPackageOrigin(PackageFullName, out Kernel32.PackageOrigin Origin).Succeeded
```

**Comment by dahall** [comment]
These functions were introduced in Windows 10 and 8.1 respectively. Are you seeing this exception on earlier systems?

**Comment by zhuxb711** [comment]
Thanks
