### ISSUE TITLE
WTSSendMessage not sending full message

### ISSUE THREAD

**Issue by ctc-aanzalone** [dahall/Vanara#309]
**Describe the bug**
Sending a message with WTSSendMessage doesnt send the full text of either title or body.

**What code is involved**
*I dont get why this code isnt being formatted correctly*
`            string title = "123456789";
            string message = "123456789";
            var handle = WTSOpenServerEx("<RDSESSIONHOST>");
            if (handle.IsInvalid || !WTSSendMessage(handle, (uint)sessionId, title, title.Length, message, message.Length, 0, 0, out uint response, false))
                return 0;
            handle.Close();`

Also tried the above with null terminating the strings and behaves the same.

**Expected behavior**
Send the entirety of the title / message. 

**Screenshots**
This is what is received on the server.
![mstsc_3uKiuRkKKM](https://user-images.githubusercontent.com/83742059/184518301-05617801-e788-4e65-8007-592ed56bbee0.png)

This works perfect inplace of the one you use in your library.
`        [DllImport("wtsapi32.dll", SetLastError = true)]
        static extern bool WTSSendMessage(
            IntPtr hServer,
            [MarshalAs(UnmanagedType.I4)] int SessionId,
            String pTitle,
            [MarshalAs(UnmanagedType.U4)] int TitleLength,
            String pMessage,
            [MarshalAs(UnmanagedType.U4)] int MessageLength,
            [MarshalAs(UnmanagedType.U4)] int Style,
            [MarshalAs(UnmanagedType.U4)] int Timeout,
            [MarshalAs(UnmanagedType.U4)] out int pResponse,
            bool bWait);`

This has been tested from Windows 10 pro to Windows Server 2019 Remote Desktop Session Host as well as Windows 10 Pro client OS.

**Comment by DexterWoo** [comment]
Guess the length there stands for size in bytes. try (length+1)*2

**Comment by AaronAnz** [comment]
Well I get that I can do that, but I feel like the import should just be changed so you don't need to do that.

**Comment by ctc-aanzalone** [comment]
Well I get that I can do that, but I feel like the import should just be changed so you don't need to do that.

**Comment by dahall** [comment]
The Microsoft documentation for that function defines both `TitleLength` and `MessageLength` parameters as "the length, in bytes, of the __ string". For ANSI, string.Length and byte length are equal. For Unicode, @DexterWoo 's comment is applicable. For these situations, where the function has both ANSI and Unicode versions, you can use the helper `Vanara.Extensions.StringHelper.GetByteCount` function as follows:
```cs
using Vanara.Extensions;

WTSSendMessage(handle, (uint)sessionId, title, title.GetByteCount(), message, message.GetByteCount(), 0, 0, out uint response, false);
```
