### ISSUE TITLE
BackgroundCopyManager.Version is always 0.0

### ISSUE THREAD

**Issue by OwnageIsMagic** [dahall/Vanara#311]
**Describe the bug**
`sysnative` dir only exist in WoW64 mode, on real x64 or x86 version selection always fails.
**What code is involved**
https://github.com/dahall/Vanara/blob/eb7f91970c065cd606882fd72de5b02a8da17131/BITS/BackgroundCopyManager.cs#L38

**Comment by dahall** [comment]
I have committed fixes to all three of your issues. Will you test and confirm they are working for you? You can get pre-release NuGet packages from the AppVeyor feed (see main readme).

**Comment by OwnageIsMagic** [comment]
I'm actually maintaining private fork for net40-WinXP and already fixed it by myself, but was to lazy to extract a patch.
btw, `GetVersionInfo` can throw, leaving process in corrupted state.
Also using `%SystemRoot%` is more reliable (user can unset `%windir%` https://answers.microsoft.com/en-us/windows/forum/all/accidentally-delete-windir-in-system-variable/6b94f890-8bd2-43e1-afe6-12dfbfa1e789)
and you can replace `IsWow64Process` with `Environment.Is64BitProcess != Environment.Is64BitOperatingSystem`

**Comment by OwnageIsMagic** [comment]
I resolved it via querying COM server dll `HKEY_CLASSES_ROOT\CLSID\{5CE34C0D-0DC9-4C1F-897C-DAA1B78CEE7C}\InProcServer32` ([uuid of IBackgroundCopyManager](https://github.com/wine-mirror/wine/blob/bd5cdef5dd2888e9b914436b792022a69e28ab4c/include/bits.idl#L371))
so it also handles x64-on-ARM

**Comment by dahall** [comment]
And then you don't bother checking WOW status? That registry key always provides a valid path regardless of 32/64/WOW?

**Comment by OwnageIsMagic** [comment]
It points to path from where COM server should be loaded, so it ought to be valid path.
-------
--------------------------------------------
| win10-x64 | `C:\Windows\System32\BitsProxy.dll` |

**Comment by OwnageIsMagic** [comment]
It points to path from where COM server should be loaded, so it ought to be valid path.

| | |
---|---
win10-x64 | `C:\Windows\System32\BitsProxy.dll`
win10-wow64 | `C:\Windows\SysWOW64\BitsProxy.dll`
winXp-x86 | `C:\Windows\SysWOW64\qmgrprxy.dll`

The one thing I worry about is that https://docs.microsoft.com/en-us/windows/win32/bits/connecting-to-the-bits-service uses `CLSCTX_LOCAL_SERVER`, so it shoud be  `LocalServer32` reg key to check, but on all available to me systems there is only `InProcServer32` so, as always never trust MSDN samples.

**Comment by OwnageIsMagic** [comment]
`ToString()` usually doesn't return `null`. You probably meant `?.`.
