### ISSUE TITLE
HTTPAPI bug

### ISSUE THREAD

**Issue by williamlzw** [dahall/Vanara#318]
.net 6.0

    var ret = HttpInitialize(HTTPAPI_VERSION.HTTPAPI_VERSION_2, HTTP_INIT.HTTP_INITIALIZE_SERVER | 
    HTTP_INIT.HTTP_INITIALIZE_CONFIG);
      if(ret != Vanara.PInvoke.Win32Error.NO_ERROR)
      {
          return false;
      }
      ret = HttpCreateServerSession(HTTPAPI_VERSION.HTTPAPI_VERSION_2, out m_sessionID, 0);//System.AccessViolationException:“Attempted to read or write protected memory. This is often an indication that other memory is corrupt.”
      if (ret != Vanara.PInvoke.Win32Error.NO_ERROR)
      {
          return false;
      }

**Comment by dahall** [comment]
What's the error and which function causes it?

**Comment by dahall** [comment]
I have committed the fix and the package should be available on AppVeyor shortly (see home page) and in NuGet in the next week.
