### ISSUE TITLE
Join Project With AArnott/pinvoke?

### ISSUE THREAD

**Issue by bormm** [dahall/Vanara#32]
I am currently working on a project that needs some Win32 API access from c#. I've chosen the Arnott/pinvoke project now, just because it covers a lot, is actively maintained AND had the most downloads. Your projects covers the same area, maybe not will full identical functionality.
Maybe with some other philosophy. I hadn't the time to deeply find differences.

Have thought about joining your project with the Arnott/pinvoke? For me it looks like the pinvoke has a lot of contributors and pull request are handled very positive and with good feedback.

Best wishes
Marco

**Comment by dahall** [comment]
This project came out my need for a large PInvoke library. I looked hard at AArnott's project, and even corresponded with him. In the end, I decided to do my own as I was looking for a less purist approach and more of a functionally useful library. I likely will not join that project due to this difference in approaches.

**Comment by bormm** [comment]
Thanks for your response. I understand your reasons, and checked some more of your code.

But at the end the P/Invoke part is very similar in both projects. Which of course is technical requirement, because the WIN32-API is how it is.

For example: Both librarys provide a P/Invoke for CreateProcess which still let the dev/user handle translation of WIN32 error codes into an exception. I even don't see another small feature layer for that, that would throw a exception if creating a process fails. 

I understand that parts like your NetworkConnection classes are not in the scope of Arnott/pinvoke. But the P/Invoke stuff, which is already a lot of very similar work and code and potential conflict and confusion in a app that consumes both.

**Comment by dzmitry-lahoda** [comment]
#6 asks same. And https://github.com/AArnott/pinvoke has more stars. And https://github.com/AArnott/pinvoke is more lower level.   At least you could keep #32 open for discussion and voting.

**Comment by bormm** [comment]
Thanks for this hint @dzmitry-lahoda . Shame on me I have not searched before opening this issue.
At the end it is @dahall project and he has to decided how the direction of his project goes, even we do not agree with that or see it the same way.
