### ISSUE TITLE
http api bug:FROMMEMORY

### ISSUE THREAD

**Issue by williamlzw** [dahall/Vanara#320]
.net6

  FROMMEMORY index = new FROMMEMORY();
  string text = "123";
  index.pBuffer = Marshal.StringToHGlobalAuto(text);
System.TypeLoadException:“Could not load type 'UNION' from assembly 'HttpApiTool, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.”

**Comment by dahall** [comment]
Thank you. I just committed the fix and updated packages should be available on AppVeyor shortly (see home page for details) and released on NuGet within the week.

I would strongly recommend you use the HTTP_DATA_CHUNK constructors here rather than rolling your own.
