### ISSUE TITLE
ws2_32 bug: SOCKADDR_IN  ,AF_UNSPEC not support?

### ISSUE THREAD

**Issue by williamlzw** [dahall/Vanara#321]
```cs
var ret = (SOCKADDR_IN)(SOCKADDR.CreateFromStructure(m_request.Address.RemoteAddress)); 
//System.InvalidCastException:“Specified cast is not valid.”

ws2_32
    public static explicit operator SOCKADDR_IN(SOCKADDR addr)
    {
        if (addr.sa_family != ADDRESS_FAMILY.AF_INET) //AF_UNSPEC not support?
        {
             throw new InvalidCastException();
        }
        return addr.handle.ToStructure<SOCKADDR_IN>();
    }
```

**Comment by dahall** [comment]
What you're seeing is that the family (IPv4 or IPv6) exposed by your `m_request.Address.RemoteAddress` value must by IPv4 (AF_INET). What is the type of that value?

**Comment by williamlzw** [comment]
The client I use WinInet to access the httpapi server, the sa_family type received by the server is AF_UNSPEC.

public static explicit operator SOCKADDR_IN(SOCKADDR addr)
    {
        if (addr.sa_family != ADDRESS_FAMILY.AF_INET || addr.sa_family != ADDRESS_FAMILY.AF_UNSPEC)
        {
             throw new InvalidCastException();
        }
        return addr.handle.ToStructure<SOCKADDR_IN>();
    }

**Comment by dahall** [comment]
Thanks for the explanation. I've updated the code.
