### ISSUE TITLE
TB_GETBUTTON does not populate tooltip button information struct

### ISSUE THREAD

**Issue by rmeshksar** [dahall/Vanara#322]
Hi, 
I have created a Windows Forms application with a toolbar component which has 3 buttons.
I would like to use SendMessage with TB_GETBUTTON message to fetch the first button information.
Here is my code:

```csharp
var tb = new ComCtl32.TBBUTTON();

var buttonCount = User32.SendMessage(mainToolbar.Handle, (uint)ComCtl32.ToolbarMessage.TB_BUTTONCOUNT, (IntPtr)0, 0);
var getButton = User32.SendMessage(mainToolbar.Handle, ComCtl32.ToolbarMessage.TB_GETBUTTON, 0, ref tb);

lblButtonCount.Text = buttonCount.ToString();
lblSuccess.Text = (getButton.ToInt32() != 0).ToString();
lblDWData.Text = tb.dwData.ToString();
lblFSStyle.Text = tb.fsStyle.ToString();
lblFSState.Text = tb.fsState.ToString();
lbliBitmap.Text = tb.iBitmap.ToString();
```

When I observe tb struct. all properties are zero and have not been populated even though getButton variable is 1 which means success.

The output looks like this:
![image](https://user-images.githubusercontent.com/5131689/192107826-1072f90e-41c4-4004-84f6-63d8e4e03864.png)

I created my own class (in naïve implementation) that looks like this:
```csharp
public sealed class Win32
{
    [DllImport("user32.dll", CharSet = CharSet.Auto)]
    public extern static int SendMessage(IntPtr hwnd, int msg, int wParam, int lParam);

    [DllImport("user32.dll", CharSet = CharSet.Auto)]
    public extern static unsafe int SendMessage(IntPtr hwnd, int msg, int wParam, void* lParam);
}
```

And when I use this class in the same form like this:
```csharp
var tb = new ComCtl32.TBBUTTON();

var buttonCount = Win32.SendMessage(mainToolbar.Handle, (int)ComCtl32.ToolbarMessage.TB_BUTTONCOUNT, 0, 0);

unsafe
{
    var getButton = Win32.SendMessage(mainToolbar.Handle, (int)ComCtl32.ToolbarMessage.TB_GETBUTTON, 0, &tb);
    
    lblButtonCount.Text = buttonCount.ToString();
    lblSuccess.Text = (getButton != 0).ToString();
    lblDWData.Text = tb.dwData.ToString();
    lblFSStyle.Text = tb.fsStyle.ToString();
    lblFSState.Text = tb.fsState.ToString();
    lbliBitmap.Text = tb.iBitmap.ToString();
}
```

It is populating the struct correctly:
![image](https://user-images.githubusercontent.com/5131689/192107978-b81bdfe3-3b70-420f-8ef7-6c29146f5abd.png)

Am I missing anything here?
Thanks.

**Comment by dahall** [comment]
Will you try the following using Vanara (not your class) and let me know if it works?
```cs
var tb = new ComCtl32.TBBUTTON();

var buttonCount = User32.SendMessage(mainToolbar.Handle, ComCtl32.ToolbarMessage.TB_BUTTONCOUNT).ToInt32();
var getButton = User32.SendMessage(mainToolbar.Handle, ComCtl32.ToolbarMessage.TB_GETBUTTON, new IntPtr(0), ref tb);
```

**Comment by rmeshksar** [comment]
Unfortunately it did not make any difference. Still after the execution of getButton, tb struct is the same as a new object and not populated with button data.

**Comment by dahall** [comment]
Hm. Would you mind zipping up your test project and sending it to me so I can troubleshoot?

**Comment by rmeshksar** [comment]
Here is the project I created
[ToolbarMessage.zip](https://github.com/dahall/Vanara/files/9647990/ToolbarMessage.zip)

**Comment by rmeshksar** [comment]
FYI, I downgraded to Vanara version 3.0.0 and it works fine.

**Comment by rmeshksar** [comment]
In fact it works fine until version 3.2.21 and fails in 3.3.0

**Comment by dahall** [comment]
Thanks. I'll look at the zip and what's changed since 3.2.21.

**Comment by dahall** [comment]
Found the problem. I've committed the fix and it will go out in the next week into NuGet and within minutes on AppVeyor.
