### ISSUE TITLE
How to get a IFolderView2 instance of the desktop?

### ISSUE THREAD

**Issue by LegendaryB** [dahall/Vanara#325]
Hey @dahall,

my use case is that I need to be able to hide and show the windows desktop icons. This should be possible by calling the "SetCurrentFolderFlags" method of a IFolderView2 instance. But how can I get it by using vanara? I tried around with ShellFolder and hoped, that there is a extension method or something like that to get it but seems like not.

Also is it possible to hide the Taskbar?

Any ideas?

Kind Regards

**Comment by dahall** [comment]
That interface is exposed via the `ShellBrowserViewHandler` class which is retrieved using `ShellBrowser.ViewHandler`. It exposes `IFolderView` through `FolderView` which can be cast to `IFolderView2`.
```cs
ShellBrowser browser = new();
browser.BrowseObject(ShellFolder.Desktop.PIDL.DangerousGetHandle(), SBSP.SBSP_ABSOLUTE);
var ifv2 = browser.ViewHandler.FolderView as IFolderView2;
ifv2.SetCurrentFolderFlags(...);
```

**Comment by LegendaryB** [comment]
@dahall Thank you. Unfortunately the ViewHandler property is marked as protected and therefor not directly callable

**Comment by dahall** [comment]
Right. My mistake. Little more manual, but here you go.
```cs
var sfvCreate = new SFV_CREATE()
{
	cbSize = (uint)Marshal.SizeOf(typeof(SFV_CREATE)),
	pshf = ShellFolder.Desktop.IShellFolder,
};
SHCreateShellFolderView(sfvCreate, out IShellView shellView).ThrowIfFailed();
IFolderView2 FolderView2 = (IFolderView2)shellView;
```
