### ISSUE TITLE
TB_GETBUTTONINFOA and TB_SETBUTTONINFOA not working on 64bit application

### ISSUE THREAD

**Issue by rmeshksar** [dahall/Vanara#327]
Hi,
I have an application and would like to modify some style of buttons of a toolbar. 
I raised another bug that I could not assign value to fsStyle but I fixed that on my local.
(https://github.com/dahall/Vanara/issues/326)

The issue is that it works fine when application is on 32bit but not 64bit.

You can compare the results of SendMessage for TB_GETBUTTON, TB_GETBUTTONINFOA and TB_SETBUTTONINFOA here:

![image](https://user-images.githubusercontent.com/5131689/194136474-210d113d-7ee3-44cc-b644-a63649f371c6.png)

![image](https://user-images.githubusercontent.com/5131689/194136499-98effad3-8ca7-4a26-941d-0b0700aa96f0.png)

And here is the code:

```csharp
private void btnVanada_Click(object sender, EventArgs e)
{
    var tb = new ComCtl32.TBBUTTON();
    var tbi = new ComCtl32.TBBUTTONINFO();

    lblResult_TB_GETBUTTON.Text = User32.SendMessage(mainToolbar.Handle, ComCtl32.ToolbarMessage.TB_GETBUTTON, 0, ref tb).ToString();

    tbi.cbSize = (uint)Marshal.SizeOf(tbi);
    tbi.dwMask = ComCtl32.TBIF.TBIF_STYLE;
    lblResult_TB_GETBUTTONINFOA.Text = User32.SendMessage(mainToolbar.Handle, ComCtl32.ToolbarMessage.TB_GETBUTTONINFOA, tb.idCommand, ref tbi).ToString();
    
    tbi.fsStyle = tbi.fsStyle | ComCtl32.ToolbarStyle.BTNS_WHOLEDROPDOWN;
    lblResult_TB_SETBUTTONINFOA.Text = User32.SendMessage(mainToolbar.Handle, ComCtl32.ToolbarMessage.TB_SETBUTTONINFOA, tb.idCommand, ref tbi).ToString();

}
```

And here is the project I created.

[ToolbarMessage.zip](https://github.com/dahall/Vanara/files/9718139/ToolbarMessage.zip)

**Comment by rmeshksar** [comment]
I noticed this line of code:
https://github.com/dahall/Vanara/blob/bdf07f10f59c02669f6eef79a7b17734738e6c5d/PInvoke/ComCtl32/CommCtrl.Toolbar.cs#L3693

If I remove Pack=1 from StructLayout it works in both 32bit and 64bit.

Is there going to be any issue removing it?

**Comment by dahall** [comment]
All good
