### ISSUE TITLE
Add SecureZeroMemory

### ISSUE THREAD

**Issue by sclarke81** [dahall/Vanara#33]
There are a number of methods that suggest calling SecureZeroMemory e.g. CredUIPromptForCredentials. I can't find anywhere that you've provided this (I might be missing it)? I think it would be good to provide it. Perhaps something like this:

```csharp
/// <summary>
/// Fills a block of memory with zeros.
/// </summary>
/// <remarks>
/// SecureZeroMemory is an alias of RtlSecureZeroMemory, an inline function defined in
/// WinBase. Neither SecureZeroMemory or RtlSecureZeroMemory are exported as a function from
/// a dll. This method is intended to mimic it's behaviour.
/// </remarks>
/// <param name="pointer">
/// A pointer to the starting address of the block of memory to fill with zeros.
/// </param>
/// <param name="bufferSize">The size of the block of memory to fill with zeros, in bytes.</param>
private static void SecureZeroMemory(IntPtr pointer, uint bufferSize)
{
    Marshal.Copy(new byte[bufferSize], 0, pointer, (int)bufferSize);
}
```

Would it be possible to update the function comments to point to the new method e.g. InteropServices.SecureZeroMemory?

**Comment by dahall** [comment]
What would you think about just exposing the Zero method on all SafeAllocatedMemoryHandle derivatives? .NET already zeroes out all newly allocated memory, so this method is only useful to clear bits that you have changed.

**Comment by dahall** [comment]
Looking at it, I will just expose that method. Simple enough and makes it possible to work with memory allocated outside of my helper classes.

**Comment by sclarke81** [comment]
It sounds like a sensible plan to me, but I have to confess that I haven't really familiarised myself with your helper classes. Maybe you could help me out? How would you use them for the output auth buffer the following example?

'''csharp
Win32Error promptForCredentialsResult = CredUI.CredUIPromptForWindowsCredentials(
    credUI,
    Win32Error.ERROR_SUCCESS,
    ref pulAuthPackage,
    IntPtr.Zero,
    0,
    out IntPtr ppvOutAuthBuffer,
    out uint pulOutAuthBufferSize,
    ref pfSave,
    dwFlags);
'''

**Comment by dahall** [comment]
Ok. I have posted the code updates to GitHub and will include them in the next (2.2.0) release. Effectively I added a FillMemory method to the Vanara.Extensions.InteropExtensions static class and as a method to the SafeAllocatedMemoryHandle base class.

First, know that for that particular method, I have already wrapped it in a WinForms control which can be found in Vanara.Windows.Forms.CredentialsDialog that will automatically switch between the old and new UI.

From that code, you can see the direct answer to your question: https://github.com/dahall/Vanara/blob/master/WIndows.Forms/Dialogs/CredentialsDialog/CredentialsDialog.cs

**Comment by sclarke81** [comment]
This looks good. Thanks for including it. I've got a couple of thoughts after looking through the code for the dialog:

1. I think that you should be calling `Zero` in the `Dispose` of `AuthenticationBuffer`.
1. `AuthenticationBuffer` is `IDisposable` but you're not calling `Dispose` when you use it in the `RunDialog` method of the dialog. I think you should wrap `buf` and `outAuth` in `using`s.

**Comment by dahall** [comment]
Good suggestions. I've implemented both.

**Comment by sclarke81** [comment]
Awesome. I'm glad it helped.
