### ISSUE TITLE
Events caught by ShellItemChangeWatcher on AppsFolder

### ISSUE THREAD

**Issue by AbraxasDMG** [dahall/Vanara#330]
Hi.

Thank you very much for maintaining this project!

I bumped into this library while testing some things with Shell:AppsFolder virtual folder. I tried to set up watcher but I get none of the expected events (and one unexpected). It could be that this is a limitation of the APIs exposed by OS. However, I just wanted to check if this might be a bug.

I put the watcher on the form and left all the defaults (which means NotifyFilter has a value of AllEvents).
On form load I have added:
```
shellItemChangeWatcher1.Item = new ShellFolder(Shell32.KNOWNFOLDERID.FOLDERID_AppsFolder);
shellItemChangeWatcher1.EnableRaisingEvents = true;
```

1. When I uninstall something, I see it in disappear from the explorer's view of Shell:AppsFolder, but I get no ItemDeleted event. 
2. When I install something, I see it in appear in the explorer's view of Shell:AppsFolder, but I don't get ItemCreated event. Instead, to my surprise, there is ItemUpdated event (this app did not exist before).

Is this behavior expected (as designed)?

If AppsFolder cannot be monitored in this way, is there any advice how to do it instead?
Thanks in advance!

**Comment by dahall** [comment]
I'll do some testing and let you know what I find. Thanks for the detail so I can reproduce.

**Comment by dahall** [comment]
The nature of this particular virtual folder is that it only receives a "Folder Updated" event (`ChangeFilters.FolderUpdated = SHCNE.SHCNE_UPDATEDIR`) when an app is added or removed.
