### ISSUE TITLE
WinSpool.DeviceCapabilities nullable pDevMode 

### ISSUE THREAD

**Issue by cezio** [dahall/Vanara#331]
`WinSpool.DeviceCapabilities(string pDevice, string pPort, WinSpool.DC fwCapability, in DEVMODE pDevMode)` call doesn't allow nullable `pDevMode` param. This is not consistent with W32 api, where `pDevMode` param is a pointer, and can be NULL: https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-devicecapabilitiesa

According to documentation, passing `NULL` for `pDevMode` param allows to retrieve numeric values related to specific device capabilities flag passed as `fwCapability`.

**Comment by dahall** [comment]
Just pushed a commit with a fix. It will get released this next onto NuGet and will be available on the AppVeyor feed within minutes.
