### ISSUE TITLE
Possibly wrong parameter signature in WinVerifyTrustEx

### ISSUE THREAD

**Issue by TechInterMezzo** [dahall/Vanara#334]
**Describe the bug and how to reproduce**
I am not sure about this one, but I think regarding the documentation, that the WINTRUST_DATA struct should be passed as a pointer and not the struct itself.

**What code is involved**

https://github.com/dahall/Vanara/blob/e97896fda6a5ff8e1c3b8c04029f076d6a7426a7/PInvoke/WinTrust/WinTrust.cs#L1083

**Expected behavior**

Use the in keyword for the pWinTrustData parameter.

**Comment by dahall** [comment]
WINTRUST_DATA is a managed class and is therefore passed by reference like the native signature. I believe it is correct. Is it producing an error or incorrect result?

**Comment by TechInterMezzo** [comment]
You are right. It's working. I did something wrong in my code and thought WINTRUST_DATA was a struct.
I honestly never used managed classes as parameters for P/Invoke.
Thank you for the fast response.
