### ISSUE TITLE
Nuget package binaries no longer signed?

### ISSUE THREAD

**Issue by TamBuiWork** [dahall/Vanara#335]
**Describe the bug and how to reproduce**

When downloading the latest (as of this writing) 3.4.10 nuget package for Vanara.Core or Vanara.Pinvoke* packages, I'm seeing that none of the binaries are signed.

**What code is involved**

N/A

**Expected behavior**

I was expecting the binaries to be signed, based off of this code check-in message:

![image](https://user-images.githubusercontent.com/87879060/199285418-2a0363ae-98dd-4f68-9989-3231fadfeeb7.png)

But I'm not seeing any digital signatures when I open the properties of the dll's.

**Screenshots**

![image](https://user-images.githubusercontent.com/87879060/199284995-c05f592d-1340-4ce7-9952-c102f8ec1234.png)

This might be a potential security vulnerability if these libraries are used in other applications. Has this always been the case that these binaries are not signed, or was this working at one point in time?

**Comment by dahall** [comment]
It appears you are correct. I'll get it resolved.

**Comment by dahall** [comment]
I have sample tested a number of the assemblies in the build with the "sn.exe" tool and all of them show they are signed. I wonder if there is a problem with showing that tab in Explorer Properties under our versions of Windows.

**Comment by TamBuiWork** [comment]
@dahall 

Perhaps I wasn't clear on my initial question. I was asking whether or not the Vanara dll's from the nuget package are digitally signed, not whether they are strongly named. 

Most resources I've found online say to check the Properties page like I had done, or use the 'signtool.exe' from Visual Studio to check if binaries are digitally signed:
[Link: scroll down to the part where it says 'Strong Names and Digital Signatures are Orthogonal Concerns'](https://blog.codingoutloud.com/2010/03/13/three-ways-to-tell-whether-an-assembly-dl-is-strong-named/)

Here's what I get when I run 'signtool.exe' from a VS command prompt:

![image](https://user-images.githubusercontent.com/87879060/200064158-624ae000-a1c5-4205-aaba-fa4bc5f27873.png)

So again my apologies if I was unclear. Have the nuget packages ever been digitally signed, as opposed to just strongly named?

Best regards,
Tam

**Comment by dahall** [comment]
No. Just strongly named.
