### ISSUE TITLE
Allow to use custom IFileOperation in ShellFileOperations

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#336]
**Describe the additions or enhancements you'd like**
We would like to use IFileOperation by myself because we want to create a IFileOperation with COM Elevation

```csharp
public / protected ShellFileOperations(IFileOperation Op)
{
 
}
```

**Comment by dahall** [comment]
Please see the referenced commit. Does this address your issue?

**Comment by zhuxb711** [comment]
Thanks, that's it
