### ISSUE TITLE
Pull request #332 not updated in Nuget package Vanara.PInvoke.User32 3.4.10

### ISSUE THREAD

**Issue by 5cover** [dahall/Vanara#337]
**Describe the bug and how to reproduce**

The SetPointSize extension method is still broken.

**What code is involved**

Pull request #332 modified the signature of the Vanara.Extensions.LOGFONTExtension.SetPointSize method.
This change is not present in the Nuget package Vanara.PInvoke.User32 version 3.4.10.
I decompiled the assembly, the method has not changed.

#### Sample code
```cs
using Vanara.PInvoke;
using Vanara.Extensions;

namespace ConsoleTest;

public static class Program
{
    [STAThread]
    public static void Main()
    {
        LOGFONT l = new();
        Console.WriteLine(l.lfHeight);
        l.SetPointSize(10);
        Console.WriteLine(l.lfHeight);
    }
}
```

**Expected output**
```
0
-13
```

**Actual output**
```
0
0
```

**Comment by dahall** [comment]
The history shows you deleted the PR on 24 Oct after I had accepted it. That is why it was missing in the push. Please resubmit it and I'll get it into 3.4.11.

**Comment by 5cover** [comment]
> The history shows you deleted the PR on 24 Oct after I had accepted it. That is why it was missing in the push. Please resubmit it and I'll get it into 3.4.11.

sorry about that, i'm a noob with git

**Comment by dahall** [comment]
On new repository pulls it won't show up if you've deleted the PR.
