### ISSUE TITLE
Missing `[Flags]` on some bitwise flag enums

### ISSUE THREAD

**Issue by peppy** [dahall/Vanara#339]
Hi,

I've been looking into potentially using this library for our project, but noticed that many enums which are intended to be used as bitwise flags are not marked with `[Flags]` and as such, cause warning with our inspection settings. Is this just an oversight, and if so would it be beneficial to pull request the addition of `[Flags]` where applicable?

Examples I found (related to our proposed usage):

`EXECUTION_STATE`:

https://github.com/dahall/Vanara/blob/6e77cebd0633f5acf8ec53d898e4e30dd27b1d33/PInvoke/Kernel32/WinBase.ProcessThread.cs#L21

`CREATE_WAITABLE_TIMER_FLAG`:

https://github.com/dahall/Vanara/blob/6e77cebd0633f5acf8ec53d898e4e30dd27b1d33/PInvoke/Kernel32/SynchApi.cs#L94
(this is also missing a value `CREATE_WAITABLE_TIMER_HIGH_RESOLUTION = 0x00000002`

Thanks!

**Comment by dahall** [comment]
It is an oversight. Please submit a PR for any you find and I'll accept and push an update.
