### ISSUE TITLE
nuget package Vanara.PInvoke.User32_Gdi not found PeekMessage

### ISSUE THREAD

**Issue by noctwolf** [dahall/Vanara#35]
Vanara.PInvoke.User32 and Vanara.PInvoke.User32.Gdi

please help
thanks

**Comment by dahall** [comment]
https://www.nuget.org/packages/Vanara.PInvoke.User32.Gdi/
and
https://www.nuget.org/packages/Vanara.PInvoke.User32/

**Comment by noctwolf** [comment]
Thanks for the reply, but the problem is not solved

github source, class User32_Gdi include PeekMessage
but nuget package, class User32_Gdi not found PeekMessage

**Comment by dahall** [comment]
Sorry. I think I see your issue now. PeekMessage is checked in, but not published yet. I'm testing the new code and should release this week. Look for version 2.2.0.

**Comment by noctwolf** [comment]
Thanks :)
