### ISSUE TITLE
Please provide a function that could be used to get/set ShellItems in NativeClipboard

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#353]
**Is your feature request related to a problem? Please describe.**
No

**Describe the additions or enhancements you'd like**
It would be great if you could provide a way to let us get/set ShellItem(s) through NativeClipboard class easily.
The function like the example below:

```csharp
public void SetShellItems(IEnumerable<ShellItem> Items)
{
    //Set items to underlying clipboard
}

public IEnumerable<ShellItem> GetShellItems()
{
    //Get items from underlying clipboard
}
```

**Comment by dahall** [comment]
Does `Vanara.Windows.Shell.ShellDataObject` have what you want?

**Comment by zhuxb711** [comment]
But ShellDataObject rely on System.Windows.Forms which is not friendly to use if someone who do not use WinForms.

**Comment by dahall** [comment]
Got it. Let me see if I can port the `ShellDataObject` code without the Forms dependencies.

**Comment by zhuxb711** [comment]
Thanks, do you have any demo to tell us how to use ShellDataObject with ShellItem (Includes Get/Set ShellItem and Set ShellItem with something custom data which stored in another clipboard id)

**Comment by dahall** [comment]
I added a couple methods to NativeClipboard. Give them a try and let me know your thoughts.

**Comment by zhuxb711** [comment]
Due to NativeClipboard not working in my project, I have not be able to test that but I reviewed the code, it looks great. https://github.com/dahall/Vanara/issues/355#issuecomment-1359584049

**Comment by dahall** [comment]
I'll see if I can troubleshoot #355 over the next few days.

**Comment by zhuxb711** [comment]
I found some issues, I could not retrieve the ShellItem which I just set into clipboard
```csharp
            IEnumerable<ShellItem> Items = Collection.Select((Item) => new ShellItem(Item.Path));

            try
            {
                NativeClipboard.SetShellItems(Items);

                if (NativeClipboard.GetShellItemArray() is ShellItemArray Array)
                {
                    foreach (ShellItem Item in Array)
                    {
                        System.Diagnostics.Debug.WriteLine($"Shell IDList: {Item.FileSystemPath}");
                    }
                }
                else
                {
                    //Runs to here which means no available Shell IDList Array
                    System.Diagnostics.Debug.WriteLine("No available Shell IDList Array");
                }
            }
            catch (Exception)
            {

            }
            finally
            {
                Items.ForEach((Item) => Item.Dispose());
            }
```

**Comment by dahall** [comment]
The latest AppVeyor package seems to be working. I used this code behind a button in a WinForms project and consistently got what I expected.
```cs
string[] fileNames = new[] { @"C:\file1.txt", @"C:\file2.txt" };
NativeClipboard.SetShellItems(fileNames.Select(ShellItem.Open));
MessageBox.Show(string.Join("\n", NativeClipboard.GetShellItemArray().Select(i => i.FileSystemPath)));
```

**Comment by zhuxb711** [comment]
Demo for you. Could set the ShellItem but could not retrieve them back
[ClipboardTest.zip](https://github.com/dahall/Vanara/files/10325725/ClipboardTest.zip)

**Comment by dahall** [comment]
I think this is now complete.

**Comment by tajbender** [comment]
Maybe these can help:

https://github.com/dahall/Vanara/blob/master/Windows.Shell/ShellObjects/ShellBrowser.cs
https://github.com/dahall/Vanara/blob/master/Windows.Shell/ShellObjects/ShellView.cs

...and least but not least:

https://github.com/electrifier/frozen.winforms.source/tree/main/src/electrifier.Core/WindowsShell

regards, tajbender

**Comment by dahall** [comment]
@tajbender What is your last comment regarding?

**Comment by tajbender** [comment]
> @tajbender What is your last comment regarding?

Oups, sorry. That was the wrong topic 🍶
