### ISSUE TITLE
IFileSystemImage2: BootImageOptionsArray is read-only, and has no assign method unlike original API

### ISSUE THREAD

**Issue by JosephM101** [dahall/Vanara#357]
`IFileSystemImage2.BootImageOptionsArray` only has a `get` modifier; no `set` modifier, which means I cannot make an ISO image with multiple boot entries, which the API is perfectly capable of. [It's even documented]( https://learn.microsoft.com/en-us/windows/win32/api/imapi2fs/nf-imapi2fs-ifilesystemimage2-put_bootimageoptionsarray), so the functionality should exist here, too.

**Comment by dahall** [comment]
I think it is corrected, but don't really have a way to test. You can get an updated NuGet package from AppVeyor (see homepage). Please let me know either way. Thanks.
