### ISSUE TITLE
Are there definitions of WM_MOUSEACTIVATE return codes such as MA_NOACTIVATE?

### ISSUE THREAD

**Issue by fandrei** [dahall/Vanara#358]
**Is your feature request related to a problem? Please describe.**

I looked in the source code and they're mentioned in comments, but I can't find any definitions for these constants.

**Describe the additions or enhancements you'd like**

Just add them, if they don't exist yet.
```
public enum MouseActivateCodes : int
{
   MA_ACTIVATE = 1,
   MA_ACTIVATEANDEAT = 2,
   MA_NOACTIVATE = 3,
   MA_NOACTIVATEANDEAT = 4
}
```

**Comment by dahall** [comment]
Thanks
