### ISSUE TITLE
Add dialog box window styles

### ISSUE THREAD

**Issue by lanyizi** [dahall/Vanara#359]
**Is your feature request related to a problem? Please describe.**
Hi! First of all, thanks for your library and your hard work!
Recently I need to use some dialog box styles for my dialog boxes, such as `DS_SETFONT`, however, those dialog box styles aren't present inside this library, and manually defining them is a bit cumbersome.
https://github.com/dotnet/pinvoke/ Do have these styles defined, however they lack some other stuffs so I'd prefer to continue using this library for `User32.dll` imports.

**Describe the additions or enhancements you'd like**
Can you add these dialog box styles to your library too?
https://learn.microsoft.com/en-us/windows/win32/dlgbox/dialog-box-styles

**Previous work**
If work on these imports have been done, please provide links.
https://github.com/dotnet/pinvoke/blob/main/src/User32/User32+WindowStyles+DialogWindowStyles.cs

**Comment by dahall** [comment]
Added. Should be on AppVeyor shortly and I'll push a new release in the next day or so.
