### ISSUE TITLE
System.Threading package and Theraot.Core package have type conflict

### ISSUE THREAD

**Issue by ccsheller** [dahall/Vanara#36]
I am use Visual Studio 2013 and target .Net 3.5 .

I need some fun supported by Task,Lazy,BlockingCollection and many more.

But when i reference Vanara.PInvoke.IpHlpApi from NuGet, it depend the Theraot.Core package.

So compiler give some errors:

The type 'System.Lazy<T>' exists in both \TaskParallelLibrary.1.0.2856.0\lib\Net35\System.Threading.dll
and \Theraot.Core.2.1.0\lib\NET35\Theraot.Core.dll'

The type 'System.Threading.Tasks.Task<TResult>' exists in both \TaskParallelLibrary.1.0.2856.0\lib\Net35\System.Threading.dll and \Theraot.Core.2.1.0\lib\NET35\Theraot.Core.dll

System.Threading.Tasks.TaskCreationOptions exists in both \TaskParallelLibrary.1.0.2856.0\lib\Net35\System.Threading.dll and \Theraot.Core.2.1.0\lib\NET35\Theraot.Core.dll

......

So I try to modify System.Threading's aliases properties. Too many modifications and the compiler give errors too.

So I try to modify Theraot.Core's aliases properties.  Build  succeeded. 
There may be potential runtime issues.

what is the best way? Thanks.

**Comment by theraot** [comment]
I wrote Theraot libraries with the intentation that you would not need TaskParallelLibrary, the motivation being that TaskParallelLibrary is no longer supported by Microsoft. It appears you are using OmerMor's mirror of the TPL.

If my libraries gives you problems once TaskParallelLibrary is removed, please post the issues on https://github.com/theraot/Theraot/issues

With that said, I am aware that I am not providing PLINQ, for that you will have to wait for the next release.

**Comment by ccsheller** [comment]
Thank's. I update Theraot's version to 2.2.0. It has the class BlockingCollection.
