### ISSUE TITLE
Q: Did you see Windows Phone Link-api?

### ISSUE THREAD

**Issue by tajbender** [dahall/Vanara#361]
Hello, Mr. Hall,

did you ever came across some API to do the magic behind Phone Link' Features?

<img width="630" alt="2022-12-30" src="https://user-images.githubusercontent.com/10961499/210084875-87abb327-863f-4b24-afd4-170d1ca627e5.png">

**Comment by dahall** [comment]
I haven't, but I'm looking for the next library to convert. I'll do some digging to see if MSFT has made the API public. Let me know if you find it first.

**Comment by dahall** [comment]
I just found this project which mentions the APIs being used : https://github.com/BestOwl/MyPhone

**Comment by tajbender** [comment]
Thx a lot!

**Comment by tajbender** [comment]
Oh...

and a `happy new year(🧨);` 😁

**Comment by dahall** [comment]
You too!

**Comment by tajbender** [comment]
I found another interesting Git:

https://github.com/tajbender/scrcpy

> This application mirrors Android devices (video and audio) connected via USB or TCP/IP and allows control using the computer's keyboard and mouse. It does not require root access or an app installed on the device. It works on Linux, Windows, and macOS.

`sndcpy` from the same person also can do Audio-Forwarding.

This way, someone might be able to stream directly from Android to Windows.

**Comment by dahall** [comment]
Looks like most of the libs are Java so not really a fit for Vanara.

**Comment by tajbender** [comment]
> Looks like most of the libs are Java so not really a fit for Vanara.

Thanks for your thoughts, dahall,

you are right, most if not all APIs on the Android side will be using Java, so changes are high that any related Windows API will use Java, too.

I just intended to share the link to `scrpy` for any reference for your Users.

For the mentioned Windows Phone Link API - in the meantime I'm pretty sure these are closed source, especially since it is still growing and getting more features.

e./ Well there is some sort of official Information regarding the API, however, it is not really publicly available:

> Phone Link task continuity is a Limited Access Feature (LAF). 
> To gain access, you will need to get approval from Microsoft to interoperate with the "Link to Windows" package preloaded on Android mobile devices.
> https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/cross-device/phonelink/index.md
