### ISSUE TITLE
VssApi.dll PInvoke package is not published

### ISSUE THREAD

**Issue by CaptainPants** [dahall/Vanara#365]
**Describe the bug and how to reproduce**

There is no published package for the windows library VssApi.dll. I can see there is a C# and a C++/CLI project for it.

Note this page https://github.com/dahall/Vanara/blob/master/PInvoke/VssApiMgd/readme.md, there is no published package. 

**What code is involved**

https://github.com/dahall/Vanara/tree/master/PInvoke/VssApiMgd

**Expected behavior**

Package to be published in nuget.

**Screenshots**

![image](https://user-images.githubusercontent.com/2021556/212468175-00577dcd-3b25-48b6-8d14-c643029be2e7.png)

----

I would be happy to work on it if there are known issues in the VSS projects, as I have a personal project I would like to use it on.

**Comment by dahall** [comment]
I haven't published because I can't figure out how to get MSBuild to automatically create the package that includes both the native (C++) and framework libraries. It will build and then you can use the to output assemblies (Vanara.PInvoke.VssApiMgd.dll and Vanara.PInvoke.VssApi) in your project manually. It works fine as the unit test shows.

**Comment by dahall** [comment]
Now available against .NET 6.0 in version 4.0.0

**Comment by KingKDot** [comment]
> Now available against .NET 6.0 in version 4.0.0

Do you plan on making a version that works with .net framework?

**Comment by dahall** [comment]
I think it could be done, but didn't do it because I'm lazy and didn't want to figure out how to get a C++ project to compile against multiple framework versions. If you can figure it out without going to a custom command-line build, that would be awesome.
