### ISSUE TITLE
ComStream might threw NotImplementException when IStream is not a file

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#373]
**Describe the bug and how to reproduce**

NotImplementException was threw in ComStream.Close() when IStream is not a file. Better to catch that exception and ignore it silently.

```csharp
   At System.Runtime.InteropServices.ComTypes.IStream.Commit(Int32 grfCommitFlags)
   AT Vanara.InteropServices.ComStream.Close()
```

**What code is involved**

```csharp
// In my case get IStream from clipboard format: "FileContents".
// I guess NotImplementException should also threw if IStream is not a file 
new ComStream(IStream).Dispose() //Although we should not dispose an object from clipboard 
```

**Expected behavior**
Do not threw any exception on dispose, catch all exceptions and ignore them.

**Comment by dahall** [comment]
Please test with latest build and confirm resolution.
