### ISSUE TITLE
Please support 'Message' enum for User32 API.

### ISSUE THREAD

**Issue by kelilife** [dahall/Vanara#376]
**Is your feature request related to a problem? Please describe.**
Using enumerations can be more convenient and type issues can be handled with forced conversions. Without these variables, it would be tedious to define them yourself each time.

**Describe the additions or enhancements you'd like**
Using enumerations can be more convenient and type issues can be handled with forced conversions. Without these variables, it would be tedious to define them yourself each time.

**Previous work**
[source.zip](https://github.com/dahall/Vanara/files/10780779/source.zip)

**Comment by kelilife** [comment]
The relevant enumeration is provided for reference, and hopefully can be accessed by enumeration for such fixed values. Of course you can provide an overloaded method.

For these specific message enumeration values you can find through Microsoft's development documentation, which I refer to when providing it and should be of some reference value.

**Comment by dahall** [comment]
All of these exist in various assemblies. Currently the Vanara assemblies support over 2000 enumerations across the Windows API.

* CursorPosition is a subset of Vanara.PInvoke.User32.HitTestValues
* HitTest can be found as Vanara.PInvoke.User32.HitTestValues
* HookType can be found as Vanara.PInvoke.User32.HookType
* MessageType can be found as Vanara.PInvoke.User32.WindowMessage
* WindowStyle can be found as Vanara.PInvoke.User32.WindowStyles
