### ISSUE TITLE
Please add window shadow enums, 'CS_HREDRAW', 'CS_VREDRAW', 'CS_DROPSHADOW' and more...

### ISSUE THREAD

**Issue by kelilife** [dahall/Vanara#377]
**Is your feature request related to a problem? Please describe.**
To make the call easier.

**Describe the additions or enhancements you'd like**
To make the call easier.

```C#
public static void SetShadowStyle(this IntPtr handle)
{
    if (handle == default)
        throw new InvalidDataException(nameof(handle));

    var gclStyle = GetClassLongFlag.GCL_STYLE;
    var newLong = new IntPtr((uint)GetClassLong(handle, gclStyle) | CS_DROP_SHADOW);

    SetClassLong(handle, gclStyle, newLong);
}
```

**Previous work**
If work on these imports have been done, please provide links.

**Comment by dahall** [comment]
The window class styles are available in Vanara.PInvoke.User32.WindowClassStyles. Using the search bar, you can search for the enum value (e.g. CS_DROP_SHADOW) and find the file it is in. The directory structure will then indicate which NuGet package (assembly) contains the definition.

**Comment by kelilife** [comment]
Sorry, I may not have searched carefully at the time, I did.

**Comment by dahall** [comment]
All the Vanara libraries use the spellings found in the header files of the Windows API. https://learn.microsoft.com/en-us/windows/win32/winmsg/window-class-styles
