### ISSUE TITLE
My app won't start after I upgraded Vanara to 3.4.13

### ISSUE THREAD

**Issue by XuanchenLin** [dahall/Vanara#381]
**Describe the bug and how to reproduce**

After I upgraded the Vanara library referenced by the app to 3.4.13, it no longer started. If I start the program with debug mode then it throws a System.ExecutionEngineException. Check the log in the event viewer, and locate the error message: A callback was made on a garbage collected delegate of type 'Vanara.PInvoke.User32!Vanara.PInvoke.User32+WindowProc::Invoke'.

**What code is involved**

This error occurs when I use WindowClass and CreateWindowEx to create a window.

```C#
    public ShadowElementWindow(ShadowElementPosition elemetPossition, WindowShadowDecorator windowShadowDecorator)
    {
        // ...

        var className = $"{SHADOW_WND_NAME}_{ShadowDecorator.TargetWindow.Handle}_{Position}";

        _wndProc = new WindowProc(WndProc);

        _gcHandle = GCHandle.Alloc(_wndProc);

        var windowClass = new WindowClass(className, HINSTANCE.NULL, _wndProc, hbrBkgd: HBRUSH.NULL);

        var exStyles = WindowStylesEx.WS_EX_LAYERED | WindowStylesEx.WS_EX_NOACTIVATE | WindowStylesEx.WS_EX_TRANSPARENT | WindowStylesEx.WS_EX_NOREDIRECTIONBITMAP;

        var styles = WindowStyles.WS_CLIPCHILDREN | WindowStyles.WS_POPUP | WindowStyles.WS_CLIPSIBLINGS;

        WND = CreateWindowEx(dwExStyle: exStyles, lpClassName: className, lpWindowName: "NanUI Shadow Window", dwStyle: styles, X: 0, Y: 0, nWidth: 0, nHeight: 0, hWndParent: HWND.NULL, hMenu: HMENU.NULL, hInstance: HINSTANCE.NULL, lpParam: IntPtr.Zero);
    }

```

**Expected behavior**

It worked fine in 3.4.12

**Screenshots**

**Comment by dahall** [comment]
I'm guessing it has something to do with the order of disposals. Could you try the following?
```cs
var className = $"{SHADOW_WND_NAME}_{ShadowDecorator.TargetWindow.Handle}_{Position}";
var windowClass = WindowClass.MakeVisibleWindowClass(className, WndProc);
var exStyles = WindowStylesEx.WS_EX_LAYERED | WindowStylesEx.WS_EX_NOACTIVATE | WindowStylesEx.WS_EX_TRANSPARENT | WindowStylesEx.WS_EX_NOREDIRECTIONBITMAP;
var styles = WindowStyles.WS_CLIPCHILDREN | WindowStyles.WS_POPUP | WindowStyles.WS_CLIPSIBLINGS;
WND = new VisibleWindow(windowClass, "NanUI Shadow Window", style: styles, exStyle: exStyles);
```
When you dispose `WND`, everything should get disposed and released in order, including the wndproc, window and the class.

**Comment by XuanchenLin** [comment]
It does not work. It happens when the application is starting, not when it is closed.  The same exception was thrown.

![image](https://user-images.githubusercontent.com/16586330/228412430-e5c565ad-c91f-4630-9491-75e9f716b3af.png)

I've rolled back Vanara to 3.4.12, which works fine.

Thanks.

**Comment by dahall** [comment]
I'm trying to replicate the error, but cannot with the code you both have provided. I'm running the following w/o error:
```cs
public void WindowClassCreateWinTest()
{
   var _wndProc = new WindowProc(WndProc);
   var _gcHandle = GCHandle.Alloc(_wndProc);
   var windowClass = new WindowClass(null, HINSTANCE.NULL, _wndProc, hbrBkgd: HBRUSH.NULL);
   var exStyles = WindowStylesEx.WS_EX_LAYERED | WindowStylesEx.WS_EX_NOACTIVATE |
      WindowStylesEx.WS_EX_TRANSPARENT | WindowStylesEx.WS_EX_NOREDIRECTIONBITMAP;
   var styles = WindowStyles.WS_CLIPCHILDREN | WindowStyles.WS_POPUP | WindowStyles.WS_CLIPSIBLINGS;
   Assert.That(CreateWindowEx(exStyles, windowClass.ClassName, "Test Window", styles), ResultIs.ValidHandle);
}

private static IntPtr WndProc(HWND hwnd, uint uMsg, IntPtr wParam, IntPtr lParam) =>
   DefWindowProc(hwnd, uMsg, wParam, lParam);
```

**Comment by sdcb** [comment]
I feel like this might not a error comes from Vanara, other component might causing Vanara PeekMessage fail, I'll try check other components.

**Comment by dahall** [comment]
@XuanchenLin Will you check and see if within your WndProc or elsewhere in your code you can calling back into the WndProc?

**Comment by XuanchenLin** [comment]
I found the problem. In my code the SetWindowPos function is called, after which I use GC.Collect(), probably this line of code is causing the handle to be destroyed.

**Comment by dahall** [comment]
Thank you for sharing your discovery!

**Comment by XuanchenLin** [comment]
> **Describe the bug and how to reproduce**
> 
> After I upgraded the Vanara library referenced by the app to 3.4.13, it no longer started. If I start the program with debug mode then it throws a System.ExecutionEngineException. Check the log in the event viewer, and locate the error message: A callback was made on a garbage collected delegate of type 'Vanara.PInvoke.User32!Vanara.PInvoke.User32+WindowProc::Invoke'.
> 
> **What code is involved**
> 
> This error occurs when I use WindowClass and CreateWindowEx to create a window.
> 
> ```cs
>     public ShadowElementWindow(ShadowElementPosition elemetPossition, WindowShadowDecorator windowShadowDecorator)
>     {
>         // ...
> 
>         var className = $"{SHADOW_WND_NAME}_{ShadowDecorator.TargetWindow.Handle}_{Position}";
> 
>         _wndProc = new WindowProc(WndProc);
> 
>         _gcHandle = GCHandle.Alloc(_wndProc);
> 
>         var windowClass = new WindowClass(className, HINSTANCE.NULL, _wndProc, hbrBkgd: HBRUSH.NULL);
> 
>         var exStyles = WindowStylesEx.WS_EX_LAYERED | WindowStylesEx.WS_EX_NOACTIVATE | WindowStylesEx.WS_EX_TRANSPARENT | WindowStylesEx.WS_EX_NOREDIRECTIONBITMAP;
> 
>         var styles = WindowStyles.WS_CLIPCHILDREN | WindowStyles.WS_POPUP | WindowStyles.WS_CLIPSIBLINGS;
> 
>         WND = CreateWindowEx(dwExStyle: exStyles, lpClassName: className, lpWindowName: "NanUI Shadow Window", dwStyle: styles, X: 0, Y: 0, nWidth: 0, nHeight: 0, hWndParent: HWND.NULL, hMenu: HMENU.NULL, hInstance: HINSTANCE.NULL, lpParam: IntPtr.Zero);
>     }
> ```
> 
> **Expected behavior**
> 
> It worked fine in 3.4.12
> 
> **Screenshots**


Finally, I located the problem.  In my code above:

```C#
var windowClass = new WindowClass(className, HINSTANCE.NULL, _wndProc, hbrBkgd: HBRUSH.NULL);
```

The windowClass is defined in the method, and it will be recycled by GC after this method is never called. So I just let windowClass as a class member, then the exception will not happen again.

Finally, I successfully upgraded to the latest version of Vanara.
