### ISSUE TITLE
NtQueryInformationProcess has incorrect signature

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#384]
**Describe the bug and how to reproduce**
In Vanara:
```csharp
[DllImport("ntdll.dll", ExactSpelling = true)]
[PInvokeData("winternl.h", MSDNShortId = "0eae7899-c40b-4a5f-9e9c-adae021885e7")]
public static extern NTStatus NtQueryInformationProcess([In] HPROCESS ProcessHandle, PROCESSINFOCLASS ProcessInformationClass, [Out] IntPtr ProcessInformation, uint ProcessInformationLength, out uint ReturnLength);

```

Should be:
```csharp
[DllImport("ntdll.dll", ExactSpelling = true, SetLastError = true)]
public static extern NTStatus NtQueryInformationProcess([In] IntPtr ProcessHandle, [In] NtDll.PROCESSINFOCLASS ProcessInformationClass, [Out] out IntPtr ProcessInformation, [In] uint ProcessInformationLength, [Optional] out uint ReturnLength);
```

**Comment by dahall** [comment]
What basis do you have for the change? I don't think you're correct. The documentation says:
`ProcessHandle`:
> A handle to the process for which information is to be retrieved.

`ProcessInformation`:
> A pointer to a buffer supplied by the calling application into which the function writes the requested information.

Also, the [unit test](https://github.com/dahall/Vanara/blob/38e611f1e304d8be05aa93f1e3a7899d2362741e/UnitTests/PInvoke/NtDll/WinternlTests.cs#L16) runs successfully.

**Comment by zhuxb711** [comment]
Ok, maybe you are right, but the second one also works for me~~~
