### ISSUE TITLE
 Shell32.DROPFILES.DangerousGetFileList() do not work as expected

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#391]
**Describe the bug and how to reproduce**

 Shell32.DROPFILES.DangerousGetFileList() return empty array which is not correct

**What code is involved**

This code not work for me:
```csharp
Shell32.DROPFILES DropStruct = // Get this from your clipboard or drag/drop, using CLIPFORMAT.CF_HDROP or FileDrop format
var Temp = DropStruct.DangerousGetFileList() // Temp is empty array
```

This code work for me:
```csharp
Shell32.DROPFILES DropStruct = // Get this from your clipboard or drag/drop, using CLIPFORMAT.CF_HDROP or FileDrop format

byte[] ArrayData = new byte[Size - DropStruct.pFiles];

Marshal.Copy(new IntPtr(DropPointer.ToInt64() + DropStruct.pFiles), ArrayData, 0, ArrayData.Length);

if (DropStruct.fWide)
{
    var Temp = Encoding.Unicode.GetString(ArrayData).Split('\0', StringSplitOptions.RemoveEmptyEntries); // Temp has at least one elements
}
else
{
    var Temp = Encoding.ASCII.GetString(ArrayData).Split('\0', StringSplitOptions.RemoveEmptyEntries); // Temp has at least one elements
}
```
**Expected behavior**
DangerousGetFileList() should return the same result as my code

**Comment by zhuxb711** [comment]
@dahall Hi! Could take a look on this issue?

**Comment by dahall** [comment]
Yep. Bad assumption in the function and bad coding to assume the documentation is followed without a good sample. I've made a change so that it is a static function receiving a memory pointer to the `DROPFILES` struct (`IntPtr ~= DROPFILES*`).
