### ISSUE TITLE
[Question] `User32.GetDC` return `SafeHDC`, is it really "safe"?

### ISSUE THREAD

**Issue by GF-Huang** [dahall/Vanara#392]
> ## Remarks
> An application must not delete a DC whose handle was obtained by calling the [GetDC](https://learn.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getdc) function. Instead, it must call the [ReleaseDC](https://learn.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-releasedc) function to free the DC.

https://learn.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-deletedc#remarks

Because `SafeHDC` inherited from `SafeHandle`, which has a finalizer `~SafeHandle()`, it will call `DeleteDC` in `SafeHDC.InternalReleaseHandle` finally. I'm not sure if this violates the documentation recommendations, nor if it creates some potential problems.

**Comment by dahall** [comment]
Almost all the docs are copied directly from learn.microsoft.com and I don't edit them. You are correct that `SafeHDC` automatically calls `DeleteDC` so there is no need to call it a second time.

**Comment by GF-Huang** [comment]
But the docs said: 
> An application **MUST NOT** delete a DC whose handle was obtained by calling the GetDC function.

So when I get a `dc` by:
```cs
using var dc = User32.GetDC(hwnd);
...
```
And I didn't read the documentation carefully, it will cause the `dc.dispose()` be called automatically (which call `DeleteDC` rather than `ReleaseDC`). I'm not sure if violating the docs leads to any pitfalls.

**Comment by dahall** [comment]
I'm making a few updates this weekend and will investigate further.
