### ISSUE TITLE
Shell32.IDesktopWallpaper.SetWallpaper should return HRESULT instead of void

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#397]
**Describe the bug and how to reproduce**

Incorrect:
```csharp
void SetWallpaper([MarshalAs(UnmanagedType.LPWStr)] string monitorID, [MarshalAs(UnmanagedType.LPWStr)] string wallpaper);
```

Correct:
```csharp
HRESULT SetWallpaper([MarshalAs(UnmanagedType.LPWStr)] string monitorID, [MarshalAs(UnmanagedType.LPWStr)] string wallpaper);
```

**Comment by dahall** [comment]
For almost all of the COM interfaces, I have removed the [PreserveSig] attribute and changed the return value to void _when_ the return value does not return any information beyond an error or when the final parameter can be used as a return value. If just an error, C# converts the HRESULT to the equivalent Exception.

**Comment by dahall** [comment]
If I set this one differently, then I really should go and do that for the hundreds of other interfaces with potentially thousands of methods to review and change.

**Comment by zhuxb711** [comment]
Ok, got it
