### ISSUE TITLE
SafeHFILE != null issue.

### ISSUE THREAD

**Issue by GreatFireWall** [dahall/Vanara#40]
Version: v2.2.1

**Describe the bug**
```cs
Kernel32.SafeHFILE device = null;
if (device != null)
    Console.WriteLine("Always here."); // this is not expected
```

**Expected behavior**
`default(Kernel32.SafeHFILE) == null // be true`

**Screenshots**

![image](https://user-images.githubusercontent.com/4510984/52895866-2e9b6900-31fb-11e9-8301-7ae0e9d409fb.png)

![image](https://user-images.githubusercontent.com/4510984/52895846-03187e80-31fb-11e9-8d45-c7b0f13fcf99.png)

**Root cause of problem**

![image](https://user-images.githubusercontent.com/4510984/52896198-542a7180-31ff-11e9-914d-ec0ee42525c4.png)

**Comment by dahall** [comment]
I've updated the code with a potential fix. What is the best way for you to test? The GitHub project can be pulled and built by you or I can supply you with updated NuGet packages you can install locally.

**Comment by GreatFireWall** [comment]
I will merge the last codes and test by myself later, thx your update. :)

**Comment by GreatFireWall** [comment]
It works well as the pictures. :)

![image](https://user-images.githubusercontent.com/4510984/53124243-d6b38800-3595-11e9-8196-f9759fe76f20.png)

![image](https://user-images.githubusercontent.com/4510984/53124283-ecc14880-3595-11e9-9779-660ba1ad2061.png)
