### ISSUE TITLE
PInvoke/WinSCard SCardListReaders returns no readers

### ISSUE THREAD

**Issue by franciscosamuel** [dahall/Vanara#402]
The SCardListReaders overload that takes an out string[] parameter does not return the actual reader names when there are connected readers.

```
SCardEstablishContext(SCARD_SCOPE.SCARD_SCOPE_USER, phContext: out var ctx);
SCardListReaders(ctx, null, out var readers);
```

The problem is that this overload makes an underlying call to SCardListReaders like so:

```
IntPtr ptr = default;
uint cch = SCARD_AUTOALLOCATE;
var ret = SCardListReaders(hContext, mszGroups, ptr, ref cch); 
```

According to the [documentation](https://learn.microsoft.com/en-us/windows/win32/api/winscard/nf-winscard-scardlistreadersw), in this case the native code converts ptr to a pointer to a byte pointer, so ptr is always IntPtr.Zero and the out array is always empty.

I tried to fix the issue myself but came across many loose ends so I thought it would be better to report the bug and start the discussion.

The native SCardListReaders method has 3 different semantics (sticking just to the happy paths) depending on the value pointed to by pcchReaders:

1. If it's 0, pcchReaders is set to the required number of bytes and mszReaders is unchanged
2. If it's SCARD_AUTOALLOCATE, pcchReaders is set to the required number of bytes, mszReaders is allocated and filled and the ownership is passed to the caller
3. Otherwise pcchReaders is set to the required number of bytes and mszReaders is filled

The current PInvoke.WinSCard.SCardListReaders implementation contains 2 overloads but both overloads will fail when using SCARD_AUTOALLOCATE semantics.

We should either remove the overload with the out parameter and leave the allocation of the IntPtr to the user or make both overloads aware of the SCARD_AUTOALLOCATE semantics and behave accordingly.

**Comment by dahall** [comment]
Thanks for finding this. It exposes a logic error in all the SCard overloads. I'm correcting them now and will release once tested.

**Comment by dahall** [comment]
I have posted a fix, but cannot test on my system as it has no smart cards. In a few minutes, you should be able to pull an updated NuGet package from AppVeyor (see home page for details). Please test and confirm the overloaded method is now working.

**Comment by franciscosamuel** [comment]
Looks good to me, ran the WinScard unit tests and can confirmed that all List* overloads are now correctly returning the respective arrays.

Before:
```
Standard Output: 
Registerd Readers(s)
======================

Registerd Card(s)
======================

Registerd Group(s)
======================


```
After: 

```
  Standard Output: 
Registerd Readers(s)
======================
OMNIKEY CardMan 5x25 0
OMNIKEY CardMan 5x25-CL 0
Registerd Card(s)
======================
Identity Device (Microsoft Generic Profile)
Identity Device (NIST SP 800-73 [PIV])
Registerd Group(s)
======================
SCard$DefaultReaders
Registerd Interface(s) for Identity Device (Microsoft Generic Profile)
======================
None
```

**Comment by dahall** [comment]
Thank you. This will go out in the next release.
