### ISSUE TITLE
Wrong STORAGE_PROPERTY_ID enumeration values

### ISSUE THREAD

**Issue by elf2k00** [dahall/Vanara#403]
The enum values for STORAGE_PROPERTY_ID defined in **winioctl.h** are incorrectly enumerated as described in [Microsoft documentation](https://learn.microsoft.com/en-us/windows/win32/api/winioctl/ne-winioctl-storage_property_id)

The enum values for some of the items are fixed and it re-defines the subsequent values:
`StorageDeviceIoCapabilityProperty = 48,`
`StorageDeviceSelfEncryptionProperty = 64,`

As in Vanara these fixed values are not set, the next values in the enumeration are wrongly set provoking and undefined behavior while querying the system with `DeviceIoControl`.

For example, the `STORAGE_PROPERTY_ID.StorageDeviceManagementStatus` should have the value 56, but in Vanara it has the value 21.

`Vanara.PInvoke.Kernel32.WinIOCtl.Enums.cs` should be modified with the STORAGE_PROPERTY_ID fixed values.

I'm also implementing the `STORAGE_DEVICE_MANAGEMENT_STATUS` structure from winioctl.h, it's missing in Vanara, please let me know if you want me to share the code.

**Comment by dahall** [comment]
Please share your structure and I'll add it when I apply the fixes to the enum.

**Comment by elf2k00** [comment]
Please find attached my implementation of `STORAGE_DEVICE_MANAGEMENT_STATUS`; 

For these are structures I couldn't find documentation in [winioctl.h documentation](https://learn.microsoft.com/en-us/windows/win32/api/winioctl/) in the web, they were directly ported from C++ winioctl.h 10.0.22000 build 0032

I can give you some simple code to test the struct using Vanara with a call to DeviceIOControl, they give you the Health Operational and Disk details of a disk.

[STORAGE_DEVICE_MANAGEMENT_STATUS.zip](https://github.com/dahall/Vanara/files/11610912/STORAGE_DEVICE_MANAGEMENT_STATUS.zip)

**Comment by dahall** [comment]
I've incorporated your structures with some minor changes and would appreciate your unit test to validate my changes.

**Comment by elf2k00** [comment]
[UnitTest_WinIOCtl.zip](https://github.com/dahall/Vanara/files/11633378/UnitTest_WinIOCtl.zip)
Please find attached the unit test, for all volumes in the system queries the device for some properties:

- BusType
- Health and Operational Status

I'm working right now in querying the drive for its form factor with STORAGE_PHYSICAL_TOPOLOGY_DESCRIPTOR and STORAGE_PHYSICAL_DEVICE_DATA, but finding some problems, let you know if I get it right.

**Comment by dahall** [comment]
Thanks for the unit test. It helped me uncover a big bug. I'm working through a solution now.

**Comment by dahall** [comment]
Whew. I had to create custom marshalers for a couple of structures, but it is all done now.

Just for your reference, there is an easier way to write the code you gave me:
```cs
using SafeHFILE hdisk = CreateFile(vol.TrimEnd('\\'), 0, FileShare.ReadWrite, null, FileMode.Open, 0);
Win32Error.ThrowLastErrorIfInvalid(hdisk);

STORAGE_PROPERTY_QUERY query = new(STORAGE_PROPERTY_ID.StorageDeviceProperty);
Win32Error.ThrowLastErrorIfFalse(DeviceIoControl(hdisk, IOControlCode.IOCTL_STORAGE_QUERY_PROPERTY, query, out STORAGE_DESCRIPTOR_HEADER sdh));
Win32Error.ThrowLastErrorIfFalse(DeviceIoControl(hdisk, IOControlCode.IOCTL_STORAGE_QUERY_PROPERTY, query, out STORAGE_DEVICE_DESCRIPTOR_MGD sdd, sdh.Size));

query.PropertyId = STORAGE_PROPERTY_ID.StorageDeviceManagementStatus;
Win32Error.ThrowLastErrorIfFalse(DeviceIoControl(hdisk, IOControlCode.IOCTL_STORAGE_QUERY_PROPERTY, query, out STORAGE_DEVICE_MANAGEMENT_STATUS outVar));
```
