### ISSUE TITLE
ShowContextMenu show Shell Context Menu but with no text and no icon

### ISSUE THREAD

**Issue by jcljb** [dahall/Vanara#406]
To simplify, I try this simple code (W11 pro) :

  public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();

            this.Shown += Form1_Shown;
        }

        ShellItem shellItem;

        private void Form1_Shown(object? sender, EventArgs e)
        {
            shellItem = new ShellItem(@"d:\xxx.txt");           
        }       

        private void button1_Click(object sender, EventArgs e)
        {
             shellItem.ContextMenu.ShowContextMenu(GetMousePosition());
        }
    }

On button1 click, the shell context menu is show  but with no text or icon...
![ContextMenu](https://github.com/dahall/Vanara/assets/112573133/99a12c2d-50d2-412c-922c-7265950f9020)

What's or or missing ?

**Comment by jcljb** [comment]
Perhaps pb with IContextMenu3 interface ?
I try to call methods directly and pass Handle to main window in order to take a look to  received messages (wndproc)
and it seems that some messages must be filtered too 
this is poor and not complete but now the contextmenu is fully shown :


  private void button1_Click(object sender, EventArgs e)
        {
            //  shellItem.ContextMenu.ShowContextMenu(GetMousePosition(),CMF.CMF_CANRENAME);

          
            hmenu = Vanara.PInvoke.User32.CreatePopupMenu();
            shellItem.ContextMenu.ComInterface.QueryContextMenu(hmenu, 0, 0x8000, int.MaxValue, CMF.CMF_EXTENDEDVERBS).ThrowIfFailed();
            var command = Vanara.PInvoke.User32.TrackPopupMenuEx(hmenu, TrackPopupMenuFlags.TPM_RETURNCMD, GetMousePosition().X, GetMousePosition().Y, Handle);
            if (command > 0)
                shellItem.ContextMenu.InvokeCommand((int)command - 0x800);
        }

        protected override void WndProc(ref Message msg)
        {
            switch (msg.Msg)
            {
                case 0x11f:
                case 0x117:
                case 0x2b:
                case 0x2c:
                case 288:

                    {
                        if (hmenu != null)
                        {
                            m_ComInterface3 = (IContextMenu3)Shell32.ShellUtil.QueryInterface(shellItem.ContextMenu.ComInterface, new Guid("{bcfce0a0-ec17-11d0-8d10-00a0c90f2719}"));

                            if (m_ComInterface3 is not null)
                            {
                                IntPtr lres;

                                m_ComInterface3.HandleMenuMsg2((uint)msg.Msg, msg.WParam, msg.LParam, out lres);
                            }
                        }
                        else
                            base.WndProc(ref msg);
                            break;
                    }
            }
            
                base.WndProc(ref msg);
            
        }

**Comment by dahall** [comment]
Have you found functional examples using `IContextMenu3`? I would follow those. Vanara simply exposes the interfaces. From light reading, it does appear that `HandleMenuMsg` and `HandleMenuMsg2` must be called in the user code.
