### ISSUE TITLE
ApplicationException always occur while calling DeviceIoControlAsync using same hDevice at 2nd time

### ISSUE THREAD

**Issue by GreatFireWall** [dahall/Vanara#41]
**Describe the bug**
As Title.

**What code is involved**
`Kernel32.DeviceIoControlAsync` -> `Kernel32.BeginDeviceIoControl` -> `OverlappedAsync.SetupOverlappedFunction`

**How to reproduce**
```cs
var device = Kernel32.CreateFile(@"\\.\DeviceDriverName", 
                                 Kernel32.FileAccess.GENERIC_READ | Kernel32.FileAccess.GENERIC_WRITE,
                                 System.IO.FileShare.None,
                                 null,
                                 System.IO.FileMode.Open,
                                 FileFlagsAndAttributes.FILE_FLAG_OVERLAPPED);

await Kernel32.DeviceIoControlAsync(device, someIoControlCode, ...);
await Kernel32.DeviceIoControlAsync(device, someIoControlCode, ...);  // exception thrown here
```

**Screenshots**

![image](https://user-images.githubusercontent.com/4510984/52999930-0f524500-3462-11e9-9a65-0712bf74658a.png)

![image](https://user-images.githubusercontent.com/4510984/53000825-314cc700-3464-11e9-9b9e-d17af592f7df.png)

**Comment by dahall** [comment]
`ThreadPool.BindToHandle` only allows a handle to be bound once per thread. It appears you're trying to reuse the handle held in `device` in your code. So my question is: Should the library work around the `ThreadPool` code or are you using `DeviceIoControl` in a way that is not consistent with its pattern by calling it twice? I'm not familiar enough with that function to answer the question.

**Comment by GreatFireWall** [comment]
Reuse `device` is common scenes, for example: open a virtual network adapter, and then keep reading and writing in a while loop for redirect or analysis network traffic. If open and close device frequently, it will reduce performance. 

Even the example is `Read` and `Write`, but this depends on the driver implementation, if it implement by DeviceIoControl ?

**Comment by dahall** [comment]
This one also is ready for testing

**Comment by GreatFireWall** [comment]
Capturing exceptions can cause some performance degradation. 
So, I don't think so `BindHandle` each call is a good way. 

---------------

**Please see my test result:**

This is the last code without my fix, you can see I call `DeviceIoControlAsync` 100 times, and print it cost time in Milliseconds:

![image](https://user-images.githubusercontent.com/4510984/53125224-6b1eea00-3598-11e9-8d4d-bc8765cd63b9.png)

the result: 

![image](https://user-images.githubusercontent.com/4510984/53126700-b4bd0400-359b-11e9-8719-c46c7aad600c.png)

---------------

If I do some fix, only `BindHandle` at first time, and the test code do not change as above:

![image](https://user-images.githubusercontent.com/4510984/53126293-bf2ace00-359a-11e9-9746-8ea58aa47f5c.png)
 
the result:

![image](https://user-images.githubusercontent.com/4510984/53126609-7b849400-359b-11e9-934b-b4c559b1536f.png)

**Comment by GreatFireWall** [comment]
I came up with three compromises.

1. Wrap `CreateFile` with `bool isAsync` argument, `BindHandle` in side `CreateFile` if  `isAsync == true`.

2. Exposing `bool bindHandle` argument for all the path of `DeviceIoControl`, but there's too much codes to modify, and it's not very elegant. 

3. Remove `BindHandle` that is inside `SetupOverlappedFunction` and add checking if the `device` had bind. Throw an exception tells user need to bind handle manually if not bind. (I don't know if this is feasible)

**Comment by dahall** [comment]
I had thought about 1 and 3. The problem is that the ThreadPool uses the handle to associate threads so it is not copying handles across thread boundaries. Removing it reduces the threading performance. I can collect handles and check them before calling BindHandle. With that, I only run the risk of holding the handle value until the process terminates. Maybe ThreadPool is already doing this so there is no harm.

**Comment by GreatFireWall** [comment]
Do you means save handles in a static `HashSet` or `Dictionary`, and check is it already exist before bind ?

**Comment by dahall** [comment]
Exactly

**Comment by GreatFireWall** [comment]
It seems feasible.

**Comment by dahall** [comment]
I just pushed updated code. Let me know if the bug is gone and performance is back.

**Comment by GreatFireWall** [comment]
Works well now.

![image](https://user-images.githubusercontent.com/4510984/53129584-eb4a4d00-35a2-11e9-8522-2230fc630f66.png)

**Comment by GreatFireWall** [comment]
By the way, are you planning to release version 2.3.0 of the nuget package these days ?

**Comment by dahall** [comment]
Yes. In the next 2 days.
