### ISSUE TITLE
ShellItemImages.GetImageAsync might throw NullReferenceException

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#414]
**Describe the bug and how to reproduce**

Recently, I got some stacktrace and found that `ShellItemImages.GetImageAsync` might throw NRE.

![image](https://github.com/dahall/Vanara/assets/42038175/dbcf806e-60aa-49a9-b3a2-340701dd3edb)

![image](https://github.com/dahall/Vanara/assets/42038175/153b8fe1-3e6c-4c4a-bd0c-b575f63a94cf)

Although the stacktrace do not show any useful information, but I think this issue might be related to the ShellItem.Parent. ShellItem.Parent might return null.

https://github.com/dahall/Vanara/blob/f66686c287b2a69e6fbbd5336ccbf3f4296b97a0/Windows.Shell.Common/ShellObjects/ShellItemImages.cs#L50-L64

https://github.com/dahall/Vanara/blob/f66686c287b2a69e6fbbd5336ccbf3f4296b97a0/Windows.Shell.Common/ShellObjects/ShellItem.cs#L502-L509

**What code is involved**
```csharp
using (ShellItem Item = new ShellItem("<Your path>"))
using (Gdi32.SafeHBITMAP HBitmap = Item.GetImage(new SIZE(150, 150), ShellItemGetImageOptions.BiggerSizeOk))
{

}
```

**Expected behavior**
Should not throw NullReferenceException

### By the way, it would be better to call the sync function directly rather than wait for Task.Result here, you simply warp the function in Task.Run()

https://github.com/dahall/Vanara/blob/f66686c287b2a69e6fbbd5336ccbf3f4296b97a0/Windows.Shell.Common/ShellObjects/ShellItem.cs#L699

https://github.com/dahall/Vanara/blob/f66686c287b2a69e6fbbd5336ccbf3f4296b97a0/Windows.Shell.Common/ShellObjects/ShellItemImages.cs#L30

**Comment by dahall** [comment]
I applied what I think is a fix for the NRE -- many more null checks. On your second point about wrapping the function in `Task.Run`, I don't see your request. Can you show how you'd do it for those two method calls?

**Comment by zhuxb711** [comment]
@dahall What I mean is that `GetImage` should not use Task internally. Let the caller to decide whether to warp it in the `Task.Run`
```csharp
public SafeHBITMAP GetImage(SIZE size, ShellItemGetImageOptions flags) => Images.GetImage(size, flags); 
```

**Comment by dahall** [comment]
Done
