### ISSUE TITLE
PreventShutdownContext does not work.

### ISSUE THREAD

**Issue by ElektroStudios** [dahall/Vanara#42]
**Describe the bug**
PreventShutdownContext does not prevent the user from shutting down the system and no dialog window is shown.

This does not seem a bug, but I think the author must improve its implementation to determine at runtime whether or not using **PreventShutdownContext** will really prevent the shutdown (and then throw an exception or something when the instance is initialized, this way the end-user can catch it to be aware that the system **CAN** be shutdown during a critical operation), but for improving that first we should figure why it is not preventing shutdown... and I don't have idea about why it does not.

**What code is involved**
WIndows.Forms/Contexts/PreventShutdownContext.cs

**Expected behavior**
You know...

**Screenshots**
Better than a screenshot: 
https://stackoverflow.com/questions/54842853/calling-shutdownblockreasoncreate-function-does-not-prevent-the-user-from-shut

**Comment by dahall** [comment]
Does [this implementation](https://github.com/dahall/Vanara/blob/master/WIndows.Forms/Contexts/PreventShutdownContext.cs) do more of what you'd expect?

**Comment by ElektroStudios** [comment]
> 
> 
> Does [this implementation](https://github.com/dahall/Vanara/blob/master/WIndows.Forms/Contexts/PreventShutdownContext.cs) do more of what you'd expect?

Thanks for the interest of support, and effort. I assume now the code is better than the previous version, however it does not prevent shutting down on my system even when **tryToPreventShutdown** is **true**. Any ideas about why?.

**Comment by ElektroStudios** [comment]
Hey, I started doing a trial-and-error snapshooting in a fresh Virtual Machine with Windows 10 and I discovered what the problem is: If the user has the AutoEndTasks registry value set (found in HKCU\Control Panel\Desktop registry key), then the shutdown does not show any UI to let the user cancel shutdown, so its useless to create a "cancel shutdown reason" in these circumstances because the app will be forced to close instantly in any case to continue the shutdown.

So, in order to make this thing to work as expected, the registry data of AutoEndTasks registry value must be 0 (zero); otherwise any app that attempts to prevent shutdown will be terminated and no UI will be shown at shutdown. 

With this info you should determine what to do now with PreventShutdownContext, I mean, if you will check for that registry key o not. This is now sholved for me.

Thanks again.

**Comment by dahall** [comment]
Thank you for doing that testing and discovery. I'll look at how Microsoft officially supports that value and will add that check to the PreventShutdownContext constructor.

**Comment by ElektroStudios** [comment]
>  I'll look at how Microsoft officially supports that value 

Maybe this is not what you mean for "how Microsoft officially supports that value", but I forgot to share this link with you that maybe could be useful: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc978604(v=technet.10)

PD: its all in my commentaries in the linked StackOverflow question.

**Comment by ElektroStudios** [comment]
Note: I discovered that the **AutoEndTasks** value can be added to "HKEY_USERS\.DEFAULT\Control Panel\Desktop", that overrides the value established in HKCU hive and HKU\{SID}.

This means, if **AutoEndTasks** is false (0) in HKCU but is true (1) in HKU\.DEFAULT, then the app will not prevent from shutting down and no shutdown UI will be shown.

if **AutoEndTasks** is false in HKU\.DEFAULT but is true in HKCU, then the app will prevent from shutting down and the shutdown UI will be shown.

Also a good point about this is that the *AutoEndTasks** value does not require to restart/log-off the system to take effect. So, once it is established to false in the proper key  (HKU\.DEFAULT), the app will prevent shut down, and we can revert this value to its previous state when we finish to use the PreventShutdownContext class.

That's all. I also ensured that the disabling of important Window Services will not affect this behavior.

**Comment by dahall** [comment]
So the class now checks those values and throws an exception if nothing can be displayed (**AutoEndTasks** == 1). I didn't want to change that value and then change it back as there is no way to lock it to prevent other processes from editing it while the context is live. I didn't want any artificial side-effects. Thanks for pointing this out. It really makes it much better.
