### ISSUE TITLE
RtlGetVersion not found in NtDll

### ISSUE THREAD

**Issue by emako** [dahall/Vanara#421]
```xml
<PackageReference Include="Vanara.PInvoke.NtDll" Version="3.4.16" />
```
RtlGetVersion not found in NtDll.

**Comment by dahall** [comment]
See https://github.com/dahall/Vanara/blob/da04510b0af70a14389922625e67cae0273eb319/PInvoke/Kernel32/SysInfoApi.cs#L2162

**Comment by emako** [comment]
It looks different from the API results of NtDll.
![R2X3O7$0QXUF1X57AT~QSHS](https://github.com/dahall/Vanara/assets/24737061/a2e0e426-b3f5-4309-8ff2-8287a2629c93)

**Comment by emako** [comment]
![image](https://github.com/dahall/Vanara/assets/24737061/14928fa0-35c5-41c5-8a3b-b0c5c3640548)
`NtDll.RtlGetVersion` is OK.

```c#
public static class NtDll
{
    [SecurityCritical]
    [DllImport(Lib.NTdll, SetLastError = true, CharSet = CharSet.Unicode)]
    [DefaultDllImportSearchPaths(DllImportSearchPath.System32)]
    public static extern int RtlGetVersion(out OSVERSIONINFOEX versionInfo);
}
```
Could you reopen the issuse?

**Comment by dahall** [comment]
Both those methods (GetVersionEx and RtlGetVersion) are marked as obsolete in lieu of the functions in VersionHelpers.h. You can find the Varana equivalents at [PInvoke/Kernel32/VersionHelpers.cs](https://github.com/dahall/Vanara/blob/9576f99ff8d4674154d1f20b3e923e066dd6f419/PInvoke/Kernel32/VersionHelpers.cs#L49)

**Comment by dahall** [comment]
To use `GetVersionEx` you have to set the size:
```cs
var ver = OSVERSIONINFOEX.Default;
if (!GetVersionEx(ref ver)) ...
```

**Comment by emako** [comment]
`Kernel32.OSVERSIONINFOEX.Default` make `Kernel32.GetVersionEx` return true, but it seems that the value is not eq to `NtDll.RtlGetVersion`.

**Kernel32.GetVersionEx**
![image](https://github.com/dahall/Vanara/assets/24737061/c460f44c-ff9e-4515-a860-df0a56b72a1a)

**NtDll.RtlGetVersion**
![image](https://github.com/dahall/Vanara/assets/24737061/4a26d94f-0330-40ad-ad45-b8bbe0202bc3)

**Addtional infos:**

My TargetFramework like following and I not use the `app.manifest` file.
```xml
<TargetFramework>net7.0-windows10.0.22621.0</TargetFramework>
```
