### ISSUE TITLE
#nullableenabled brunch is not being merged into master

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#426]
**Describe the bug and how to reproduce**
There are some fixes still remain in the #nullableenabled brunch.

**Comment by dahall** [comment]
Yep. I can't release a partial build with only some of the projects supporting nullability and it has been an enormous amount of work. If there are particular fixes you'd like me to force into master, please let me know. I've tried to keep them current with big fixes, but it is very possible that I've missed some.

**Comment by zhuxb711** [comment]
That brunch includes the fix for not to use Task.Run in ShellItem.GetImage internally which should be merge into master brunch first.

**Comment by dahall** [comment]
Done. Let me know if you find others.
