### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [dahall/Vanara#429]
Maybe You will be interested in hosting API Explorer online:
https://www.robiniadocs.com/d/vanara/api/Vanara.PInvoke.html

This is ready-to-go, so above link can be added to README.md for other people to see it.
Or using ready shields.io badge:

[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/vanara/api/Vanara.PInvoke.html)

```
[![Static Badge](https://img.shields.io/badge/API%20Documentation-RobiniaDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/vanara/api/Vanara.PInvoke.html)
```

https://github.com/NeuroXiq/RobiniaDocs

Besides above, I saw that Your projects has so many supported libraries that I didn't 
included them as an example documentation, I decided to take a few and generate documentation:
[Vanara.Kernel32 - RobiniaDocs](https://www.robiniadocs.com/d/vanara-pinvoke-kernel32/api/Vanara.PInvoke.html)
[Vanara.WebSocket- RobiniaDocs](https://www.robiniadocs.com/d/vanara-pinvoke-websocket/api/Vanara.PInvoke.html)
[Vanara.Gdi32- RobiniaDocs](https://www.robiniadocs.com/d/vanara-pinvoke-gdi32/api/Vanara.PInvoke.html)

Hope You will find RobiniaDocs useful for this and other projects

Regards
NeuroXiq

**Comment by dahall** [comment]
Cool project. Thanks for the info!
