### ISSUE TITLE
missing definition for StorageDeviceSeekPenalty.

### ISSUE THREAD

**Issue by DexterWoo** [dahall/Vanara#438]
according to the defininition in MSDN: https://learn.microsoft.com/en-us/windows/win32/api/winioctl/ne-winioctl-storage_property_id

**StorageDeviceSeekPenalty** is missing in the enum. the corresponding type is **DEVICE_SEEK_PENALTY_DESCRIPTOR**.

https://github.com/dahall/Vanara/blob/69f805f25c707ea3e216e92dbae293b7da82c352/PInvoke/Kernel32/WinIOCtl.Enums.cs#L2166

**[CorrespondingType(typeof(DEVICE_SEEK_PENALTY_DESCRIPTOR ))]
StorageDeviceSeekPenalty,** 

should be inserted there.

**Comment by dahall** [comment]
Fixed and committed. Will go out in next release.
