### ISSUE TITLE
User32.GetWindowLongAuto throws an exception if result is 0

### ISSUE THREAD

**Issue by vlad2048** [dahall/Vanara#442]
**Describe the bug and how to reproduce**

0 is a valid return value for GetWindowLong & GetWindowLongPtr.
So it cannot be used alone to detect an error.

For example querying the extended styles (WindowStylesEx) of a window can return 0 as a valid value.

**What code is involved**
```c#
// PInvoke\User32\WinUser.Gdi.cs
public static IntPtr GetWindowLongAuto(HWND hWnd, WindowLongFlags nIndex)
```

**Expected behavior**
Instead of just checking the return value against 0, we should:
- clear the last error ```Kernel32.SetLastError(0);```
- query the function
- if the result is 0 **and** ```Kernel32.GetLastError``` returns an error then throw the Win32Exception

**Screenshots**
n/a

**Comment by dahall** [comment]
I have updated the function as follows:
```cs
public static IntPtr GetWindowLongAuto(HWND hWnd, WindowLongFlags nIndex)
{
	SetLastErrorEx(0, 0);
	IntPtr ret = IntPtr.Size == 4 ? GetWindowLong(hWnd, nIndex) : GetWindowLongPtr(hWnd, nIndex);
	if (ret == IntPtr.Zero)
		Win32Error.GetLastError().ThrowIfFailed();
	return ret;
}
```
