### ISSUE TITLE
OverlappedAsyncBaseResult does not make processed bytes available.

### ISSUE THREAD

**Issue by mateli** [dahall/Vanara#443]
When using OverlappedAsyncBase for read and write operation, getting the number of written/read bytes is very useful.

I am thinking something like this:
asyncResult.Complete(true, (int)code); >> asyncResult.Complete(true, (int)code, bytes);
```
internal void Complete(bool synch = false, int error = 0, uint bytes = 0)
{
	CompletedSynchronously = synch;
	errorCode = error;
        processedBytes = bytes;
	if (IsCompleted) return;
		IsCompleted = true;
		lock (lockObj)
		{
			evt?.Set();
			AsyncCallback?.Invoke(this);
		}
	}
}
```

**Comment by dahall** [comment]
Added to 4.0.0 beta
