### ISSUE TITLE
How to use native Win32 Shell ImageList in WinUI3 - Implementing ExplorerBrowser for WinUI3

### ISSUE THREAD

**Issue by tajbender** [dahall/Vanara#444]
**Is your feature request related to a problem? Please describe**

I'm using WinAppSDK for some months now.
I wonder how to use a native System Win32 API ImageList in UWP / WinUI?
No changes to Vanara needed, i guess.

Any Idea, David? Thx.

**Describe the additions or enhancements you'd like**

// convert system wide shellItemList into xaml based type
`var winUIxamlObject = Vanara.*.SysImageList as || .SomeConversion()`

**Comment by dahall** [comment]
@tajbender I haven't done much with WinUI. There is a package called `Vanara.WinUI.Extensions` where we can land anything you want to add. Right now, that assembly is pretty light. I'll accept any PR you post.

**Comment by dahall** [comment]
Cool! Thanks. Happy Easter to you too!

**Comment by tajbender** [comment]
> @tajbender I haven't done much with WinUI.

btw, they have done an excellent job with WinUI3, in my humble opinion.

I've never worked with WPF and UWP before, but WinUI3 is straightforward as soon you get the point. They generate code-behind for the UI while compiling, this way, the UI-stuff is amazingly fast.

They also use DirectX / DirectDraw for rendering stuff. On the other side, you can use WinRT for the abstraction layer to OS for DOS, manipulating HWND settings / Messaging and so on: 🍔 

👍

**Comment by tajbender** [comment]
Done so far.

**Comment by tajbender** [comment]
addendum: These classes my help out:

https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/win32/microsoft.ui.interop/

**Comment by dahall** [comment]
@tajbender What type(s) do you want converted from and to? I don't have a `SysImageList` class. Do you mean a native image list handle (HIMAGELIST)? What is the output type under WinUI3?

**Comment by tajbender** [comment]
> @tajbender What type(s) do you want converted from and to? I don't have a `SysImageList` class. Do you mean a native image list handle (HIMAGELIST)? What is the output type under WinUI3?

@dahall Thanks for Reply, but you don't have to care about the Notes above.
I just wrote down what I've found so far, so they're just a reminder for myself 🧷 

You're right, with `SysImageList` I refer to the `Win32 - HIMAGELIST` handle, you could get with `SHGFI_SYSICONINDEX` flag, which returns the Index to the Shell Icon you're looking for.

Using Win32 you can pass this Handle to your `ListView` or `TreeView` controls directly, to avoid copying the images around from System space to your own Heap.

Anyway, *_you don't have to care_* about these comments, these are reminders for myself.

Sorry for confusion, Thank you very much anyways,

tajbender

**Comment by dahall** [comment]
I think you may be able to use `Vanara.Windows.Shell.ShellImageList` (in Vanara.Windows.Shell.Common) to expose the `SafeHICON` of system files or folders and wrap that into a class the derives from `IconSource` to provide the converted icon handle to a bitmap.

**Comment by tajbender** [comment]
@dahall: I uploaded an [YouTube-Video](https://youtu.be/FN3kUNfQ4r4)

That's the current state of the WinUI3 Shell - Components I'm working on, using Vanara.

- There's no optimization done yet, and no Unit-Tests done so far
- Shell Images are default embedded Icon Resources, so no `Vanara.Windows.Shell.ShellImageList` in use
- Enumeration is done using Vanara, respectively

<img width="1317" alt="Screenshot 2024-06-04 101413" src="https://github.com/dahall/Vanara/assets/10961499/e1ea1715-dd77-4ef7-9b10-75821e989aaf">


You may look at the [current branch here](https://github.com/tajbender/electrifier.v1.24).

I still may need your help on some occasions, but I'm satisfied for now 😀

Just for your Info, regards, tajbender

**Comment by dahall** [comment]
I just committed a class I'll use for this: [`Vanara.Windows.Shell.ShellIconExtractor`](https://github.com/dahall/Vanara/blob/ac0a1ac301dd4fdea9706688dedf96d596a4908a/Windows.Shell.Common/ShellIconExtractor.cs#L27)

**Comment by tajbender** [comment]
> I just committed a class I'll use for this: [`Vanara.Windows.Shell.ShellIconExtractor`](https://github.com/dahall/Vanara/blob/ac0a1ac301dd4fdea9706688dedf96d596a4908a/Windows.Shell.Common/ShellIconExtractor.cs#L27)

Thank you very much. This will help a lot. 🥇

**Comment by tajbender** [comment]
> I just committed a class I'll use for this: [`Vanara.Windows.Shell.ShellIconExtractor`](https://github.com/dahall/Vanara/blob/ac0a1ac301dd4fdea9706688dedf96d596a4908a/Windows.Shell.Common/ShellIconExtractor.cs#L27)

Hi, @dahall 

I used the `ShellIconExtractor` for some days now.

I'm new to that multithreading stuff, but anyway I get some strange behavior: Enumerating the same Folder again and again when navigating through the pages and views, `ShellIconExtractor` in my App may result in different findings:

```
08:40:10:034	'electrifier.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.19\System.Private.CoreLib.dll'. Symbol loading disabled by Include/Exclude setting.
08:40:10:389	'electrifier.exe' (CoreCLR: clrhost): Loaded 'Snippets'. 
08:40:10:892	'electrifier.exe' (CoreCLR: clrhost): Loaded 'D:\gitHub\tajbender\electrifier.v1.24\src\electrifier\bin\x64\Debug\net7.0-windows10.0.19041.0\AppX\runtimes\win\lib\net7.0\System.Diagnostics.EventLog.dll'. Symbol loading disabled by Include/Exclude setting.
08:40:10:892	'electrifier.exe' (CoreCLR: clrhost): Loaded 'D:\gitHub\tajbender\electrifier.v1.24\src\electrifier\bin\x64\Debug\net7.0-windows10.0.19041.0\AppX\Vanara.Windows.Shell.Common.dll'. Symbol loading disabled by Include/Exclude setting.
08:40:10:892	'electrifier.exe' (CoreCLR: clrhost): Loaded 'D:\gitHub\tajbender\electrifier.v1.24\src\electrifier\bin\x64\Debug\net7.0-windows10.0.19041.0\AppX\Vanara.PInvoke.Ole.dll'. Symbol loading disabled by Include/Exclude setting.
08:40:10:892	'electrifier.exe' (CoreCLR: clrhost): Loaded 'D:\gitHub\tajbender\electrifier.v1.24\src\electrifier\bin\x64\Debug\net7.0-windows10.0.19041.0\AppX\Vanara.PInvoke.Shell32.dll'. Symbol loading disabled by Include/Exclude setting.
08:40:10:892	'electrifier.exe' (CoreCLR: clrhost): Loaded 'D:\gitHub\tajbender\electrifier.v1.24\src\electrifier\bin\x64\Debug\net7.0-windows10.0.19041.0\AppX\Vanara.PInvoke.Shared.dll'. Symbol loading disabled by Include/Exclude setting.
08:40:11:883	Error: Converter failed to convert value of type 'Windows.Foundation.IReference`1<Microsoft.UI.Xaml.GridLength>' to type 'Double'; BindingExpression: Path='TemplateSettings.CompactPaneGridLength' DataItem='Microsoft.UI.Xaml.Controls.SplitView'; target element is 'Microsoft.UI.Xaml.Media.Animation.SplineDoubleKeyFrame' (Name='null'); target property is 'Value' (type 'Double'). 
08:40:14:383	'electrifier.exe' (CoreCLR: clrhost): Loaded 'D:\gitHub\tajbender\electrifier.v1.24\src\electrifier\bin\x64\Debug\net7.0-windows10.0.19041.0\AppX\Vanara.Core.dll'. Symbol loading disabled by Include/Exclude setting.
08:40:14:631	'electrifier.exe' (CoreCLR: clrhost): Loaded 'D:\gitHub\tajbender\electrifier.v1.24\src\electrifier\bin\x64\Debug\net7.0-windows10.0.19041.0\AppX\Vanara.PInvoke.Gdi32.dll'. Symbol loading disabled by Include/Exclude setting.
08:40:14:631	'electrifier.exe' (CoreCLR: clrhost): Loaded 'D:\gitHub\tajbender\electrifier.v1.24\src\electrifier\bin\x64\Debug\net7.0-windows10.0.19041.0\AppX\Vanara.Windows.Extensions.dll'. Symbol loading disabled by Include/Exclude setting.
08:40:14:631	'electrifier.exe' (CoreCLR: clrhost): Loaded 'D:\gitHub\tajbender\electrifier.v1.24\src\electrifier\bin\x64\Debug\net7.0-windows10.0.19041.0\AppX\Vanara.PInvoke.User32.dll'. Symbol loading disabled by Include/Exclude setting.
08:40:15:144	.IconExtOnComplete(): 63 items
08:40:15:144	.SetItemsSource(): `Desktop` 63 items.
08:40:16:630	.IconExtOnComplete(): 61 items
08:40:16:630	.SetItemsSource(): `Desktop` 61 items.
08:40:16:630	.GridViewVisibility = Visible
08:40:23:882	'electrifier.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.19\System.Reflection.Emit.Lightweight.dll'. Symbol loading disabled by Include/Exclude setting.
08:40:23:882	'electrifier.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.19\System.Reflection.Emit.ILGeneration.dll'. Symbol loading disabled by Include/Exclude setting.
08:40:23:882	'electrifier.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.19\System.Reflection.Primitives.dll'. Symbol loading disabled by Include/Exclude setting.
08:40:24:130	.IconExtOnComplete(): 64 items
08:40:24:130	.SetItemsSource(): `Desktop` 64 items.
08:40:27:631	.IconExtOnComplete(): 64 items
08:40:27:631	.SetItemsSource(): `Desktop` 64 items.
08:40:27:631	.GridViewVisibility = Visible
08:40:47:395	The thread '[Thread Destroyed]' (12448) has exited with code 0 (0x0).
08:40:47:645	The thread '[Thread Destroyed]' (27936) has exited with code 0 (0x0).
08:40:50:430	.IconExtOnComplete(): 63 items
08:40:50:430	.SetItemsSource(): `Desktop` 63 items.
08:40:52:736	.IconExtOnComplete(): 64 items
08:40:52:736	.SetItemsSource(): `Desktop` 64 items.
08:40:52:984	.GridViewVisibility = Visible
08:40:55:740	.IconExtOnComplete(): 64 items
08:40:55:740	.SetItemsSource(): `Desktop` 64 items.
08:40:57:780	.IconExtOnComplete(): 64 items
08:40:57:780	.SetItemsSource(): `Desktop` 64 items.
08:40:57:780	.GridViewVisibility = Visible
08:41:00:578	.IconExtOnComplete(): 64 items
08:41:00:578	.SetItemsSource(): `Desktop` 64 items.
08:41:03:657	.IconExtOnComplete(): 64 items
08:41:03:657	.SetItemsSource(): `Desktop` 64 items.
08:41:03:657	.GridViewVisibility = Visible
08:41:05:689	.IconExtOnComplete(): 62 items
08:41:05:689	.SetItemsSource(): `Desktop` 62 items.
08:41:25:456	The thread '[Thread Destroyed]' (8484) has exited with code 0 (0x0).
08:41:25:697	The thread '[Thread Destroyed]' (22372) has exited with code 0 (0x0).
```


Everytime `.IconExtOnComplete():` has finished, my desktop folder has been enumerated. As you may see, I may get different number of items while doing so (62, 63, 64). 😒 

In Fact, it should be 63 items... I'll investigate further 🤔 💭 

Have a nice, sunny day 🌞

**Comment by tajbender** [comment]
> Hi, @dahall
> 
> I used the `ShellIconExtractor` for some days now.
> 
> I'm new to that multithreading stuff, but anyway I get some strange behavior: Enumerating the same Folder again and again when navigating through the pages and views, `ShellIconExtractor` in my App may result in different findings:
> 
> Everytime `.IconExtOnComplete():` has finished, my desktop folder has been enumerated. As you may see, I may get different number of items while doing so (62, 63, 64). 😒
> 
> In Fact, it should be 63 items... I'll investigate further 🤔 💭
> 
> Have a nice, sunny day 🌞

@dahall: Never mind, after some changes/optimization, I can't reproduce this behavior.

It should have been caused by limited Multi-Threading Knowledge on my side 😀 

Regards, tajbender

**Comment by tajbender** [comment]
📥 For further Development, I've created my own branch for Additions:

https://github.com/electrifier/Vanara-Additions/tree/WinUI3-Shell32-Controls

**Comment by tajbender** [comment]
For converting a `HBitmap`, you can use:

```
    public ImageEx? ImageIconSource
    {
        get;
        internal set;
    }
```

Then use https://learn.microsoft.com/en-us/windows/communitytoolkit/controls/imageex

**Comment by tajbender** [comment]
> @tajbender I haven't done much with WinUI. There is a package called `Vanara.WinUI.Extensions` where we can land anything you want to add. Right now, that assembly is pretty light. I'll accept any PR you post.

Hello, @dahall 

I'd like to add some helpers and Controls in beta state now, just for convenience. However, some more work is necessary to polish them.

- Is it okay to fork and create an temporary pull request, or what way should I contribute my beta stuff ❓
- *And, will it be included in nightly AppVeyor builds* ❓

Regards, tajbender

**Comment by tajbender** [comment]
BTW: This snippet is working finally:

```
    /// <summary>
    /// Taken from <see href="https://stackoverflow.com/questions/76640972/convert-system-drawing-icon-to-microsoft-ui-xaml-imagesource"/>
    /// </summary>
    /// <param name="bitmapIcon"></param>
    /// <returns></returns>
    public static async Task<SoftwareBitmapSource> GetWinUi3BitmapSourceFromIcon(Icon bitmapIcon)
    {
        if (bitmapIcon == null)
            return null;

        // convert to bitmap
        using var bmp = bitmapIcon.ToBitmap();
        return await GetWinUi3BitmapSourceFromGdiBitmap(bmp);
    }

    /// <summary>
    /// Taken from <see href="https://stackoverflow.com/questions/76640972/convert-system-drawing-icon-to-microsoft-ui-xaml-imagesource"/>
    /// See also <see href="https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.image.source?view=windows-app-sdk-1.5#microsoft-ui-xaml-controls-image-source"/>
    /// </summary>
    /// <param name="gdiBitmap"></param>
    /// <returns></returns>
    public static async Task<SoftwareBitmapSource> GetWinUi3BitmapSourceFromGdiBitmap(Bitmap gdiBitmap)
    {
        if (gdiBitmap == null)
            return null;

        // get pixels as an array of bytes
        var data = gdiBitmap.LockBits(new System.Drawing.Rectangle(0, 0, 
                                      gdiBitmap.Width, gdiBitmap.Height), 
                   System.Drawing.Imaging.ImageLockMode.ReadOnly, 
                   gdiBitmap.PixelFormat);
        var bytes = new byte[data.Stride * data.Height];
        Marshal.Copy(data.Scan0, bytes, 0, bytes.Length);
        gdiBitmap.UnlockBits(data);

        // get WinRT SoftwareBitmap
        var softwareBitmap = new Windows.Graphics.Imaging.SoftwareBitmap(
            Windows.Graphics.Imaging.BitmapPixelFormat.Bgra8,
            gdiBitmap.Width,
            gdiBitmap.Height,
            Windows.Graphics.Imaging.BitmapAlphaMode.Premultiplied);
        softwareBitmap.CopyFromBuffer(bytes.AsBuffer());

        // build WinUI3 SoftwareBitmapSource
        var source = new SoftwareBitmapSource();
        await source.SetBitmapAsync(softwareBitmap);
        return source;
    }
```
