### ISSUE TITLE
Missing unions in FwpUClnt FWPM_* structures

### ISSUE THREAD

**Issue by jcspencer** [dahall/Vanara#445]
**Describe the bug and how to reproduce**

Hi!

First of all - thank you for building Vanara - this library is an absolute lifesaver!

I am currently working with the Windows Filtering Platform using RPC Filters. Specifically, adding filters using the `FwpUClnt` PInvoke library.

A number of structures in this subsystem have union field types, and some are missing in Vanara. This means the structures are larger than they are supposed to be, and causes issues inside WFP when it attempts to parse the structures that Vanara creates. 

**What code is involved**

In [FWPM_FILTER0](https://github.com/dahall/Vanara/blob/7de0f5301480fc4126c5bebe0a2dd25d2c2f0886/PInvoke/FwpUClnt/FwpMTypes.cs#L1550C3-L1550C9):
-   `UINT64 rawContext` and `GUID providerContextKey` should be overlapped in the struct memory.
- See [MSDN](https://learn.microsoft.com/en-us/windows/win32/api/fwpmtypes/ns-fwpmtypes-fwpm_filter0) for reference.

In [FWPM_ACTION0](https://github.com/dahall/Vanara/blob/7de0f5301480fc4126c5bebe0a2dd25d2c2f0886/PInvoke/FwpUClnt/FwpMTypes.cs#L777):
-  `Guid filterType` and `Guid calloutKey` should be overlapped in the struct memory.
- See [MSDN](https://learn.microsoft.com/en-us/windows/win32/api/fwpmtypes/ns-fwpmtypes-fwpm_action0) for reference.

I may have missed others, but these are the first two that are obvious to me.

**Expected behavior**

When creating an new `FWPM_FILTER0` and passing it to `FwpmFilterAdd0()`, the library is unable to parse the structure.

See this [Sample Code](https://gist.github.com/jcspencer/91229f40a79ba3181695ad0ad1e8921b) for an example that fails.

Initializing this class with `dynamic=true` should be enough to trigger the failure.

Thanks!

**Comment by dahall** [comment]
Sorry I missed those. They are now fixed in the nullable branch and will get released with the 4.0 packages.
