### ISSUE TITLE
PInvoke.IpHlpApi.GetExtendedUdpTable give wrong port 

### ISSUE THREAD

**Issue by BigPino67** [dahall/Vanara#446]
**Describe the bug and how to reproduce**

PInvoke.IpHlpApi.GetExtendedUdpTable give wrong port when compared to the windows command "netstat -ano"

**What code is involved**

```
private static List<TCPUDPConnection> GetIpV4UdpConnections(int pid)
{
    List<TCPUDPConnection> udpConnList = new List<TCPUDPConnection>();
    try
    {
        using (var results = GetExtendedUdpTable<MIB_UDPTABLE_OWNER_MODULE>(Vanara.PInvoke.IpHlpApi.UDP_TABLE_CLASS.UDP_TABLE_OWNER_MODULE, Ws2_32.ADDRESS_FAMILY.AF_INET))
        {
            foreach (var r in results)
            {
                if (pid < 0 || r.dwOwningPid == pid)
                {
                    IPAddress ipa = IPAddress.Parse(r.dwLocalAddr.ToString());
                    TCPUDPConnection row = new TCPUDPConnection(Utils.GetLocalHostName());
                    row.Protocol = Protocol.UDP;
                    row.Local = new System.Net.IPEndPoint(ipa, (int)r.dwLocalPort);
                    row.PID = pid;
                    udpConnList.Add(row);
                }
            }
        }
    }
    catch (Exception)
    {
        //Nothing to do here
    }
    
    return udpConnList;
}

private static List<TCPUDPConnection> GetIpV6UdpConnections(int pid)
{
    List<TCPUDPConnection> udpConnList = new List<TCPUDPConnection>();
    try
    {
        using (var results = GetExtendedUdpTable<MIB_UDP6TABLE_OWNER_PID>(Vanara.PInvoke.IpHlpApi.UDP_TABLE_CLASS.UDP_TABLE_OWNER_PID, Ws2_32.ADDRESS_FAMILY.AF_INET6))
        {
            foreach (var r in results)
            {
                if (pid < 0 || r.dwOwningPid == pid)
                {
                    IPAddress ipa = IPAddress.Parse(r.ucLocalAddr.ToString());
                    TCPUDPConnection row = new TCPUDPConnection(Utils.GetLocalHostName());
                    row.Protocol = Protocol.UDP;
                    row.Local = new System.Net.IPEndPoint(ipa, (int)r.dwLocalPort);
                    row.PID = pid;
                    udpConnList.Add(row);
                }
            }
        }
    }
    catch (Exception)
    {
        //Nothing to do here
    }
    
    return udpConnList;
}
```

**Expected behavior**

I expect that "netstat -ano" give the same results as PInvoke.IpHlpApi.GetExtendedUdpTable. It's not the case here :
Netstat port : 56359
PInvoke.IpHlpApi.GetExtendedUdpTable : 10204

**Screenshots**

"Netstat -ano" results :
![image](https://github.com/dahall/Vanara/assets/15323780/910a25cf-3108-4a29-a787-d5ad2c2556bc)

PInvoke.IpHlpApi.GetExtendedUdpTable results :
![image](https://github.com/dahall/Vanara/assets/15323780/0dd898f0-5344-41b6-af55-412eda5c79a5)

**Comment by dahall** [comment]
I expect there is structure sizing problem. Are you running your code as 32 or 64-bit?

**Comment by dahall** [comment]
Haha. I deleted my last comment. You and I both failed to read the docs for `dwLocaPort`:
> The port number of the UDP endpoint on the local computer. This member is stored in network byte order.

In the next 4.0 release, I've added a new property called dwHostLocalPort that puts dwLocalPort in host order.

**Comment by BigPino67** [comment]
Following the newest release (v.4.0.1), MIB_UDP6TABLE_OWNER_PID and MIB_UDPTABLE_OWNER_MODULE does not have any properties calleddwHostLocalPort. Is it normal?

**Comment by dahall** [comment]
> @dahall Following the newest release (v.4.0.1), MIB_UDP6TABLE_OWNER_PID and MIB_UDPTABLE_OWNER_MODULE does not have any properties calleddwHostLocalPort. Is it normal?

I don't see that field (`dwHostLocalPort`) in either `MIB_UDPROW_OWNER_MODULE` or `MIB_UDP6ROW_OWNER_PID`. Both have `dwLocalPort`.

**Comment by dahall** [comment]
Thanks for the callout to make all the structures consistent. This is done for 4.0.2
