### ISSUE TITLE
WTSApi32: Wrong variable used to create dateTime

### ISSUE THREAD

**Issue by AgentDove** [dahall/Vanara#448]
**Describe the bug and how to reproduce**

`public DateTime LastInputTime => DateTime.FromFileTimeUtc(LogonTimeUTC);`
Should be
`public DateTime LastInputTime => DateTime.FromFileTimeUtc(LastInputTimeUTC);`

**What code is involved**

https://github.com/dahall/Vanara/blob/7de0f5301480fc4126c5bebe0a2dd25d2c2f0886/PInvoke/WTSApi32/WTSApi32.cs#L3020

**Expected behavior**

LastInputTime should be derived form LastInputTimeUTC and not LogonTimeUTC

**Comment by dahall** [comment]
Fixed in nullable branch. Will release in 4.0 package push shortly.
