### ISSUE TITLE
ReadConsoleInput and associated structures not marshalling data correctly

### ISSUE THREAD

**Issue by oising** [dahall/Vanara#45]
**Describe the bug**
ReadConsoleInput, when reading KEY_EVENT, the bKeyDown flag is always TRUE for both keyup and keydown. I've noticed in other scenarios the event type flag is always 0 - I think perhaps your automated conversion (I assume you're using something automated here) is messing up.

**What code is involved**
Kernel32.ReadConsoleInput and INPUT_RECORD

**Expected behavior**
bKeyDown should reflect keydown events correctly.

**Screenshots**
I replaced your library with the definitions here and everything works fine. 
http://www.pinvoke.net/default.aspx/kernel32/ConsoleFunctions.html 

Thanks for an otherwise outstanding and clean library.

**Comment by dahall** [comment]
Thanks for finding this. I think the problem lies in aligning the structure to 4 byte boundaries. I have updated the code and will test shortly to confirm I've fixed the problem and then will report back. While I understand the PInvoke definition, it is not aligned well to the API code in that they removed the union. However, it did alert me to the boundary as they made it explicit.

**Comment by dahall** [comment]
Would you plug this structure into your project and confirm it works?
```
		[StructLayout(LayoutKind.Explicit)]
		public struct INPUT_RECORD
		{
			/// <summary>
			/// <para>A handle to the type of input event and the event record stored in the <c>Event</c> member.</para>
			/// <para>This member can be one of the following values.</para>
			/// <para>
			/// <list type="table">
			/// <listheader>
			/// <term>Value</term>
			/// <term>Meaning</term>
			/// </listheader>
			/// <item>
			/// <term>FOCUS_EVENT 0x0010</term>
			/// <term>The Event member contains a FOCUS_EVENT_RECORD structure. These events are used internally and should be ignored.</term>
			/// </item>
			/// <item>
			/// <term>KEY_EVENT 0x0001</term>
			/// <term>The Event member contains a KEY_EVENT_RECORD structure with information about a keyboard event.</term>
			/// </item>
			/// <item>
			/// <term>MENU_EVENT 0x0008</term>
			/// <term>The Event member contains a MENU_EVENT_RECORD structure. These events are used internally and should be ignored.</term>
			/// </item>
			/// <item>
			/// <term>MOUSE_EVENT 0x0002</term>
			/// <term>The Event member contains a MOUSE_EVENT_RECORD structure with information about a mouse movement or button press event.</term>
			/// </item>
			/// <item>
			/// <term>WINDOW_BUFFER_SIZE_EVENT 0x0004</term>
			/// <term>
			/// The Event member contains a WINDOW_BUFFER_SIZE_RECORD structure with information about the new size of the console screen buffer.
			/// </term>
			/// </item>
			/// <item/>
			/// <item/>
			/// <item/>
			/// </list>
			/// </para>
			/// </summary>
			[FieldOffset(0)]
			public EVENT_TYPE EventType;

			/// <summary>
			/// The event information. The format of this member depends on the event type specified by the <c>EventType</c> member.
			/// </summary>
			[FieldOffset(4)]
			public INPUT_RECORD_EVENT Event;

			/// <summary>The event union.</summary>
			[StructLayout(LayoutKind.Explicit)]
			public struct INPUT_RECORD_EVENT
			{
				/// <summary>The key event</summary>
				[FieldOffset(0)]
				public KEY_EVENT_RECORD KeyEvent;

				/// <summary>The mouse event</summary>
				[FieldOffset(0)]
				public MOUSE_EVENT_RECORD MouseEvent;

				/// <summary>The window buffer size event</summary>
				[FieldOffset(0)]
				public WINDOW_BUFFER_SIZE_RECORD WindowBufferSizeEvent;

				/// <summary>The menu event</summary>
				[FieldOffset(0)]
				public MENU_EVENT_RECORD MenuEvent;

				/// <summary>The focus event</summary>
				[FieldOffset(0)]
				public FOCUS_EVENT_RECORD FocusEvent;
			}
		}
```

**Comment by oising** [comment]
Nope, EventType is always 0.

**Comment by dahall** [comment]
Thank you. After trying a few methods from the link you shared and trying more of mine, I've determined that there is nothing very clean about either. I'm building a function by function test console app so I can work out all the bugs. I'll have a fully working wincon.h equivalent in the next day or so.

**Comment by dahall** [comment]
After a lot of toil, I believe what is pushed is the only complete, fully functional and fully tested WinCon p/invoke solution on the web. I found so many examples across the web that had some parts working, and others just wrong. I'll push in the next day or so as version v2.3.6. Thanks for alerting me to this section's incompleteness. I hope it helps your work.
