### ISSUE TITLE
Wrong values in Kernel32.READ_DIRECTORY_NOTIFY_INFORMATION_CLASS enum

### ISSUE THREAD

**Issue by antoinebj** [dahall/Vanara#450]
**Describe the bug and how to reproduce**

The values of the enum are incorrectly 0 and 1.

**What code is involved**

Declaration of [Kernel32.READ_DIRECTORY_NOTIFY_INFORMATION_CLASS enum](https://github.com/dahall/Vanara/blob/7de0f5301480fc4126c5bebe0a2dd25d2c2f0886/PInvoke/Kernel32/WinBase.File.cs#L641)

**Expected behavior**

The values should be 1 and 2 according to Microsoft documentation:
https://learn.microsoft.com/en-us/windows/win32/api/minwinbase/ne-minwinbase-read_directory_notify_information_class
Also verified in minwinbase.h itself

**Comment by dahall** [comment]
Fixed in 4.0 branch. Release out soon.
