### ISSUE TITLE
SearchApi.IQuerySolution.Resolve() should not require unsafe pointer for parameter "SYSTEMTIME* pstReferenceTime"

### ISSUE THREAD

**Issue by zhuxb711** [dahall/Vanara#451]
**Describe the bug and how to reproduce**
Vanara should not allow passing the unsafe pointer as the parameter to the "SearchApi.IQuerySolution.Resolve()", which will force every program to enable unsafe switch. Also unsafe code will break the IAsynEnumerable pattern.

![image](https://github.com/dahall/Vanara/assets/42038175/a88ffd35-54cb-45a1-852b-dd2c6b8728a6)
![image](https://github.com/dahall/Vanara/assets/42038175/b0ff0766-2ff0-49bf-96ee-adcbd1780fd1)

**Expected behavior**
Should be the same as 3.4.17

**Comment by dahall** [comment]
The parameter notes for `pstReferenceTime` indicate
> A pointer to a `SYSTEMTIME` value to use as the reference date and time. A null pointer can be passed if `sqro` is set to SQRO_DONT_RESOLVE_DATETIME.
The 3.4.17 version couldn't allow for that so that prompted the change.

Can you help me understand more about your comment "Also unsafe code will break the IAsynEnumerable pattern."? Do you mean that you have to then have `unsafe` blocks? If that is the case, I can overloads that support both options in Vanara so you can just use safe code.

**Comment by zhuxb711** [comment]
Yes, better provide a overload for that because it's not possible to create a *variable (unsafe pointer) without enabling unsafe switch for C#. For the code in 4.0.0, it's no possible to use fully safe pointer if you defined something *parameter instead of IntPtr

**Comment by zhuxb711** [comment]
> The parameter notes for `pstReferenceTime` indicate
> 
> > A pointer to a `SYSTEMTIME` value to use as the reference date and time. A null pointer can be passed if `sqro` is set to SQRO_DONT_RESOLVE_DATETIME.
> 
> The 3.4.17 version couldn't allow for that so that prompted the change.
> 
> 
> 
> Can you help me understand more about your comment "Also unsafe code will break the IAsynEnumerable pattern."? Do you mean that you have to then have `unsafe` blocks? If that is the case, I can overloads that support both options in Vanara so you can just use safe code.

If you try to use unsafe code in a function that returns IAsyncEnumerable. You will get an error from the compiler: "Unsafe code may not appear in iterators"

**Comment by zhuxb711** [comment]
FYR: C# Compiler Error [CS1629](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs1629)

**Comment by dahall** [comment]
Thank you. I'll dig into this and find a resolution.

**Comment by dahall** [comment]
Fixed in 4.0.1

**Comment by zhuxb711** [comment]
Thanks, and hope will release 4.0.1 soon~
