### ISSUE TITLE
SafeHANDLE != operator should make parameters nullable

### ISSUE THREAD

**Issue by GF-Huang** [dahall/Vanara#459]
**Describe the bug and how to reproduce**
It's not a bug. 

![image](https://github.com/dahall/Vanara/assets/4510984/41dd6feb-9a68-4288-bf9d-13a8d71e1c92)

**Expected behavior**
No warning(CS8604).

**Comment by dahall** [comment]
Fixed in 4.0.1

**Comment by GF-Huang** [comment]
The `h1` seems also need to nullable. 😄 

![image](https://github.com/dahall/Vanara/assets/4510984/7512dab7-b9e1-4ae6-be0f-81f01f78d580)

**Comment by dahall** [comment]
Corrected this and the == operator so null SafeHANDLEs are covered in 4.0.2
