### ISSUE TITLE
DOSvc unit test fails with 0x80010123

### ISSUE THREAD

**Issue by pl4nty** [dahall/Vanara#465]
**Describe the bug and how to reproduce**

I've cloned the repo and targeted net6.0 on Windows 22631.3527, then modified `DoSvcTests.cs` to import `System.Threading.Tasks` and return a `Task` as required by NUnit.

`dotnet test UnitTests\PInvoke\DOSvc` fails with the following stack trace, running with admin or SYSTEM permissions. Apologies for the screenshot, it's on a VM without copy/paste:

![image](https://github.com/dahall/Vanara/assets/21111317/60d14e9d-8e33-4cec-a9c7-e3438437038d)

**What code is involved**

`UnitTests\PInvoke\DOSvc`

**Expected behavior**

Test passes successfully. I can't find a successful CI run though, so this might be a regression.

**Comment by pl4nty** [comment]
seems like `CoSetProxyBlanket` [doesn't handle auth properly](https://github.com/dotnet/runtime/issues/101909#issuecomment-2098554896), so we need to initialize manually before `IDOManager`.
```c#
CoInitializeSecurity(
	PSECURITY_DESCRIPTOR.NULL,
	-1,
	[],
	(IntPtr)null,
	Rpc.RPC_C_AUTHN_LEVEL.RPC_C_AUTHN_LEVEL_DEFAULT,
	Rpc.RPC_C_IMP_LEVEL.RPC_C_IMP_LEVEL_IMPERSONATE,
	dwCapabilities: EOLE_AUTHENTICATION_CAPABILITIES.EOAC_STATIC_CLOAKING
);
```

This initiates a download, but `OnStatusChange` is only called once at creation and the temp file is empty. `Get-DeliveryOptimizationStatus` shows the download has completed though.

**Comment by dahall** [comment]
Fixed test definition and support class
