### ISSUE TITLE
Add a function to enumerate all open Windows Explorer Instances, including the path that is selected

### ISSUE THREAD

**Issue by tajbender** [dahall/Vanara#469]
**_Is your feature request related to a problem? Please describe._**

No.

**_Describe the additions or enhancements you'd like_**

Some years ago, I found a Function to enumerate every Windows Explorer. A want to add this existing function to Vanara Shell32 Package

**Previous work**
_If work on these imports have been done, please provide links._

Somewhere in the depth of https://github.com/electrifier/Classic-electrifier. 🍪 

Regards,
tajbender

**Comment by dahall** [comment]
Couldn't you do this with a combination of `GetDesktopWindow` and `EnumChildWindows` looking for the registered window class of Explorer?

**Comment by tajbender** [comment]
> Couldn't you do this with a combination of `GetDesktopWindow` and `EnumChildWindows` looking for the registered window class of Explorer?

Yes, that is exactly what the snippet does. Found it 10+ years in an MSDN-Article.

I still have the code, just gimme some time 😁

**Comment by tajbender** [comment]
For someone's Refernence:

https://devblogs.microsoft.com/oldnewthing/?p=4933

**Comment by dahall** [comment]
I got `IShellWindows.FindWindowSW` working. See implementation in [unit tests](https://github.com/dahall/Vanara/blob/master/UnitTests/PInvoke/Shell32/ExDispTests.cs).

**Comment by tajbender** [comment]
Wow, this is rocket science 🚀 🎸 

Thanks.
