### ISSUE TITLE
The Portable Device API uses HRESULT return values for their methods

### ISSUE THREAD

**Issue by NilsHoyer** [dahall/Vanara#473]
The [Portable Device API](https://learn.microsoft.com/de-de/windows/win32/api/portabledeviceapi/) has several COM interfaces and as far I see, all their methods are giving back a HRESULT. But your implementations are not (void instead of HRESULT).

**Comment by dahall** [comment]
In general, I have chosen to let .NET handle HRESULT errors from COM interface methods as exceptions except in cases where the interface must be implemented in .NET or when the HRESULT can return results like S_FALSE that are more result codes than errors.

**Comment by NilsHoyer** [comment]
When I read your comment, I thought this would be bad implemented. Today, I love it! 😌

**Comment by dahall** [comment]
Thank you for the positive feedback!
