### ISSUE TITLE
FwpUClnt.FWPM_FILTER0.filterId is broken

### ISSUE THREAD

**Issue by Signum21** [dahall/Vanara#475]
**Describe the bug and how to reproduce**

I'm enumerating the wfp filters.
The name, description and filterKey are correctly extracted but the filterId is 0 for all filters.

**What code is involved**

```csharp
FwpUClnt.FwpmFilterEnum0(engineHandle, filterEnumHandle, 2500, out FwpUClnt.SafeFwpmMem filters, out uint filterslength);
FwpUClnt.FWPM_FILTER0[] filtersArray = filters.ToArray<FwpUClnt.FWPM_FILTER0>(filterslength, true);

foreach (FwpUClnt.FWPM_FILTER0 filter in filtersArray)
{
    Console.WriteLine(filter.displayData.name);
    Console.WriteLine(filter.displayData.description);
    Console.WriteLine(filter.filterId);
    Console.WriteLine(filter.filterKey + Environment.NewLine);
}
```

**Expected behavior**

The filterId should be different and not 0 (I confirmed this with another tool).

**Comment by dahall** [comment]
Thanks. I had a size bug in FWP_VALUE0 causing the problem. It is fixed and can be found in 4.0.3 (soon to be released) or on the AppVeyor repository as pre-release (see readme).

I would strongly encourage the use of the overload for FwpmFilterEnum0 that tucks the array inside a memory manager.
```cs
FwpmFilterEnum0(engineHandle, out SafeFwpmArray<FWPM_FILTER0> h);
foreach (FWPM_FILTER0 e in h)
   ...
```
