### ISSUE TITLE
Kernel32.DeviceIoControlAsync stuck at EndOverlappedFunction -> handle.WaitOne();

### ISSUE THREAD

**Issue by GF-Huang** [dahall/Vanara#48]
**Describe the bug**

All `Kernel32.DeviceIoControlAsync( ... )` always stuck at 

```cs
public static object EndOverlappedFunction(IAsyncResult asyncResult)
{
    ...
    handle.WaitOne(); // stuck here
    ...
}
```

**How to reproduce**

See the following image.

The `Kernel32.DeviceIoControlAsync<EmptyStruct>(device, 0x282004)` I can change to any other `ioControlCode` that already implementation in my driver, always stuck too.  

The `DeviceIoControl` (without async) works well. So I infer that it's not my driver's problem.

![image](https://user-images.githubusercontent.com/4510984/56859622-311afb80-69c0-11e9-91a0-a794cda4f367.png)

Now debug this unit test method:

![gif](https://i.vgy.me/6LcxQ8.gif)

OK, let's try add a delay between `CloseDevice` and `OpenDevice` like this:

![image](https://user-images.githubusercontent.com/4510984/56859765-ffa32f80-69c1-11e9-85c0-c20577774998.png)

Debug again:

![gif](https://i.vgy.me/v1m0mY.gif)

**No stuck now.** 🤔

**Comment by GreatFireWall** [comment]
I think use [AsyncLock](https://github.com/StephenCleary/AsyncEx) instead of `lock` will be better in `async methods` ?

**Comment by dahall** [comment]
Will you post the code for the full unit test you are using to create the condition? I'd like to use it to confirm any fixes I do are working.

**Comment by dahall** [comment]
If you then can fix the code and submit a PR, I will accept it.

**Comment by dahall** [comment]
I have an upcoming code release with many changes to the Kernel32 library. Have you been able to fix this problem?

**Comment by GreatFireWall** [comment]
I'm sorry, I unable to fix this.. 😢

**Comment by GreatFireWall** [comment]
I found that it was caused by `IOCompletionCallback` of `o.Pack` not being called in the second `DeviceIoControlAsync`.

Do you know under what circumstances the `IOCompletionCallback` may not be called?

I see my driver output log is correct, and as I said before, the `DeviceIoControl` (without async) works well.

**Comment by NN---** [comment]
Did you manage it?

Can this be related?
https://stackoverflow.com/a/59948146/558098

**Comment by dahall** [comment]
@GF-Huang I'm going through open issues and looking for updates. Were you able to resolve the root cause to this problem? If so, are you able to share your findings or solutions?

**Comment by GF-Huang** [comment]
> Did you manage it?
> 
> Can this be related?
> https://stackoverflow.com/a/59948146/558098

@dahall I think that is right. Now, I just use `Task.Run(() => Kernel32.DeviceIoControlAsync(...))` for walkaround this issue. 
So, this issue maybe not an issue in fact.
