### ISSUE TITLE
Additional hint for the summary of IPortableDeviceContent::CreateObjectWithPropertiesAndData

### ISSUE THREAD

**Issue by NilsHoyer** [dahall/Vanara#483]
In your description of IPortableDeviceContent::CreateObjectWithPropertiesAndData I would like to have a hint, that the stream must be released and how I should do that.

https://learn.microsoft.com/en-us/windows/win32/api/portabledeviceapi/nf-portabledeviceapi-iportabledevicecontent-createobjectwithpropertiesanddata

Same for IPortableDeviceResources::GetStream:
https://learn.microsoft.com/en-us/windows/win32/api/portabledeviceapi/nf-portabledeviceapi-iportabledeviceresources-getstream

PS I use a Marshal method for releasing and that works fine for me. But I mention this after I spend 30 to find this out (call me "stupid" if you want 🤫).

**Comment by dahall** [comment]
For both methods, the XML comments exactly match those in the links you provided. Was there more you think is needed?

**Comment by dahall** [comment]
Right. The .NET framework, when [marshaling strings](https://learn.microsoft.com/en-us/dotnet/framework/interop/default-marshalling-behavior#unmanaged-signature), will internally call `CoTaskMemFree` on them before returning the `string`.

The `IStream` parameter does have the correct text for what needs to be done.
>The caller must release this interface when it is done with it.

**Comment by NilsHoyer** [comment]
I'm using Marshal.ReleaseComObject(stream):
https://learn.microsoft.com/de-de/dotnet/api/system.runtime.interopservices.marshal.releasecomobject?view=net-8.0

If I don't call it, I can't use both mentioned methods again. While trying it, I get a message, that a resource is busy. (Sorry, at this moment I can't provide the correct error code or message.)

**Comment by dahall** [comment]
Good. You're doing exactly what the documentation requires, but in .NET fashion.

**Comment by NilsHoyer** [comment]
... and I believe, this hint inside your description would be helpful for other people. Because of this, I opened this issue.

**Comment by dahall** [comment]
Added that note to those methods.

**Comment by NilsHoyer** [comment]
Your changes are exactly, what I hope other developer helps. Thank you!
