### ISSUE TITLE
NetworkListManager does not work to receive events in .Net MAUI project

### ISSUE THREAD

**Issue by NilsHoyer** [dahall/Vanara#484]
I'm trying to catch the events of the NetworkListManager, and it works fine for me in a simple .Net Core 8.0 project. But not for a .Net MAUI project.

Can you imagine, that this is a problem of your code? If not, I will try to find a Microsoft member to take a look at this.

My code:

    internal class MyClass : INetworkConnectionCostEvents
    {
        public void Initialize()
        {
            var networkListManager = new NetworkListManager();

            var guid = typeof(INetworkConnectionCostEvents).GUID;
            ((IConnectionPointContainer)networkListManager).FindConnectionPoint(ref guid, out var connectionPoint);
            connectionPoint.Advise(this, out var cookie);
        }
 
        public HRESULT ConnectionCostChanged(Guid connectionId, NLM_CONNECTION_COST newCost)
        {
            return 0;
        }

        public HRESULT ConnectionDataPlanStatusChanged(Guid connectionId)
        {
            return 0;
        }
    }

Both methods will never executed.

**Comment by dahall** [comment]
That is curious. There is nothing too special about this implementation. Threading model? COM initialization? Annotating the class with `[ComVisible(true)]` maybe?

**Comment by NilsHoyer** [comment]
[ComVisible(true)] and CoInitializeEx() doesn't help.

Now I will try to get the INetwirkLostManager object on the recommended way:

    INetworkListManager *pNetworkListManager = NULL; 
    HRESULT hr = CoCreateInstance(CLSID_NetworkListManager, NULL,
            CLSCTX_ALL, IID_INetworkListManager,
            (LPVOID *)&pNetworkListManager);

If this doesn't work, I will mention this issue to the MAUI developers.

**Comment by NilsHoyer** [comment]
I didn't find a solution, so I will inform the MAUI project about this issue.
