### ISSUE TITLE
Code analysis attribute polyfills should be internal, not public

### ISSUE THREAD

**Issue by brantburnett** [dahall/Vanara#485]
**Describe the bug and how to reproduce**

When polyfilling code analysis attributes from modern .NET to a library, they should be `internal` and not `public`. Leaving them public will cause build errors for any consumers that may have their own polyfills.

More importantly, if two different libraries being consumed, i.e. Vanara and some other library, both add public polyfills then it will cause build errors. To avoid this, all NuGet packages should keep the polyfills internal.

In the example below, [Polyfill](https://www.nuget.org/packages/Polyfill) is being used to add these code analysis attributes and a wide variety of other polyfills, but it is conflicting with Vanara once we upgrade Vanara to 4.x.

```
error CS0433: The type 'NotNullWhenAttribute' exists in both 'AdvantagePolyfill, Version=24.15.2.2668, Culture=neutral, PublicKeyToken=null' and 'Vanara.Core, Version=4.0.3.0, Culture=neutral, PublicKeyToken=c37e4080322237fa'
```

**What code is involved**

[The method, file path and library causing the issue. If you have code that will reproduce the bug, please include it here.](https://github.com/dahall/Vanara/blob/1638eb955b0220c5e626fb142abd0b530292cc4c/Core/BkwdComp/CodeAnalysis.cs)

**Expected behavior**

The presence of polyfills in Vanara should not affect external builds.

**Comment by dahall** [comment]
These are backported classes that have to remain public since they are used in multiple Vanara libraries.

**Comment by brantburnett** [comment]
> These are backported classes that have to remain public since they are used in multiple Vanara libraries.

I realize this may be a hot take, but I do feel like this is the incorrect approach, as this makes your library incompatible with other libraries. Primarily this incompatibility is with other "poor citizen" libraries that also make their members public, though it does include other cases such as `Polyfill` mentioned above.

The .NET runtime itself has the same issue with their down-level libraries. Their solution is to use shared files and include them in every down-level package as internals. This is a bit of bloat, as every package gets a copy of the attributes, but it ensures compatibility and the bloat isn't that significant. https://github.com/dotnet/runtime/blob/ad0c47c42e8901b9300701b237c42345b83c2bd9/src/libraries/Directory.Build.targets#L170-L177

Another option would be the use of the InternalsVisibleTo attribute, though admittedly that can get a bit tricky when dealing with signed assemblies. In the inverse direction, there is also the `IgnoresAccessChecksToAttribute` which can be added to the consuming assembly rather than the defining assembly. But this attribute isn't included in the framework, it's a "hidden" runtime feature typically used for things like dynamic assembly generation, so it would also need to be polyfilled in every assembly.

Of course, since 4.0 has already been released, changing this now could cause backward compatibility issues for consumers, so I do understand the change may require waiting until you're ready for a 5.0 release. But I do think it's worth considering. In at least my case it will require me to either remain on 3.0 (which has trimming problems) or not use the library at all until I've gotten this project moved from .NET 4 to .NET 8 (which we're doing but it's a long, slow slog).

**Comment by dahall** [comment]
I like the shared code approach. Let me see if I can make that work.
