### ISSUE TITLE
Connectivity.NetworkAccess reports "Internet" without an internet connection on Android

### ISSUE THREAD

**Issue by NilsHoyer** [dahall/Vanara#486]
Inside the Connectivity.ConnectivityChanged event handler, Connectiviy.NetworkAccess reports "Internet" after disabling WLAN and without Mobile Data on my Android device.

I updated all software, but this doesn't help.

**Comment by dahall** [comment]
I believe the code you reference is from [Microsoft](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.networking.connectivity.connectivitychanged?view=net-maui-8.0), not Vanara. Please close this issue if that assumption is correct.

**Comment by NilsHoyer** [comment]
I'm very sorry, I posted this issue on the wrong place, please excuse me. 😓
