### ISSUE TITLE
[UxTheme.dll] GetThemeBitmap function is outdated

### ISSUE THREAD

**Issue by NickAcPT** [dahall/Vanara#5]
Hello, according to [the MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/bb773388(v=vs.85).aspx), the GetThemeBitmap pinvoke is outdated.

Probably there are more functions that don't need the hDc argument.

According to the MSDN:
```
HRESULT GetThemeBitmap(
  _In_  HTHEME  hTheme,
  _In_  int     iPartId,
  _In_  int     iStateId,
  _In_  int     iPropId,
  _In_  ULONG   dwFlags,
  _Out_ HBITMAP *phBitmap
);
```

Your P/Invoke:
```
HRESULT GetThemeBitmap(
  UxTheme.SafeThemeHandle hTheme,
  Gdi32.SafeDCHandle hdc,
  int iPartId,
  int iStateId,
  int iPropId,
  int dwFlags,
  out IntPtr phBitmap
);
```

When running the code, this can be confirmed by Visual Sudio's Managed Debugging Assistant:
```
Managed Debugging Assistant 'PInvokeStackImbalance' :
'A call to PInvoke function 'Vanara.PInvoke.UxTheme!Vanara.PInvoke.UxTheme::GetThemeBitmap' has unbalanced the stack.
This is likely because the managed PInvoke signature does not match the unmanaged target signature.
Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'
```

Thank you for the time you put to make this project into something really good and usable.

**Comment by dahall** [comment]
I'm doing some testing to ensure this works. Have you found a class/part/state combination where GetThemeBitmap and GetThemeStream work? I have validated that they don't throw exceptions, but I'd like to know if they actually work.

**Comment by NickAcPT** [comment]
Hello, GetThemeBitmap can be used to get the titlebar buttons from the basic theme.
[Real world usage of GetThemeBitmap (Using the GetBitmap method from the VisualTheme class)](https://github.com/NickAcPT/OpenTitlebarButtons/blob/master/OpenTitlebarButtons/Utils/NativeThemeUtilsBasic.cs#L41)

GetThemeStream can be used to get the image atlas of the dwmwindow.
[Real world usage of GetThemeStream (Using the GetDiskStream method from the VisualTheme class)](https://github.com/NickAcPT/OpenTitlebarButtons/blob/master/OpenTitlebarButtons/Utils/NativeThemeUtilsAero.cs#L83)

**Comment by dahall** [comment]
I've almost completed full unit testing on the whole of UxTheme. Thank you for those examples! You should see 1.0.15 pushed in the next couple of days with updates to UxTheme and Windows.Forms with updates to the base methods and the VisualTheme helper class.

**Comment by dahall** [comment]
Took a few days, but the update (1.0.15) is now available on NuGet. Thanks for pushing me to fully unit test this module.

**Comment by NickAcPT** [comment]
I'm the one that needs to thank your for this amazing project.
