### ISSUE TITLE
Kernel32.WaitForDebugEventEx throws TypeLoadException

### ISSUE THREAD

**Issue by alexrp** [dahall/Vanara#50]
**Describe the bug**
Attempting to use the `Kernel32.WaitForDebugEventEx` API results in this exception:

```
Unhandled Exception: System.TypeLoadException: Could not load type 'EXCEPTION_INFO' from assembly 'Vanara.PInvoke.Kernel32, Version=2.3.8.0, Culture=neutral, PublicKeyToken=c37e4080322237fa' because it contains an object field at offset 0 that is incorrectly aligned or overlapped by a non-object field.
```

**What code is involved**
Something along these lines:

```csharp
if (Kernel32.DebugActiveProcess(pid))
    while (Kernel32.WaitForDebugEventEx(out var ev, Kernel32.INFINITE))
        Kernel32.ContinueDebugEvent(ev.dwProcessId, ev.dwThreadId, Kernel32.DEBUG_CONTINUE.DBG_CONTINUE);
```

**Expected behavior**
No `TypeLoadException`.

**Comment by dahall** [comment]
Thanks. I have confirmed the bug and am working through finding a fix. I'll report back once I have it resolved. It may require code changes I'm afraid given my initial assessment.

**Comment by dahall** [comment]
Corrected code has been posted and should build if you need fix now. Otherwise, I'll release by the weekend with some other updates I'm still testing.
