### ISSUE TITLE
AccessibleObjectFromWindow

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#51]
**Describe the additions or enhancements you'd like**
Add AccessibleObjectFromWindow, AccessibleObjectFromEvent, AccessibleObjectFromPOint

https://www.pinvoke.net/default.aspx/oleacc.accessibleobjectfromwindow
https://www.pinvoke.net/default.aspx/oleacc.accessibleobjectfromevent
https://www.pinvoke.net/default.aspx/oleacc.AccessibleObjectFromPoint

**Comment by dahall** [comment]
These are pretty easy to implement for .NET 2.0-4.5. However, the IAccessibility interface, available in Accessibility.dll, is not available for .NET Standard or .NET Core < 3.0. Is that OK?

**Comment by dahall** [comment]
If you're ok with the framework restrictions, I can release this weekend. Please confirm.

**Comment by NN---** [comment]
It is okay
