### ISSUE TITLE
AdvApi32 CredEnumerate marshals error

### ISSUE THREAD

**Issue by Herve-M** [dahall/Vanara#54]
**Describe the bug**
`AdvApi32.CredEnumerate` call is not functionning, throwing an `System.ExecutionEngineException: 'Exception of type 'System.ExecutionEngineException' was thrown.'`

**What code is involved**
[`AdvApi32.CredEnumerate`](https://github.com/dahall/Vanara/blob/c8cb9a29d7dbb85ec3e6b8326ec3537181b88833/PInvoke/Security/AdvApi32/WinCred.cs#L330) and after some fast research underlying [`handle.ToArray`](https://github.com/dahall/Vanara/blob/c8cb9a29d7dbb85ec3e6b8326ec3537181b88833/PInvoke/Security/AdvApi32/WinCred.cs#L1517) 

**Expected behavior**
Returning a array of Credential object. 

**Other** 
Some CredAPI could be impr. and a PR is on this way too.

**Comment by dahall** [comment]
Thank you for doing the work on the PR! Would you like me to fix `CredEnumerate` or will you do that as part of your PR?

**Comment by dahall** [comment]
If you're looking at Vanara.PInvoke.Crypt32, please note that it has been superceded by Vanara.PInvoke.Cryptography.

**Comment by dahall** [comment]
Before working too much on a PR, please look at the fixes I just posted. CREDENTIAL now marshals correctly. My implementation of the CredEnum didn't cast to a pointer before getting the structure. It now does. Those two changes should make the other functions work better.

**Comment by Herve-M** [comment]
Okay I see that you have fixed/impr. some part as `struct CREDENTIAL` and `CredEnumerate` flag param. 
Thanks you was faster than me! Will test this fix.

**Comment by dahall** [comment]
Fixed and released in 2.3.11 today
