### ISSUE TITLE
MarshalDirectiveException when using CommandLineToArgvW()

### ISSUE THREAD

**Issue by alexrp** [dahall/Vanara#56]
**Describe the bug**
```
Cannot marshal 'return value': Invalid managed/unmanaged type combination.
  + Vanara.PInvoke.Shell32.CommandLineToArgvW(string, out int)
```

**What code is involved**
```csharp
> #r "Vanara.PInvoke.Shell32.dll"
> using Vanara.PInvoke;
> Shell32.CommandLineToArgvW("", out _)
```

**Expected behavior**
No exception.

**Comment by dahall** [comment]
Yep. I screwed up on this one. I know how to fix and will post the update tomorrow and include in the next release.

**Comment by dahall** [comment]
It is corrected and pushed. I'll include it in the next release later in the week.
