### ISSUE TITLE
CreateProcessWithTokenW has invalid signature

### ISSUE THREAD

**Issue by slowik-marcin** [dahall/Vanara#57]
**Describe the bug**
The method CreateProcessWithTokenW  in AdvApi32/.Vanara.PInvoke.Security.dll has invalid signature.

**What code is involved**
`public static extern bool CreateProcessWithTokenW(HTOKEN hToken, ProcessLogonFlags dwLogonFlags, string lpApplicationName, [Optional] StringBuilder lpCommandLine, CREATE_PROCESS dwCreationFlags,
			[Optional] IntPtr lpEnvironment, [Optional] string lpCurrentDirectory, in STARTUPINFO lpStartupInfo, [Out] PROCESS_INFORMATION lpProcessInformation);
`

**Expected behavior**
According to MSDN the last parameter (LPPROCESS_INFORMATION lpProcessInformation)
should be an out parameter.
Expected: `[Out] out PROCESS_INFORMATION lpProcessInformation`

**Screenshots**
None.

**Comment by dahall** [comment]
That would be true if `PROCESS_INFORMATION` was defined as `struct`. It is a class and is therefore already passed by reference. Thus that application of the `OutAttribute` to inform the marshaler that the class is being updated on the way back. Are you getting an error? In my unit testing, it worked.

**Comment by dahall** [comment]
I found the problem. It is not in the signature of the function, it is in the implementation of the class `PROCESS_INFORMATION`. It will be corrected shortly.

**Comment by slowik-marcin** [comment]
The `PROCESS_INFORMATION ` doesn't have a public constructor. 

I have also reviewed it's usage and in `Kernel32.CreateProcess`  (and other places) it is used with `out `specifier and internally instantiated using a struct recieved from the WinAPI.

PROCESS_INFORMATION is used with [Out] attribute in other places like, `CreateProcessAsUser`, `CreateProcessWithLogonW`, but none of them have unit tests.

Note: I was writing this message when your last answer popped out.

**Comment by dahall** [comment]
Thanks for pointing all this out. Turns out it was bad naming and some inconsistency between assemblies. It has been corrected now. I decided to make it a breaking change due to the immensity of my mistake. I need users to know it is broken so they fix it. This code now works for the function:
```cs
using (var pTok = SafeHTOKEN.FromProcess(GetCurrentProcess()))
using (var hTok = pTok.DuplicateImpersonate())
{
   var b = CreateProcessWithTokenW(hTok, 0, "notepad.exe", null, 0, default, default,
      STARTUPINFO.Default, out var pi);
   if (b) WaitForSingleObject(pi.hProcess, INFINITE);
}
```
I'll post all these changes to GitHub and then will include them in the next release early next week.
