### ISSUE TITLE
How this differs from https://github.com/AArnott/pinvoke ?

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#6]
I think it will be better to have one project instead of two.
https://github.com/AArnott/pinvoke

**Comment by dahall** [comment]
Before I decided to start this project, I corresponded with that project's owner. We had two different approaches. Theirs was more of a pure approach, using unsafe code extensively. I wanted to focus on usability more with helper classes, functions and marshalers. Thus, I decided to start this project.

**Comment by NN---** [comment]
I think you should just use PInvoke project and add wrapping instead of doing the same work twice.
I had also a talk with the owner of PInvoke and I know what you mean.

**Comment by dahall** [comment]
Duplicating work, I agree, is inefficient. However, I think I'll keep down this path so that I can continue to focus on making the library's use as simple as possible.

**Comment by NN---** [comment]
At least there should be a common nuget with all base types , e.g. SafeHandles.
I suggest to discuss with with PInvoke author.
This can de-duplicate some work.
