### ISSUE TITLE
TaskDialog fails with ArgumentException in 64-bit process

### ISSUE THREAD

**Issue by snechaev** [dahall/Vanara#61]
**Describe the bug**
When I tried to use Vanara.Windows.Forms.TaskDialog in 64 bit WinForms app, I got ArgumentException in TaskDialog.ShowDialog method.

**What code is involved**
* Simple just created WinForms app, with one form and one button on it.
* In button click handler I have the following code
```
        private void button1_Click(object sender, EventArgs e)
        {
            using (var dlg = new TaskDialog())
            {
                dlg.ShowDialog();
            }
        }
```
* **Critical**: in build settings I have AnyCPU and "Prefer 32-bit" checkbox **unchecked**.
* I run this on 64-bit Win10 pro.

**Expected behavior**
TaskDialog displayed.

**ActualBehavior**
System.ArgumentException in the ShowDialog.

If I will check "Prefer 32-bit" checkbox (and thus the process will run in 32 bit mode even on 64 bit Windows), all works as expected.

**Comment by dahall** [comment]
I just ran the following two tests without error on Win10 64bit v1803 with the same build settings. I would check the combination of properties you've set. If you post the code for your dialog setup, I'm glad to help troubleshoot it if this code doesn't help. By the way, this comes from the unit tests in the project. If you're ever looking for help on how to use a class or function, I encourage you to look there first.
```cs
using System.Windows.Forms;

public void TaskDialogTest()
{
   var td = new TaskDialog
   {
      ButtonDisplay = TaskDialogButtonDisplay.CommandLink,
      Content = "Content text, Content text, Content text, Content text, Content text, Content text, Content text, Content text, Content text, Content text, Content text, Content text",
      MainInstruction = "Main Instruction",
      WindowTitle = "Title"
   };
   td.Buttons.Add(new TaskDialogButton("Try this"));
   td.Buttons.Add(new TaskDialogButton("Try that"));
   td.ShowDialog();

   td.Reset();
   td.RadioButtons.Add(new TaskDialogRadioButton("Radio 1", 20));
   td.RadioButtons.Add(new TaskDialogRadioButton("Radio 2", 21) { Enabled = false });
   td.DefaultRadioButton = 20;
   td.MainInstruction = "Radio Instruction";
   td.CommonButtons = TaskDialogCommonButtons.Ok | TaskDialogCommonButtons.Cancel;
   td.ShowDialog();
}

public void ShowTest1()
{
   var i = TaskDialog.Show("Main instruct", "Caption", new[] { "Test1", "Test2" }, TaskDialogIcon.Shield);
}
```

**Comment by dahall** [comment]
I'm also not saying there isn't a bug in the code, but I can't know until I see what configuration you're using and can duplicate it.

**Comment by dahall** [comment]
Found the bug. There is an easy workaround until I get the next version released. Simply set the `CommandButtons` property to something other than `None`.
```cs
using (var dlg = new TaskDialog { CommandButtons = TaskDialogCommonButtons.Cancel })
   dlg.ShowDialog();
```
