### ISSUE TITLE
Request; WM_SYSCOMMAND enum

### ISSUE THREAD

**Issue by Bert-Proesmans** [dahall/Vanara#62]
I could not find the WM_SYSCOMMAND enumeration mapping in the Vanara libs.
It's also hard to find out if an enumeration is mapped without having a method that uses it as starting point.
Eventually i imported all Vanara libraries into DotPeek and used the search tool to find variants of these enumerations, but couldn't find anything.

Please also map the WM_SYSCOMMAND enumeration. (https://docs.microsoft.com/en-us/windows/win32/menurc/wm-syscommand)

Thank you.

**Comment by dahall** [comment]
[PInvoke/User32/User32_WindowMessage.cs](https://github.com/dahall/Vanara/blob/6b8e0ccf586f9849aff5d9f259656c10e12324f1/PInvoke/User32/User32_WindowMessage.cs) line 650. I just use the GitHub search for the repository. Typically, I will try to put the declarations in a file named after the header file if that helps in the future.

**Comment by dahall** [comment]
Sorry, were you looking for the SC_* enum?

**Comment by dahall** [comment]
Just in case, they were not there but I have just added them to User32/WinUser.Windows.cs. They'll get included in the next release I hope to have out in the next week.

**Comment by Bert-Proesmans** [comment]
Great! Thank you for your hard work.

I also made mistakes confusing WM_*, WC_*, SC_* with other enumerations. That's why I love your library so much, in a C# playground it becomes an interactive man page.
