### ISSUE TITLE
Parameter problem with User32.LockSetForegroundWindow function

### ISSUE THREAD

**Issue by okman523** [dahall/Vanara#63]
**Describe the bug**

User32.LockSetForegroundWindow hánshù shūrù cānshù uLockCode shì bool lèixíng, dànshì cān shǔ shuōmíng xiě de shì Uint lèixíng, cān shǔ shuōmíng de Uint lèixíng yǔ guānfāng de API shì yīzhì de, shì xiě cuòle cānshù lèixíng?
101/5000
The User32.LockSetForegroundWindow function input parameter uLockCode is a bool type, but the parameter description is written as a Uint type. The Uint type of the parameter description is consistent with the official API. Is the wrong parameter type written?

**What code is involved**
Describe the method and library causing the issue:

**Expected behavior**

**Screenshots**

**Comment by dahall** [comment]
Thanks for the catch. I have updated the function definition to use an enum with the expected values and committed the changes. It will appear in the next release.
