### ISSUE TITLE
Missing IO control codes and structs from Kernel32

### ISSUE THREAD

**Issue by dboikliev** [dahall/Vanara#67]
**Describe the additions or enhancements you'd like**
Many of the functions and structs under Kernel32 are present. However some of the structs and IO control codes used by DeviceIoControl upon which I depend ([and others](https://docs.microsoft.com/en-us/windows/win32/api/winioctl/)) are missing:
- Codes
FSCTL_QUERY_USN_JOURNAL
FSCTL_ENUM_USN_DATA
FSCTL_READ_USN_JOURNAL
FSCTL_CREATE_USN_JOURNAL
- Structs
MFT_ENUM_DATA
USN_RECORD
USN_JOURNAL_DATA

Are there plans on extending Kernel32 to contain these and the rest?

**Comment by dahall** [comment]
I will add them to my list for the next release.

**Comment by dahall** [comment]
In case you are using the code and not the builds or can build yourself, I have completed all the codes, enums and your requested structures. I still have almost 100 structures left to do, but wanted to get you going if you could.

**Comment by dboikliev** [comment]
Thank you for your quick response!
