### ISSUE TITLE
Request: Some Shell Constants                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Request: Some Shell Constants: CSIDL_* / SID_*                                                                                                             

### ISSUE THREAD

**Issue by tajbender** [dahall/Vanara#69]
**Is your feature request related to a problem? Please describe.**
I've just created a helper class saving and restoring the Desktop Icon Layout. I've used this approach, just for your interest: https://devblogs.microsoft.com/oldnewthing/?p=4933

**Describe the additions or enhancements you'd like**
It would be nice and perhaps useful for others to have some (missing) constants in Vanara Shell Libraries:

` // Shlobj.h:`
`public static int CSIDL_DESKTOP = 0x0000;`
` // shobjidl_core.h:`
`public static Guid SID_STopLevelBrowser = new Guid("4C96BE40-915C-11CF-99D3-00AA004AE837");`

**Previous work**
In `Vanara\PInvoke\Shell32\ShlObj.cs` you've already imported some of those Shell Constant IDs. However, there are many more: https://docs.microsoft.com/en-us/windows/win32/shell/csidl

Any reason why you don't just throw them in all, or is it because some of them have been superseded by `KNOWNFOLDERID`s?

**Comment by dahall** [comment]
Yes, my logic was to put the work into KNOWNFOLDERID rather than the obsolete CSIDL constants. I'm glad to add them all along with the SID_ constant(s). Give me a week or so to get them into a release.

**Comment by dahall** [comment]
All the CSIDL* and SID_S* constants have been added to the Vanara.PInvoke.Shell32 class. They will go out in the next release due in less than a week.

**Comment by tajbender** [comment]
Thank you so much, again :)
