### ISSUE TITLE
AccessViolationException - calling Shell32.IShellFolder.GetDisplayNameOf()

### ISSUE THREAD

**Issue by Sherulez** [dahall/Vanara#73]
**Describe the bug**
`System.AccessViolationException` while calling `IShellFolder.GetDisplayNameOf()`

**What code is involved**
```csharp 
//...
string dName = shellFolder.GetDisplayNameOf(pidlSub, SHGDNF.SHGDN_FORPARSING);
```
`shellFolder `and `pidlSub` are both correctly implemented.

**Expected behavior**
No `AccessViolationException`

Not sure but I think your STRRETMarshaler does something wrong with the STRRET ptr

Note that a custom IShellFolder Interface
```csharp 
...
void GetDisplayNameOf(PIDL pidl, SHGDNF uFlags, out STRRET pName);
...
```

And a custom `StrRetToBSTR `to get the string
```csharp 
[DllImport("shlwapi.dll")]
public static extern void StrRetToBSTR([In, Out] ref STRRET pstr, [In] IntPtr pidl, [Out, MarshalAs(UnmanagedType.BStr)] out string pbstr); 
```

Works well for me.

**Comment by dahall** [comment]
Thanks for finding this. It is now corrected, though it required changing the signature of the function.
