### ISSUE TITLE
SID_NAME_USE enum: SidTypeLogonSession=11 seems to be missing

### ISSUE THREAD

**Issue by donid** [dahall/Vanara#74]
LookupAccountSid just returned '11' for the 'use' parameter and it seems to be missing in the SID_NAME_USE enumeration

see also: https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ne-ntifs-_sid_name_use

**Comment by dahall** [comment]
Thanks. I added `SidTypeLogonSession` which has the value of 11 to the SID_NAME_USE enum type.
