### ISSUE TITLE
(Winuser.h) WINDOWINFO RECT Values not accurate (?)

### ISSUE THREAD

**Issue by Sherulez** [dahall/Vanara#75]
**EDIT  :** 

After more investigations it seems that it is the whole structure "`WINDOWINFO`" which poses problem. 
 `dwStyle`, `atomWindowType ` etc... all return null or inconsistent values.

Using pInvoke.net as a reference for `GetWindowInfo` and `WINDOWINFO` everything works fine.

It should be in this order : 

```csharp
            ...
            public uint cbSize;
            public RECT rcWindow;
            public RECT rcClient;
            public uint dwStyle;
            public uint dwExStyle;
            public uint dwWindowStatus;
            public uint cxWindowBorders;
            public uint cyWindowBorders;
            public ushort atomWindowType;
            public ushort wCreatorVersion;
            ...
```

---

**Describe the bug**
RECT values not accurates (?)

**What code is involved**

C++
```cpp 
WINDOWINFO wi;
wi.cbSize = sizeof(WINDOWINFO);

GetWindowInfo(hWnd, &wi);		
RECT rect = wi.rcWindow;

std::cout << rect.right << std::endl;	//	output 1920 <--------
std::cout << rect.bottom << std::endl;	//	output 1080 <--------
```
-----------
C#
```csharp
WINDOWINFO wf = new WINDOWINFO
{
    cbSize = 60
};

GetWindowInfo(ghDesk, ref wf);
Vanara.PInvoke.RECT rect = wf.rcWindow;

Console.WriteLine(rect.right);      // output 0 <--------
Console.WriteLine(rect.bottom);     // output 83935485 <--------
```
(the hwnd is the same, same window)

**Expected behavior**
Same values

Not sure if this is a bug or if it's me missing something :)

By the way, `wf.cyWindowBorders` return `1920` with Vanara but return` 0` in C++

**Comment by Sherulez** [comment]
I ended up doing it this way, since it works well : 

```csharp
Vanara.PInvoke.RECT rect;
if (GetWindowRect(ghDesk, out rect))
{
    int width = rect.right - rect.left;
    int height = rect.bottom - rect.top;

    Console.WriteLine(width);           // 1920
    Console.WriteLine(height);          // 1080

    Console.WriteLine(rect.Width);      // 1920
    Console.WriteLine(rect.Height);     // 1080
}
```

**Comment by dahall** [comment]
Thanks for the bug report and the workaround. There was a problem with the field order in my implementation of `WINDOWINFO`. That is now fixed.
