### ISSUE TITLE
IFolderView.SelectAndPositionItems -> MarshalDirectiveException

### ISSUE THREAD

**Issue by Sherulez** [dahall/Vanara#76]
**Describe the bug**

_Vanara.PInvoke.Shell32.IFolderView (SelectAndPositionItems)
Vanara.PInvoke.Shell32.IFolderView2 (SelectAndPositionItems)_

> System.Runtime.InteropServices.MarshalDirectiveException : 'Cannot marshal 'parameter 2': Invalid managed/unmanaged type combination (Arrays of SafeHandles are not supported).'

**What code is involved**
```csharp
...
PIDL[] pIDLs = { pidlsub };
Point[] points = { pt };

FolderView.SelectAndPositionItems(1, pIDLs, points, SVSIF.SVSI_POSITIONITEM);
```

**Expected behavior**
No MarshalDirectiveException

**Note**
`pidlsub` is valid, and work well with other PIDL related function.
He is from IEnumIdList.Next

**Comment by Sherulez** [comment]
A good hint I guess : https://stackoverflow.com/questions/16548353/workaround-to-add-a-default-parameterless-constructor-to-a-struct :)

**Comment by dahall** [comment]
Thank you for the report and the exception information. Using it, I was able to identify the bug and fix it. Effectively, any time I have used `PIDL[]`, I have changed it to `IntPtr[]` to avoid the marshaling error. However, this will require that before passing your `PIDL[]`, you convert it using something like `Array.ConvertAll(pIDLs, p => (IntPtr)p)`. I will release it with the 3.1.7 release in the next couple of weeks.

**Comment by Sherulez** [comment]
You're welcome, thanks to you for your amazing work :)

**Comment by Sherulez** [comment]
I tried by taking example on your last commits, it works well ! 

But I have a small question (a bit out of context sorry) let's take this code: 

``` csharp
while (IStream_ReadPidl(stream, out IntPtr ppidlOut) == HRESULT.S_OK)
{

    PIDL pIDL = ppidlOut;
    PIDL[] pIDLs = { pIDL };

    Point pt;
    byte[] ptByte = new byte[155];
    stream.Read(ptByte, ptByte.Length, IntPtr.Zero);

    BinaryFormatter bf = new BinaryFormatter();
    using (MemoryStream ms = new MemoryStream(ptByte))
    {
        object obj = (Point)bf.Deserialize(ms);
        ms.Position = 0;
        pt = (Point)obj;
    }


    IntPtr[] intPtrs = Array.ConvertAll(pIDLs, p => (IntPtr)p);
    Point[] points = { pt };

    ((NativeMethods.IFolderView)FolderView1).SelectAndPositionItems(1, intPtrs, points, SVSIF.SVSI_POSITIONITEM);


    pIDL.Dispose();

}
```

Do I have to worry about freeing `intPtrs` and `pIDLs ` ?
Sorry if it's a silly question, I do not know much about unmanaged memory.

**Comment by dahall** [comment]
Thanks for testing my committed code. Glad it works for you. On you second post, I'm not sure what you are freeing with `Marshal.FreeCoTaskMem(pidlSub);` Using the implicit conversion from `IntPtr` to `PIDL` on the second line, you are telling `PIDL` to own the pointer and the allocated memory behind it. Calling `Dispose` on it frees all the memory allocated by the call to `IStream_ReadPidl`. Below is how I would have written the loop:
```cs
while (IStream_ReadPidl(stream, out IntPtr ppidlOut).Succeeded)
{
   using (PIDL pIDL = ppidlOut)
   {
      Point pt;
      byte[] ptByte = new byte[155];
      stream.Read(ptByte, ptByte.Length, IntPtr.Zero);

      BinaryFormatter bf = new BinaryFormatter();
      using (MemoryStream ms = new MemoryStream(ptByte))
      {
         object obj = (Point)bf.Deserialize(ms);
         ms.Position = 0;
         pt = (Point)obj;
      }

      ((NativeMethods.IFolderView)FolderView1).SelectAndPositionItems(1, new[] { ppidlOut }, new[] { pt }, SVSIF.SVSI_POSITIONITEM);
   }
}
```

**Comment by dahall** [comment]
I'm also going to look at why I didn't use PIDL for the second argument typ on `IStream_ReadPidl`. I may change that in a future release.
