### ISSUE TITLE
SourceLink support

### ISSUE THREAD

**Issue by NN---** [dahall/Vanara#77]
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink

Just add package and relevant properties, see: https://github.com/rsdn/CodeJam/commit/f71645af713a27e8e299e8ab329b2ff5381e3e5d#diff-29625df1d8c0f40d09db6e8f2cdfb7ecR30

```xml
	<PropertyGroup>
		...
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All"/>
	</ItemGroup>
```

**Comment by dahall** [comment]
Great idea. Let me see if I can get it into the next release.

**Comment by dahall** [comment]
Done! You'll see this support in 3.1.7 due in the next week.
