### ISSUE TITLE
PathEx.GetUNCServer returns truncated result

### ISSUE THREAD

**Issue by kimhunsoo** [dahall/Vanara#78]
**Describe the bug**

Running PathEx.GetUNCServer(@"\\\\diskstation\\t\\") returns "diskstat" ("ion" is truncated)

**What code is involved**

In the StringHelper.GetString(ptr, charSet, allocatedBytes) method, allocatedBytes is passed path.Length * 1 and chkLen is counted as length * 2, making the comparison incorrect.

**Comment by dahall** [comment]
Thanks. Failed to account for Unicode and null terminator. Now fixed.
