### ISSUE TITLE
Change signature of method GetSystemMetricsForDpi to use SystemMetric enum.

### ISSUE THREAD

**Issue by Yomodo** [dahall/Vanara#79]
**Describe the additions or enhancements you'd like**
The signature of `GetSystemMetrics` is: `GetSystemMetrics(SystemMetric nIndex)`
The signature of `GetSystemMetricsForDpi` is: `GetSystemMetricsForDpi(int nIndex, uint dpi)`

Change the signature for consistency: `GetSystemMetricsForDpi(SystemMetric nIndex, uint dpi)`

Thank you for your hard work on this library, very much appreciated!

**Comment by dahall** [comment]
Thanks for pointing out the inconsistency. I have corrected it.
