### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by Yomodo** [dahall/Vanara#80]
I have a couple of pinvokes that are not available in Vanara, like:

`advapi32.dll`: `CreateProcessAsUserW`
`wtsapi32.dll`: `WTSQueryUserToken`
`userenv.dll`: `CreateEnvironmentBlock`, `DestroyEnvironmentBlock`

Are there any specific requirements to add these (or other Win32API's) to Vanara?
I am willing to do the work of integrating these pinvokes and create PR's for approval and inclusion.

**Comment by dahall** [comment]
The first one, `CreateProcessAsUser` can be found in `Vanara.PInvoke.Security` in the `AdvApi32` class. (The `W` is removed.)

The other two are in DLLs that I haven't tackled yet. Your request is the first I've seen for WTS functions. The last one, `CreateEnvironmentBlock` belongs to a set of functions for User Profiles that looks useful and has had other requests. I'll add that to my list, though I'm not sure how long it will take me to get to it. If you are interested in doing the work to port those functions (looks like they're all documented [here](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/bb776901%28v%3dvs.85%29)), I'd be happy to create the project file for you and send it via zip so you can do that work.

**Comment by Yomodo** [comment]
Sure, I'd be happy to help out where I can.
A zip file you say? Is it not just a matter of fork/clone the repro and get busy?

**Comment by dahall** [comment]
I have a predefined project file and naming convention for new DLL projects is all.

**Comment by dahall** [comment]
Actually, if you want to get started, you can just copy the project directory for `Vanara/PInvoke/UrlMon` and just change all file names and internal .csproj references from `UrlMon` to `UserEnv`, including the project directory. I have a tool I've created to pull the documentation from the web, so don't worry about that. If you end up testing the code, please send along the test methods and I'll add them to the NUnit tests.

**Comment by dahall** [comment]
If you haven't already done the work to create a UrlEnv project, I have time to do it today. Let me know.

**Comment by Yomodo** [comment]
By all means, go ahead!

**Comment by dahall** [comment]
I just pushed the addition of `Vanara.PInvoke.UserEnv` with the `CreateEnvironmentBlock` and `DestroyEnvironmentBlock` methods implemented. I didn't create any unit tests yet, nor have I tested those functions. If you're up to the task, I'll add your related PR. Thanks.

**Comment by dahall** [comment]
Actually, I decided to add a test project for UserEnv. (I was curious if my marshaling class worked.) Give me a few minutes to get it running and I'll push it out.

**Comment by dahall** [comment]
Done. The test project is now pushed too. (And the marshaler worked!)

**Comment by Yomodo** [comment]
Cool! I will test the code and make the appropriate unit tests. Will start tomorrow.

**Comment by Yomodo** [comment]
I'm working on the unit tests for Create-/DestroyEnvironment block. These should be easy.

Nice job on the Marshaller! However, DestroyEnvironment needs the InPtr that is returned from CreateEnvironment block, but that is now a string[]. I'll adjust the code accordingly.

**Comment by dahall** [comment]
It is correct as is and the unit tests are complete. Please don't change.

**Comment by dahall** [comment]
The marshaler takes the pointer from `CreateEnvironmentBlock` and converts it to a `string[]` before returning from the function. It then calls `DestroyEnvironmentBlock` after the conversion to free the native memory. The unit test is in `UnitTests\PInvoke\UserEnv\UserEnvTests.cs` and tests both functions, the create explicitly and the destroy implicitly as part of the marshaling action.

**Comment by Yomodo** [comment]
You are correct, my bad. I compared the new code with my current cold.
I did change the unit test to do some more testing.
