### ISSUE TITLE
Failure to compile project Vanara.Windows.Shell

### ISSUE THREAD

**Issue by Yomodo** [dahall/Vanara#81]
**Describe the bug**
Error CS1503 Argument 4: cannot convert from 'Vanara.PInvoke.Shell32.PIDL[]' to 'System.IntPtr[]'

**What code is involved**
`\Vanara\Windows.Shell\ShellObjects\ShellItemArray.cs`
Method: `public ShellItemArray(IShellFolder parent, IEnumerable<PIDL> pidls)`  at line 45.

Changing the signature in `Vanara\PInvoke\Shell32\ShObjIdl.cs` of method:
`public static extern HRESULT SHCreateShellItemArray(..., [In, Optional] IntPtr[] ppidl, ...);` to `PIDL[]` fixes the compilation error.

**Comment by dahall** [comment]
Went the other direction and fixed `ShellItemArray` constructor.
