### ISSUE TITLE
Favor StringComparison.OrdinalIgnoreCase over StringComparison.InvariantCultureIgnoreCase

### ISSUE THREAD

**Issue by Yomodo** [dahall/Vanara#84]
On some past projects we've favored `StringComparison.OrdinalIgnoreCase` over `StringComparison.InvariantCultureIgnoreCase`

One of the main reasons would be a slight speed increase.

Of course we should not blindly do a replace all, but it seems there a quite some places in Vanara to apply this replacement.

Two links for better explanations:
https://stackoverflow.com/questions/2749662/string-comparison-invariantcultureignorecase-vs-ordinalignorecase

https://stackoverflow.com/questions/72696/which-is-generally-best-to-use-stringcomparison-ordinalignorecase-or-stringco

**Comment by dahall** [comment]
After doing the reading you suggested, it appears that this is a better method. I'm hesitant to change existing code in case others have based their code on a certain behavior. However, on new code I'll definitely follow that guidance.

**Comment by dahall** [comment]
If there are current uses you find that produce the wrong behavior using invariant culture, please reopen this with those bugs.
