### ISSUE TITLE
Exception thrown when ShellItem::GetImage() is invoked for KnownFolder items

### ISSUE THREAD

**Issue by dboikliev** [dahall/Vanara#85]
**Describe the bug**
Exception thrown when ShellItem::GetImage() is invoked.
I am iterating over known folder items and trying to retrieve their icons/thumbnails,
The call to GetImage results in an ArgumentException with the message 'The specified type (DIBSECTION) cannot be retrieved from an object of type OBJ_BITMAP.'

e.g.
```csharp
var folder = new ShellFolder(KNOWNFOLDERID.FOLDERID_AppsFolder);
foreach (var item  folder.EnumerateChildren(FolderItemFilter.NonFolders | FolderItemFilter.Folders))
{	
	item.GetImage(new Size(32, 32), ShellItemGetImageOptions.BiggerSizeOk); // throws ArgumentException -> 'The specified type (DIBSECTION) cannot be retrieved from an object of type OBJ_BITMAP.'

 	item.GetImage(new Size(256, 256), ShellItemGetImageOptions.ThumbnailOnly);  // throws ArgumentException -> 'The specified type (DIBSECTION) cannot be retrieved from an object of type OBJ_BITMAP.'
}
```
**What code is involved**
Vanara.PInvoke.Shell32, Version=3.1.6
Vanara.PInvoke.Shell32.ShellItem::GetImage()

**Expected behavior**
 The icon/thumbnail should be returned.

**Comment by dahall** [comment]
Will you please send the stack track of the exception? I need to know which method is actually causing the problem.

**Comment by dboikliev** [comment]
**Stack trace**

```
Unhandled exception. System.ArgumentException: The specified type (DIBSECTION) cannot be retrieved from an object of type OBJ_BITMAP.
   at Vanara.PInvoke.Gdi32.GetObject[T](IGraphicsObjectHandle hgdiobj)
   at Vanara.Windows.Shell.ShellItem.GetTransparentBitmap(HBITMAP hbitmap)
   at Vanara.Windows.Shell.ShellItem.GetImage(Size size, ShellItemGetImageOptions flags)
   at Main.Program.Main()
```

**Comment by dahall** [comment]
Thank you. I was able to locate and fix the bug.
