### ISSUE TITLE
Add internal helper method that uses string.IsNullOrEmpty for .NET 3.5 and string.IsNullOrWhiteSpace for .NET 4.0+

### ISSUE THREAD

**Issue by Yomodo** [dahall/Vanara#86]
`string.IsNullOrWhiteSpace` was introduced in .NET 4.0 and is generally preferred as it also
catches strings that consists of only whitespaces.

**Comment by dahall** [comment]
Added `StringHelper.IsNullOrWhiteSpace` to address request.
