### ISSUE TITLE
Where are the constant definitions that specify NET20, NET35, NET40, etc.?

### ISSUE THREAD

**Issue by Yomodo** [dahall/Vanara#87]
Normally, one would define a VS constant on the Build page of a project, for example: `NET40`:

![image](https://user-images.githubusercontent.com/10358198/71596807-08479900-2b41-11ea-94db-f16aab051449.png)

This constant is then saved into the .csproj file, and looks something like this:

![image](https://user-images.githubusercontent.com/10358198/71596791-f4039c00-2b40-11ea-82f4-9cc06e817e4f.png)

These constants are used in code:

![image](https://user-images.githubusercontent.com/10358198/71596885-5f4d6e00-2b41-11ea-908b-ee187c320fcb.png)

But I cannot find the constant definitions for `NET20`, `NET35`, `NET40`, etc.
Perhaps I'm missing something?

**Comment by dahall** [comment]
With the new SDK style project, and when multi-targeted, the Roslyn builder automatically creates those. See https://docs.microsoft.com/en-us/dotnet/standard/frameworks.
