### ISSUE TITLE
Add AccountUtils.IsAdmin method using System.Security.Claims

### ISSUE THREAD

**Issue by Yomodo** [dahall/Vanara#94]
The current `AccountUtils.IsAdmin` method uses `WindowsPrincipal().IsInRole`

.NET 4.5 introduced [`Claims`](https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claim?view=netframework-4.8) which can also be used to determine if a user is a local administrator.

**Comment by dahall** [comment]
Is the new `Claims` functionality any better than the `IsInRole`? If so, then aren't we just complicating the code to use something new?

**Comment by Yomodo** [comment]
`.IsInRole`  uses the [WindowsBuiltInRole ](https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.windowsbuiltinrole?view=netframework-4.5) enum that only has 9 possible values, while the [WellKnownSidType](https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.wellknownsidtype?view=netframework-4.5) enum has way more values to compare to, which are `GUID` based.

**Comment by dahall** [comment]
Sure, but given that we only need the one, that is defined in both, I'm not seeing the justification. I just did some research and, for Windows accounts, it doesn't appear to have any advantages to use UserClaims.

**Comment by Yomodo** [comment]
I was a bit too fast, Hold on.

**Comment by Yomodo** [comment]
I concur, my suggestion does not offer any significant improvements over the current `IsAdmin` method.
