### ISSUE TITLE
Shell32 - Fetching multiple Item with IEnumIDList.Next()

### ISSUE THREAD

**Issue by Sherulez** [dahall/Vanara#97]
Not really a problem but rather a question (I guess?)
Regarding the `IEnumIDList` interface and his `.Next()` method.

Usually I use it like this :
```csharp
while (enumIdList.Next(1, out IntPtr pIdlOut, out _) == HRESULT.S_OK) // S_OK and not .Successed
{
// do something
}
```
The problem is that if I want to fetch more than 1 item pIdlOut must be an array (IntPtr[]), right ?
I **can't** do : 
```csharp
if (enumIdList.Next(5, out IntPtr pIdlOut, out _) == HRESULT.S_OK)
{
// pIdlOut is the last feteched pidl
// fetching more than 5 items throw an error (System.ExecutionEngineException)
}
```

Changing the `.Next()` Method to 
```csharp
HRESULT Next(uint celt, [MarshalAs(UnmanagedType.LPArray), Out] out IntPtr[] rgelt, out uint pceltFetched);
```
or
```csharp
HRESULT Next(uint celt, [MarshalAs(UnmanagedType.LPArray), In] in IntPtr[] rgelt, out uint pceltFetched);
```
Same issue.

From MSDN :
> rgelt
> Type: LPITEMIDLIST*
> The address of a pointer to an **array** of ITEMIDLIST pointers 

> The implementation must allocate these item identifiers using CoTaskMemAlloc

I guess I need to pass an already allocated array, but how ?

**Comment by dahall** [comment]
As I understand the documentation, the implementer will allocate the PIDLs. Leaving the method declaration as it is, and assuming I understand the documentation, you should be able to do the following:
```cs
while (enumIdList.Next(5, out var pIdlOut, out var cnt).Succeeded && cnt > 0)
{
   var pidls = pIdlOut.ToArray<IntPtr>((int)cnt);
   // process pidls, casting each to PIDL
   Marshal.FreeCoTaskMem(pIdlOut);
}
```
I haven't tested the above code, but it should be close. Give it a try and let me know your results.

**Comment by Sherulez** [comment]
Thank you for giving me your time. The thing is, I have an `System.ExecutionEngineException` here : 
 
```csharp
while (enumIdList.Next(5, out var pIdlOut, out var cnt).Succeeded && cnt > 0) // <---- Resharper tell me : enumIdList =  Unable to read the memory
{
}
```

This append at the second "pass" of the `while` :

![](https://i.ibb.co/gj9bfQ2/Capture.png)
![](https://i.ibb.co/GcnmNFn/Capture2.png)

_enumIdList =  Unable to read the memory_ : 
![](https://i.ibb.co/pK93B3w/3.png)

**Comment by dahall** [comment]
After reading more, I think the definition needs to be
```cs
HRESULT Next(uint celt, [MarshalAs(UnmanagedType.LPArray)] ref IntPtr[] rgelt, out uint pceltFetched);
```
and you have to pass in an array of `IntPtr` with `celt` items allocated. You then will get the number of items populated in `pceltFetched` and have to free each one with `Marshal.FreeCoTaskMem`.

**Comment by dahall** [comment]
If you can confirm, I'll update the library with the correct definition and also provide a helper method to allocate and free appropriately. What a mess of a function!

**Comment by dahall** [comment]
Nope, I'm wrong. I just looked at the definition in IDL. Here's how it would translate:
```cs
HRESULT Next(uint celt, [MarshalAs(UnmanagedType.LPArray)] IntPtr[] rgelt, out uint pceltFetched);
```

**Comment by dahall** [comment]
Implementation would look like:
```cs
var pidls = new IntPtr[5]; // Length can be any number
while (enumIdList.Next(pidls.Length, pidls, out var cnt).Succeeded && cnt > 0)
{
   for (int i = 0; i < cnt; i++)
   {
      // Give ptr to PIDL class and let it dispose of memory when out of scope
      using (var pidl = new PIDL(pidls[i]))
      {
         // Do something with new PIDL
      }
   }
}
```

**Comment by Sherulez** [comment]
I tested this, with your last .Next() method, no error 

```csharp
IntPtr[] ptrs = new IntPtr[5];

Test.IEnumIDList b = (Test.IEnumIDList) enumIdList;

while (b.Next(5, ptrs, out var cnt) == HRESULT.S_OK && cnt > 0)
{
    Debug.WriteLine(cnt); // 5 and 5 (10 item in the _folderView)
}
```

> What a mess of a function! 

True ;D

Now what to do with `ptrs` ;/

**Comment by Sherulez** [comment]
You are too fast XD

I did that with the ptrs

```csharp
while (b.Next(5, ptrs, out var cnt) == HRESULT.S_OK && cnt > 0)
{
    var ppidls = ptrs.ToArray<IntPtr>();
    
    foreach (var ppidl in ppidls)
    {
        PIDL p = new PIDL(ppidl);
        Debug.WriteLine(p.IsEmpty);
        p.Dispose();
    }
}
```

But still, you are better than me with your using ;p 
Thank you, for now I have a working solution !

**Comment by Sherulez** [comment]
By the way, since we are talking about `IEnumIdList`, I never managed to use `IEnumIdList.Skip()`.

I don't know if I have to open a new "issue" for that but `.Skip()` alway throw a `System.NotImplementedException` `E_NOTIMPL`

**Comment by dahall** [comment]
That just means that whatever object is exposing `IEnumIdList` chose not to implement the `Skip` method. It is not a by-product of the Vanara library.

**Comment by Sherulez** [comment]
That's what I thought thanks for the confirmation.

**Comment by dahall** [comment]
I just changed the definition in `Vanara.PInvoke.Shell32` to the one I thought was the correct definition and tested it. It now works as it should. I also added an extension method for `IEnumIDList` instances called `Enumerate` that will take a parameter to determine retrieval size. The default value for that parameter is set to 1. It can be used like:
```cs
// Enumerate all PIDLs in enumIdList requesting 20 at a time
IEnumerable<PIDL> pidls = enumIdList.Enumerate(20);

// Enumerate all PIDLs in enumIdList requesting 1 at a time
IEnumerable<PIDL> pidls2 = enumIdList.Enumerate();
```

**Comment by Sherulez** [comment]
Sorry to for "necroing" this question but what's the best way to use this new `Enumerate` extension method ? 
I am hesitating between : 

```csharp
using (var pidls = enumIdList.Enumerate(fv.ItemCount(SVGIO.SVGIO_ALLVIEW)).GetEnumerator())
{
    while (pidls.MoveNext())
    {
        using (var pidl = pidls.Current)
        {
            // Do something with pidl;
        }
    }
}

// OR

var pidls = enumIdList.Enumerate(fv.ItemCount(SVGIO.SVGIO_ALLVIEW));
foreach (var pidl in pidls)
{
    using (pidl)
    {
        // Do something with pidl;
    }
}
```

**Comment by dahall** [comment]
```cs
foreach (var pidl in enumIdList.Enumerate(fv.ItemCount(SVGIO.SVGIO_ALLVIEW)))
{
    using (pidl)
    {
        // Do something with pidl;
    }
}
```

**Comment by dahall** [comment]
Also, as an interesting sidenote when using this method with IShellFolder I found that calling the `ItemCount` method plus calling Next with the full number of items (86 in my case) took 92ms where as calling Next with just 1 took 96ms. In other words, adding more code didn't really improve the speed.

**Comment by Sherulez** [comment]
Thanks for the code snippet. Good idea to have tested `Next(1)++` vs` Next(many)`, indeed no big difference. 

I tested with `Parallel `(for example a task which do `Next(10)` and another which do `Next(10)` etc ...) But it is not profitable either. Maybe with 200+ items.
